;;; SK8 © 1997 by Apple Computer, Inc.
;;; The code in this file is protected under the terms of the current SK8 License.
;;; For information on this license, see http://sk8.research.apple.com
;;; Apple Computer, Inc. -- Apple Research Laboratories


;; Exports updated  2-07-96  11:15 am

(in-package :SK8)



(SK8-declare-syms :SK8 :public

                  ("Processes"
                   LOCKDATA BACKGROUND CREATIONTIME LASTRUNTIME PRIORITY
                   PROCESS PROCESSDATA PROCESSFUNCTION PROCESSLOCK PROCESSWAIT
                   STATE TOTALRUNTIME WITH\ PROCESSLOCK WITH\ TEMPORARYPROCESS)

                  ("Apple Script Object"
                   APPLESCRIPT SCRIPTTEXT INTERPRETRESULT COMPILEDSCRIPTID COMPONENTRECORD
                   DESCTYPE EXTRACTHANDLE PRECOMPILE EXECUTE)

                  ("mac widgets"
                   ISENABLED OWNER PERCENTDONE)

                  ("2-d graphics"
                   ARROW CLOSED ICON TEXT !STACKFRAMEINDEX !STACKFRAMESBLOCK ABOUTBOX ABOUTBOXBOX ABSOLUTEBOTTOM ABSOLUTETOP
                   ACCEPTSDROPS ACTIVATE ACTIVATETEXT ACTIVATEVERSIONDISPLAYED ACTIVE ACTIVEVERSION ACTORABOVE
                   ACTORBELOW ACTORSAFFECTED ACTORSBOUNDS ACTORTEXTSIZE ADDCONNECTOR ADDEDMEASPARENT ADDITEMS
                   ADDTOCLIPBOARD AFFIXEDSCROLLERS ALIGNMENTOFBOUNDSTOBOUNDS ALIGNSIZEWITHINBOX ALPHABETICALDISPLAY
                   ANCHOR ANGLE ANYELEMENT ANYSTATE ARROWCOLOR ARROWPRESSEDRENDERER ARROWS ARROWSIZE ATTACHED
                   AUTOHIGHLIGHT AUTOKEY AUTOTAB AVAILABLEVERSIONS BACKBLUE BACKGREEN BACKGROUNDRENDERER
                   BACKRED BESTSIZE BINDBYCONTENTS BODY BOTTOM BOTTOMRENDERER BOUNDEDBYCONTENTS BOUNDSRECT
                   BOUNDSREGION BOUNDSREGIONOK BRANCHIFY BREAKPOINTSVISIBLE BRINGCLOSER BRINGTOFRONT BRINGUP
                   BWPATTERNTOPATTRANSLATOR CACHECONTENTSRECTS CACHEDRECTS CACHESPIXMAP CANCELED CANEXPORT
                   CANIMPORT CAPTUREPICTURE CHANGEPARENTS CHARUNDERMOUSE CHECK CHECKCOLOR CHECKED CHECKMARK
                   CHECKSIZE CHECKSTYLE CHICAGO CLEARCLIPBOARD CLEARSELECTION CLICK CLIPBOARDOPEN CLIPTOMASK
                   CLOSEITEM COLLAPSEGNODE COLLAPSESELECTION COLLECTIONLIKE COLORCURSORRSRCTOCRSRTRANSLATOR
                   COLORDEPTH COLORPATTERNTOPPATTRANSLATOR COMMANDKEY COMMANDKEYEVENT COMPACTTREE COMPUTESIZE
                   CONNECT CONNECTED CONNECTEDACTORS CONNECTEDFROM CONNECTEDTO CONNECTORS CONSTRAINBOUNDSTOASPECTRATIO
                   CONSTRAINSIZETOASPECTRATIO CONTAINEDBY CONTAINER CONTENTAREA CONTENTS CONTENTSDRAWFUNCTION
                   CONTROLPANEL CONVERT-TO-TLA-REGIONS COPYNEXTSTATE COPYRESOURCETOPROJECT COPYSELECTIONTOCLIPBOARD
                   COPYSTATE COVERED CREATEARROW CREATEICON CREATEOFFSET CREATETEXTCOLOR CREATETEXTCOLORS
                   CREATETEXTDISPLAYITEM CREATETEXTITEMSTYLE CURRENTACTOR CURRENTCLIPTOMASK CURRENTELEMENT
                   CURRENTITEM CURRENTMENUBAR CURRENTVALUE CURRENTVALUETOTHUMBPOSITION CURRENTWINDOW CURSOR
                   CURSORLOCKED CURSORRSRCTOCURSTRANSLATOR CUTSELECTIONTOCLIPBOARD DAD DATA DEACTIVATE DEACTIVATETEXT
                   DECREMENTOWNSREGIONCOUNT DEEPCONTENTS DEEPLYVISIBLE DEFAULTMENUITEM DEFAULTRENDERSTYLE
                   DEINSTALL DELETEEARLIERVERSIONS DELETEVERSIONDISPLAYED DEPRESSED DEPRESSES DEPTH DEPTHVIEWER
                   DETACHED DIRECTION DIRTY DISABLEDMENUS DISCARD DISCONNECT DISPLAYINGACTIVEVERSION DISPLAYITEM
                   DISPLAYITEMSIZE DISPLAYITEMVSEPARATION DISPLAYMESSAGE DISPLAYSAMPLE DISPOSE DISPOSETREE DITHER DOFIRSTCLICK
                   DOUBLECLICK DOUBLECLICKINBREAKPOINT DOUBLECLICKSTYLE DOWN DOWNARROW DOWNARROWINFIELD DRAG
                   DRAGACTORS DRAGGABLE DRAGGEDOVEREVENTS DRAGGINGMOUSEENTER DRAGGINGMOUSELEAVE DRAGGINGMOUSEWITHIN
                   DRAGGINGMOUSEWITHINEVENTS DRAGONSTAGE DRAGRUBBERBAND DRAWFUNCTION DRAWSEPARATOR DRAWSTRING
                   DRAWTREE DROP DROPEVENTS DROPPED EDITDATA EDITTEXT ELEMENT ELEMENTN ELEMENTNFROMEND EMPTY
                   ENABLED ENDACTOR ENDARROW ENDBLUE ENDGEOMETRY ENDGREEN ENDOPBLUE ENDOPGREEN ENDOPRED ENDPOINT
                   ENDPOINTGEOMETRY ENDPOINTS ENDRED ENSURETYPE ENTERINFIELD ENTERINGSTAGE EQUALTO EVALUATE
                   EVENTACTOR EVENTH EVENTTICK EVENTTIME EVENTV EXPANDGNODE EXPANDSELECTION EXPORTTYPES
                   EXPORTTYPESAVAILABLE EXTENDEDMOUSEDOWN EXTENT-H-RANGE EXTENT-V-RANGE EXTENTHRANGE EXTENTVRANGE
                   EXTERNALOBJECTS EXTERNALTYPE FILLBOUNDSRECT FILLCOLOR FILLREGION FILLREGIONOK FILTER FINALOBJECT
                   FINALSTATE FINDANDSELECT FINDCURRENTEVENTACTOR FINDDROPOBJECT FINDENDPOINT FINDEXPORTTRANSLATOR
                   FINDIMPORTTRANSLATOR FINDPORT FINISHNEWMASK FITTOTEXT FLAGS FLOATING FORCEREDRAW FOREBLUE
                   FOREGREEN FOREGROUNDRENDERER FORERED FRAMECOLOR FRAMEHEIGHT FRAMEMASK FRAMEOVAL FRAMERECT
                   FRAMEREGION FRAMEREGIONOK FRAMERELATIVE FRAMESIZE FRAMEWIDTH GENERATEITEMS GET-CONNECT-POINT
                   GETFROMCLIPBOARD GETPOPUPMENU GETRECTSHAPEFROMUSER GLOBALVARIABLES H HANCHOR HANDLEACTIVATE
                   HANDLEIDLE HANDLEKEY HANDLEMOUSEDOWN HANDLEMOUSEUP HANDLERDISPOSED HANDLERSTEPPED HANDLERVERSIONSAVED
                   HASCONTENTS HATCHTYPE HEIGHT HIDE HIGHLIGHT HIGHLIGHTAREA HIGHLIGHTCOLOR HITBYMOUSE HMAGNIFY
                   HMOUSE HOFFSET HORIGIN HORIZONTALSCROLL HPIVOT HSCALE HSCROLLER HSIZE HSPACE ICONRSRCTOCICNTRANSLATOR
                   ICONSIZE IDENTIFIERHELP IDLE IMAGERENDERERTOCICNTRANSLATOR IMAGERENDERERTOPATTRANSLATOR
                   IMAGERENDERERTOPICTTRANSLATOR IMAGERENDERERTOPPATTRANSLATOR IMPORTFROMCLIPBOARD
                   IMPORTFROMFILE IMPORTFROMRESOURCE IMPORTTRANSLATORSAPPLICABLE INCOMINGDATA INCREMENTOWNSREGIONCOUNT
                   INCURRENTANDREQUIREDPROJECTS INDICATESCRIPTSYNTAXERROR INDIRECTTRANSLATOR INITIALDEPTH
                   INITIALIZE INITIALSTATE INK INPUTHANDLER INPUTHANDLERID INSERTAFTERCURRENTELEMENT INSERTAFTERCURRENTITEM
                   INSERTBEFORECURRENTELEMENT INSERTBEFORECURRENTITEM INSERTINTO INSK8 INSTALL INSTALLED
                   INSTALLEDIN INTERNALOBJECT INVERTS ISOLATE ITEMBOUNDSRECT ITEMCONTENTS ITEMS ITEMVISIBLE
                   JUSTIFICATION KEYCOLOR KEYDOWN KEYTARGET KEYUP KIDS LASTCURSOR LASTLOC LASTSELECTED LAYER
                   LEAFIFY LEAVINGSTAGE LEAVINGVERSIONDISPLAYED LEFT LEFTMARGIN LEFTRENDERER LENGTHOFARROW
                   LIGHTFORCEREDRAW LINEINFO LINEPOINTS LINES LINESIZE LINESPACING LINESPACING* LINETO LINETYPE
                   LIVE LOADMEDIA LOCALVARIABLES LOCALVIRTUALPROPERTIES LOCATION LOCATIONVALID LOCK LOCKED
                   LOCKEDSCROLLER LOCKEDTEXT LOCKLEVEL LOCKTEXT LOCKTEXTLEVEL LOGICALBOUNDSRECT LOGICALTOPHYSICAL
                   LOGICALTOPHYSICALLIST LOGICALTOPHYSICALRECT LOGICALXSCALE LOGICALYSCALE LOWLEVELIDLE MACHANDLE
                   MACMENU MACRESOURCETYPESAVAILABLE MACSK8IMPORTABLERESOURCETYPESAVAILABLE MAGNIFICATION
                   MAINMONITOR MAINMONITORCENTER MAKEBOUNDSREGION MAKEFILLREGION MAKEFRAMEREGION MAPCOLLECTION
                   MAPCOLLECTIONINREVERSE MAPITEMS MAPSTATE MAPSTATEINREVERSE MAPSTATES MAPSTATESFORMODS
                   MAPVALUE MASKBOTTOM MASKBOUNDSRECT MASKCOPY MASKDIFFERENCE MASKEMPTY MASKEQUAL MASKINSET
                   MASKINTERSECT MASKLEFT MASKRIGHT MASKTOP MAXIMUMTHUMBSIZE MAXIMUMVALUE MEDIADATA MEDIATRANSLATOR
                   MENUENTER MENUFILLCOLOR MENUITEMS MENUITEMS\ FOR\ MODS MENUS MENUS\ FOR\ MODS MENUSELECT MENUSIBLINGS
                   MENUSIZE MENUTEXTCOLOR MENUTEXTSIZE MENUTYPE MIDDLEELEMENT MIDDLESTATE MINIMUMSIZE MINIMUMTHUMBSIZE
                   MINIMUMVALUE MODAL MODALDIALOG MODE MOUSEDOWN MOUSEDOWNINBREAKPOINT MOUSEDOWNINERRORMARKER
                   MOUSEENTER MOUSELEAVE MOUSELOC MOUSESENSITIVITY MOUSESTATUS MOUSEUP MOUSEWITHIN MOVED
                   MYCONNECTOR MYTREEVIEWER NAMEALREADYINUSE NAMEDONLY NEW NEWCONTAINEROK NEWCONTENTOK NEWX
                   NEWY NEXTFONTCHANGE NEXTSTATE NTHITEM NTHPOINT NTHPREVIOUSSTATE NTHSTATE NUMELEMENTS NUMITEMS OBJECT
                   OBJECTS OBJECTSINCLIPBOARD OBJECTSONHOLD OFFSET OFFSETBY OKTOMODIFYTEXT ONSTAGE OPBLUE
                   OPENITEM OPGREEN OPRED ORIENTATION ORIGIN ORIGINALOBJECTSTATES ORIGINHPIVOT ORIGINPOINTSLIST
                   ORIGINVPIVOT OSPOINTER OSWINDOW OTHERACTORS OVERLAPS OVERVIEWER OWNEDREGION OWNSREGION
                   PAGESTEP PAINTMASK PAINTOVAL PAINTRECT PARTHIT PARTNERHSCROLLER PARTNERSCROLLER PARTNERVSCROLLER
                   PASTECLIPBOARDTOSELECTION PATTERN PENMODE PENSIZE PHYSICALBOUNDSRECT PHYSICALTOLOGICAL
                   PHYSICALTOLOGICALLIST PHYSICALTOLOGICALRECT PICKERPROTOTYPE PICTFILEMEDIATOPICTFILETRANSLATOR
                   PIVOT PIXELVALUE PIXMAP POINTONWHICHACTOR POINTONWHICHPART POINTS POINTSLIST POSITIONOFITEM
                   PREPAREFORNEWCONTAINER PREPAREFORNEWCONTENT PREPAREFORNEWHANDLER PREPAREFORNEWHANDLERVERSION
                   PREPAREFORRUNNINGMODE PRESERVE PREVCONTAINER PREVIOUSFONTCHANGE PREVIOUSSTATE PREVLOC PROJECT PROPS QDPICTURETOPICTTRANSLATOR
                   REALARROWS REALOBJ RECOMPUTEPOINTS RECT RECTTOMASK RECYCLED RELATION RELATIONVIEWER REMOVECONNECTOR
                   REMOVECURRENTELEMENT REMOVECURRENTITEM REMOVINGMEASPARENT RENDER RENDERAMEDIAERROR RENDERANERROR
                   RENDERERLIST RENDERSTRETCHED RENDERSTYLE RENDERTILED RENDERUNSTRETCHED RESCALED RESCALETHUMB
                   RESETCOORDINATES RESETPEN RESIZABLE RESIZE RESIZED RESIZER RESIZESCONTENTS RESIZETOTEXT
                   RESOURCEID RESTORE RESUME RETURNINFIELD RETURNVALUE REVERSECONNECTION REVERT-TO-NONTLA-REGIONS
                   RIGHT RIGHTRENDERER ROOT ROOTITEM ROOTVIEWER ROTATE ROUNDEDNESS RUNNING RUNNINGDEPTH RUNNINGLINE
                   RUNNINGMODE RUNNINGSTOPPED RUNTIMEERROR SAVEDRUNNINGINFO SAVEVERSIONDISPLAYED SCALE SCALECONTENTS
                   SCALEFACTOR SCRAPCOUNT SCRIPTINPUTCOMPLETED SCRIPTTYPE SCROLL SCROLLERBODY SCROLLSTEP SELECTEDITEM
                   SELECTEDITEMS SELECTEDNODE SELECTFROMMENU SELECTFROMMENUBAR SELECTION SELECTION* SELECTIONCOMPLETED
                   SELECTIONSTYLE SELECTIONVIEWER SENDFARTHER SENDTOBACK SETARROWSIZE SETBOUNDSRECT SETENDPOINT
                   SETENDPOINTS SETFRAMESIZE SETLOCATION SETNTHPOINT SETORIGIN SETREGULARPOLYGON SETROUNDEDNESS
                   SETSCALE SETSCROLLERVALS SETSELECTION SETSIZE SETSTARTPOINT SETUPTEXTCOLORS SHOW SHOWN
                   SHOWSELECTION SIZE SIZEOFLINES SLIDERBODY SLIDERTHUMB SOUNDRSRCTOSNDTRANSLATOR SOUNDTOSNDTRANSLATOR
                   SPACING SPLITACTORS SPOTS-TAKEN SPOTSTAKEN STAGERELATIVE STARTACTOR STARTARROW
                   STARTAT STARTBLUE STARTGEOMETRY STARTGREEN STARTNEWMASK STARTOPBLUE STARTOPGREEN STARTOPRED
                   STARTPOINT STARTPOINTGEOMETRY STARTRED STATE STATEEQUAL STATEGREATEROREQUAL STATEGREATERTHAN
                   STATELESSOREQUAL STATEN STATENFROMEND STATEOFITEM STATEPROPERTY STOP STRING STRINGS STRINGSIZE
                   STRINGTOTEXTTRANSLATOR STYLES SUSPEND SWATCH TABINFIELD TABLENGTH TABTONEXTACTOR TARGETPROJECT
                   TEXTCOLOR TEXTCOLORS TEXTFONT TEXTHOFFSET TEXTLOCATION TEXTMODIFIED TEXTOFFSET TEXTSIZE
                   TEXTSTYLE TEXTTOTEXTTRANSLATOR TEXTVOFFSET THEARROWS THEDIALOG THEICONS THEOFFSET THEOFFSETS
                   THETREE THICKNESS THUMB THUMBPOSITIONTOCURRENTVALUE THUMBVIEW TICK TITLE TITLEBAR TOGGLESTATE
                   TOP TOPRENDERER TRANSFER-BITMAP TRANSLATOR TRANSLATORSAPPLICABLE TRANSLUCENTCOLOR TRANSLUCENTCONTENTS
                   TREEBROWSE TREEROOT TREEVIEWER TYPESINCLIPBOARD UNLOADMEDIA UNLOCK UNLOCKTEXT UPARROW
                   UPARROWINFIELD UPDATE UPDATE-FIELD-RECT UPDATEPARTNERSCROLLER UPDATESCROLLERS UPDATEVSCROLLER
                   V VALID VALUE VANCHOR VERSIONDISPLAYED VERTICALSCROLL VISIBLE VISIBLELINES VMAGNIFY VMOUSE
                   VOFFSET VORIGIN VPIVOT VSCALE VSCROLLER VSIZE VSPACE WANTSIDLE WANTSMOUSEWITHIN WIDTH
                   WIDTHOFARROW WINDOWSONLY WINDOWSTYLE WINDOWTITLE WITH\ CLIPPEDMASK WITH\ LOCKEDCURSOR
                   WITH\ PEN WITHACTORLOCKED WITHACTORLOCKEDPOSSIBLYFALSE WORDUNDERMOUSE WRAPPING XORIGIN
                   XSCALE YEDGE YORIGIN YSCALE ZOOM)

                  ("Function Library"
                   ACTORTOPRINTER
                   REALPART IMAGPART ABS ACOS ROUNDBOXDIMENSIONS ABSOLUTETIMETODATESTRING ACOSH AGEOFMOON
                   ALPHABETIC ALPHANUMERIC APPLEEVENTERROR ARITHMETICOVERFLOWERROR ARRAY ASH ASIN ASINH ASTYPE
                   ATAN ATANH BOUND CANTCHANGECONSTANTERROR CEILING CHARACTER COERCIONERROR COLLECTIONAS
                   COMPILATIONERROR CONSTANT COS COSH DATE-COMPONENT-VALUES DATESTRING DATESTRINGTOABSOLUTETIME
                   DAY DAYNAME DAYOFWEEK DAYOFYEAR DAYSBETWEEN DAYSINMONTH DIFFERENCE DISPOSEDOBJECTERROR
                   DIVISIONBYZEROERROR EON EQUALTO ERA EVEN EVENTMODEERROR EXP EXPT FCEILING FFLOOR FILENOTFOUNDERROR
                   FINDTHING FLOOR FROUND FTRUNCATE FUNCTIONAL GCD GREATERTHAN HOUR INCORRECTARGUMENTSERROR
                   INCORRECTSUBSCRIPTSERROR INCREMENTBYDAYS INDEXOUTOFBOUNDSERROR INITIALIZE INTERSECTIONOF
                   INTTOTIMEOFDAY LCD LIST LOG LOWERCASE LSH LUNARPHASE MACCHOOSEDIRECTORYDIALOG MACCHOOSEFILEDEFAULTDIRECTORY
                   MACCHOOSEFILEDIALOG MACCHOOSENEWFILEDIALOG MACCOPYRESOURCES MACGETANSWERFROMUSER MACMESSAGETOUSER
                   MACSELECTFROMCOLLECTIONDIALOG MACYESORNODIALOG MAX MAXIMUM MAYBEWRITEOBJECTNAME MAYBEWRITEPROJECTQUALIFICATION
                   MIN MINIMUM MINUTE MONTH MONTHNAME MONTHSBETWEEN NEGATIVE NOW NULL NUMBER NUMBERAS
                   OBJECT OBJECTAS OBJECTASLIST OBJECTASNUMBER OBJECTASSTRING OBJECTSTRING ODD PHASE PM POSITIVE
                   PRESERVE PROJECT RANDOM REMOVEDUPLICATES REST ROUND SEARCHTHING SECONDS SECONDSBETWEEN
                   SECONDSSINCE1904 INDIRECTFUNCTION INDIRECTARGUMENT SIGNUM SIMPLEOBJECTSTRING SIN SINH
                   SORT SQRT STRING STRINGAS SYMBOL TANH TICKS TIMESTRING TRUNCATE UNBOUNDVARIABLEERROR UNDEFINEDHANDLERERROR
                   UNIONOF UNTRUE UPDATECOMPONENTS UPPERCASE VECTOR WEEKOFYEAR WITH\ CURSOR WITH\ DEFERREDACTION
                   WITH\ EVENTSDISABLED WITH\ LOCKEDACTOR WITH\ LOCKEDCURSOR WITH\ MACRESOURCEFILE
                   WITH\ PROJECT WITH\ VISUALEFFECT WRITEOBJECT WRITEOBJECTRECURSIONLIMIT WRITESOURCES WRITEUNINTERESTINGOBJECT
                   YEAR RAISEUNSETTABLEPROPERTYERROR RAISEINSUFFICIENTINITIALIZERSERROR SYSTEMTICKCOUNT)

                  ("All Functions"
                   & * + - <> abs acos acosh activemode activemodeprocess actorathvcoordinates
                   actorsbounds actualbasetext actualbasetextandrange addeventinterest addhandlerdialog
                   addparentdialog addportdialog addpropertydialog align alignmentofboundstobounds alignsizetobounds alphabetic
                   alphanumeric analyzeactorsforselection as ascii ash asin asinh atan atanh beep bound boundsregionok
                   bringuphandlerwithruntimeproblem browserhighlight browserunhighlight buildstandalonedialog cando canlogit
                   capskeydown ceiling Character characterpositionoferror clearallbreakpoints clearallreferences
                   clearbreakpoint clearprojectinterests clearsystemstateforprojectload cliptomask commandkeydown 
                   compilescriptfile compilescripthandler compilescripts computemaybetruncatedtext constant
                   constrainboundstoaspectratio constrainsizetoaspectratio contains containsactivebreakpoints
                   controlkeydown copyrealproperties copyresourcetoproject copytextproperties cos cosh createnewprojectforload
                   createnewvariablefromstore currentcliptomask currenteventkey currenteventmodes currenteventrecord
                   currentfloatingwindow currentwindow datestringtoabsolutetime debugabort debuggo debugstep deletemoviefile
                   descriptionoferror dispatchclick dispatchtointerestedobjects disposedialog distribute div dollarstring
                   dragactors dragonstage dragrubberband drawactorcontents drawxorframe drawxorline drawxorrectangle edithandler
                   edithandlerdialog edithandlerobject edithandlerobjectdialog endswith evaluateexpressioninlocalcontext
                   evaluatescriptcommand evaluatescriptforms evaluatescripttranslation even eventsdelegated eventwindow
                   examinablehandlers exitmodalstate exp expt fillregionok findcurrenteventactor finddropobject 
                   findexporttranslator findfileinproject findhandlereditor findimporttranslator findobject findselectedactors
                   findselectedactorsgrow findthing finishnewmask fittobounds floor forceexitcurrentmode forcegarbagecollection 
                   frameregionok functional gcd generatefaslforproject getanswerfromuser getconstantnamecompletions
                   getfilefromuserwithpreview getfromuserdialog getfunctionnamecompletions getglobalnamecompletions 
                   gethandlernamecompletions getholderoftype getkeys getobjectnamecompletions getpropertynamecompletions 
                   getpropertyvalue getrecordfield getrectshapefromuser getscrap getvalue handlerargumentsstring 
                   handleridfromscript handleridtohandlerobject icl8tocicn imagpart importtranslatorsapplicable 
                   initializerargument insertatend insertinfront invertmask IS\ A itsaclick layoutdialog
                   lineoferror List loadandevalscriptfile loadfilephysicalname loadscriptfaslfile loadscriptfaslfiles
                   loadscriptfile loadscripts log logobjectstring lowercase macchoosedirectorydialog
                   macchoosefiledefaultdirectory macchoosefiledialog macchoosenewfiledialog maccopyresources 
                   macgetanswerfromuser macmessagetouser macselectfromcollectiondialog macyesornodialog mainmonitorcenter 
                   makeeventinterestshashtable makeinstancefromstore mapallobjects maskbottom maskboundsrect maskcopy 
                   maskdifference maskempty maskequal maskinset maskintersect maskleft maskright masktop maskunion max 
                   messagetouser min modaldialog mountedvolumes namealreadyinuse negative newfiledialog 
                   newindirecttext newprojectdialog objectfrom objectfromobjectid objectidfromobject 
                   objectnamedialog objectsinterestedinevent objectstring odd oksk8character openfiledialog 
                   openprojectdialog openprojectfile optionkeydown Pair phase popupballoon positive
                   previouseventmode processunusedinitializerarguments propagatevalue putscrap quicktimeversion 
                   quit raiseinsufficientinitializerserror raiseunsettablepropertyerror random realpart
                   recordsoundtoclipboard recttomask registerexpressionforruntimeuse registerfordisposalonquit 
                   registerforlowlevelidle removeconstantdialog removeduplicates removeeventinterest removehandlerdialog
                   removeparentdialog removepropertydialog removevariabledialog renderamediaerror renderanerror
                   requirequicktimeinitialized rest round roundboxdimensions SAME\ OBJECT searchscripts
                   searchthing selecteditemsboundsrect selectfromcollectiondialog sendtolog setbreakpoint
                   setpropertyvalue setrecordfield setupparsingprojectvariables setvalue shiftkeydown showmediainactor 
                   sign simpleobjectstring sin sinh sort splicenewparent sqrt sqrt startnewmask startswith stringequal
                   systemtickcount tagdialog Tan tanh tickeventclock tile translatescriptcommand translatescriptcommandorexpr
                   translatescriptexpression translatescriptfile truncate t_addresource t_deactivategcosptr
                   t_detachresource t_filerefnumtofilerefnumgchandle t_flattenmovie t_flattenmoviedatagc t_gestalt
                   t_get1resource t_get1resourcegc t_getccursorgc t_getcicongc t_getgworld t_getmovienextinterestingtime
                   t_getpixpatgc t_getresource t_gettracknextinterestingtime t_handletogchandle t_lockpixels
                   t_makegcosptr t_newgworldgc t_newmoviefromdataforkgc t_newmoviefromfilegc t_newmoviefromhandlegc 
                   t_newmoviefromscrapgc t_newmoviegc t_newpixpatgc t_newrgn t_newrgngc t_ptrtogcptr t_removeresource 
                   t_setmediaplayhints t_setmovieplayhints t_unique1id t_writeresource undoableset undolastset
                   unregisterforlowlevelidle untrue uppercase warnifinsuperproject WITH\ HIGHLIGHTCOLOR WITH\ LOCKEDACTOR
                   WITH\ LOCKEDSCROLLER WITH\ PROJECT WITH\ TARGETOBJECT yesornodialog zeroscrap
                   zoomboundsrect zoomrect ^)

                  ("macframes"
                   ZERO TIMEBASEOSPTR INSTANCEOSPTR MEDIAOSPTR MASTERCLOCK MASTERTIMEBASE EFFECTIVERATE STARTTIME
                   STOPTIME CALLBACKEVENT PARAMETERS ACTIVE AWAITINGACTIVATION SWAPFILE SUPPRESSINGSTEPBUTTONS
                   SUPPRESSINGSPEAKERBUTTON USINGWINDOWPALETTE DONTSAVE FILLCOLORACTOR FRAMECOLORACTOR TEXTCOLORACTOR
                   SETFILLCOLORACTOR SETFRAMECOLORACTOR SETTEXTCOLORACTOR DYNAMICRENDERERTOUSE DEFAULTBACKGROUNDCOLOR
                   FORCEGARBAGECOLLECTION *UNDEFINED* ACQUIRETAG ACTIVATE ACTIVATE-INPUT-PORT-PREAMBLE ACTIVATEDISABLE
                   ACTIVATEINPUTPORT ACTIVATEOUTPUTPORT ACTIVE ACTIVEMODE ACTIVESEGMENT ACTOROWNER ACTOROWNER
                   ACTORPARENT ADD-TRACK ADDEDMEASPARENT ADDEVENT ADDINPUTOUTPUTPORT ADDINPUTPORT ADDMOVIESELECTION
                   ADDOUTPUTPORT ADDPARENT ADDPROPERTY ADDSAMPLE ADDSAMPLEREFERENCE AEDESC ALIGNBOUNDSTOMOVIE
                   ALIGNMOVIETOBOUNDS ALIGNSIZETOMOVIE ALLTRACKALTERNATES ANCESTORS APPLEICONTWO APPLICATIONNAME
                   ARRAY ATSTREAMEND ATTACHED ATTACHPORT AUTOTRACKALTERNATESENABLED AUTOWIRE BACKGROUNDCOLOR
                   BACKWARDS BASEPARENT BEGINMEDIAEDITS BESTCOLORDEPTH BOUNDSRECT CAPSKEYDOWN CHANGED? CHANGEPARENTS
                   CHANNEL CHECKSK8VERSION CHECKTIMEVALUE CHICAGOFONT CLEAR CLEARMOVIESELECTION CLOSEMOVIE
                   CLOSEPROJECT COLLECTIONLIKE COLOR COLORDEPTH COMMANDKEYDOWN COMPACTPROJECTCODE COMPILESCRIPTFILE
                   COMPILESCRIPTS CONSTANTS CONTROLKEYDOWN COPYDOWNMOVIEPARENTSLOTS
                   COPYMOVIESELECTION COPYPROJECT COPYREALPROPERTIES COPYSELECTION COPYSETTINGS COULDNOTRESOLVEDATAREFERENCE
                   COURIERFONT COVER CREATE CREATE CREATEFILE CREATEMOVIEFILE CREATIONDATE CREATIONRELATIONS
                   CREATIONTIME CREATOR CURRENTCOMMANDKEY CURRENTCYCLE CURRENTDIRECTORY CURRENTEVENTKEY CURRENTEVENTMODES
                   CURRENTEVENTRECORD CURRENTTICK CURRENTTIME CUTMOVIESELECTION CUTSELECTION DATA DATAFILE
                   DATAREFERENCE DATAREFERENCETYPE DATAREFERENCEWASCHANGED DATASIZE DEACTIVATE DEFAULTSFROM
                   DEFINE-HANDLER DEFINE-SK8-CONSTANT DEFINE-SK8-FUNCTION DEFINE-SK8-MACRO DEFINE-SK8-VAR
                   DEFINE-SYSTEM-HANDLER DELETECURRENTFILE DELETEMOVIEFILE DELETESEGMENT DETACHED
                   DETACHPORT DEVICE DIRECTION DIRECTORIES DIRECTORYNAMES DISABLE DISABLED DISPLAYING
                   DISPOSE DISPOSEMOVIECONTENTS DONE DONTASKUNRESOLVEDDATAREFERENCES DONTAUTOALTERNATES DONTCREATEMOVIE
                   DONTOPENFILE DONTRESOLVEDATAREFERENCES DOWN DRIVE DURATION DYNAMIC EJECTED ELEMENTTYPE
                   ENABLE ENABLED ENABLED ENABLEDVISUALTRACKS ENDMEDIAEDITS ENDTIME ENTERMODALSTATE ENTERMODE
                   ESPYSANSBOLDFONT ESPYSANSFONT ESPYSERIFBOLDFONT ESPYSERIFFONT EVENTCLASS EVENTID EVENTLISTENERS
                   EVENTS EVENTTICK EXISTED EXITMODALSTATE EXITMODE EXTRACTPARAMETER EXTRACTREPLYPARAMETER
                   FEEDBACKACTION FILE FILEDEVICE FILEDIRECTORY FILEEXISTS FILENAME FILENAMES FILEOFFSET
                   FILES FILESPECGCHANDLE FILETYPE FINALIZER FINDFILEOBJECTNAMED FINDNEXTEMPTYMEDIATIME FINDOBJECT
                   FINDPARENT FIXEDTONUMBER FLAGS FLATTEN FLUSH FONT FONTDATA FONTNAME FONTS FORCEEXITACTIVEMODE
                   FORCEEXITCURRENTMODE FORWARDS FRACTTONUMBER FRAMEPOSITION FRAMES FUNCTIONS GENEVAFONT
                   GETCONSTANTNAMECOMPLETIONS GETFUNCTIONNAMECOMPLETIONS GETGLOBALNAMECOMPLETIONS GETHANDLERNAMECOMPLETIONS
                   GETINITIALIZEVALUE GETKEYS GETMEDIASAMPLE GETMEDIASAMPLEREFERENCE GETMOVIETRACKFROMID
                   GETMOVIETRACKFROMINDEX GETOBJECTNAMECOMPLETIONS GETPROPERTYNAMECOMPLETIONS GETPROPERTYVALUE
                   GETVALUE GLOBALS GOTOBEGINNING GOTOEND GRAPHICSMODE GWORLD GWORLD H HANDLE HANDLEACTIVATE
                   HANDLEAPPLEEVENT HANDLEAUTOKEY HANDLEIDLE HANDLEKEYDOWN HANDLEKEYUP HANDLEMOUSEDOWN HANDLEMOUSEUP
                   HANDLEOTHER HANDLERS HANDLEUPDATE HELVETICAFONT ID ID IFDOESNOTEXIST IFEXISTS IMPLEMENTORS
                   IMPORTFROMDATAFORK INCREMENT INDEX INHERITEDHANDLERS INHERITEDPROPERTIES INHERITEDPROPERTY
                   INHERITEDREALPROPERTIES INHERITEDVIRTUALPROPERTIES INHERITSFROM INITIALIZE INITIALIZE-SEQUENCE
                   INITIALIZEFROMSTORE INITIALIZER INITIALSTATEFORNEWMOVIEPARENT INITIALSTATEFORNEWMOVIEPARENT
                   INITIALSTATEFORNEWMOVIEPARENT INPUTOUTPUTPORTS INPUTPORTS INSERTEMPTYSEGMENT INSERTFRAME
                   INSERTMEDIA INSERTPARAMETER INSERTREPLYPARAMETER INSERTSEGMENT INSTALLMOVIESUBACTORS INSTALLTRACKACTOR
                   INVALIDATEMOVIEPICT IS-A ISDIRECTORY ISROOTDIRECTORY ISVISUAL KEYBOARDS KEYSDOWN KNOWNCHILDREN
                   KNOWNDESCENDANTS LINKMOVIETOFILE LIST LOADFILEPHYSICALNAME LOADINTORAM LOADMOVIEINTORAM
                   LOADSCRIPTFASLFILE LOADSCRIPTFASLFILES LOADSCRIPTFILE LOADSCRIPTS LOCALCREATIONRELATIONS
                   LOCALHANDLERS LOCALPROPERTIES LOCALPROPERTY LOCALREALPROPERTIES LOCALVIRTUALPROPERTIES
                   LOCATION LOGICALNAME LOOPS MACCOUNTRESOURCESOFTYPE MACFILECREATOR MACFILETYPE MACGETRESOURCEFROMTYPEANDINDEX
                   MACGETRESOURCEHANDLEFROMID MACGETRESOURCEHANDLEFROMIDFORDRAWING MACGETRESOURCEHANDLEFROMNAME
                   MACGETRESOURCEHANDLEIDS MACGETRESOURCEHANDLEINFO MACGETRESOURCEHANDLENAMES MACGETRESOURCEHANDLES
                   MACHANDLE MACHASRESOURCES MACRESOURCEFILEOPEN MACRESOURCETYPESAVAILABLE MACSK8IMPORTABLERESOURCETYPESAVAILABLE
                   MACTOTALSK8IMPORTABLERESOURCES MACUPDATERESOURCEFILE MAINMONITOR MAINMONITORCENTER MAINTAINASPECTRATIO
                   ALIGNMENT ALIGNMOVIEFROMBOUNDS MAKEFILLREGION MAKENEWMOVIETRACK MAKEOBJECTAPROXY MAKEPROPERTYNOTPROPAGATE
                   MAKEPROPERTYPROPAGATE MAKEPROXYFOR MAPALLOBJECTS MAPANCESTORS MAPKNOWNDESCENDANTS MAPPROJECTOBJECTS
                   MASTER MASTEROFFSET MASTERTICKS MASTERTICKSPERTICK MATRIX MAXCOLORDEPTH ME MEDIA MEDIA
                   MEDIADATAREF MEDIADATAREFCOUNT MEDIAHANDLER MEDIAHANDLERDESCRIPTION MEDIALANGUAGE MEDIANEXTINTERESTINGTIME
                   MEDIAQUALITY MEDIATYPE MENUBARS MENUITEMS MENUS MODEMS MODIFICATIONDATE MODIFICATIONTIME
                   MONACOFONT MONITORS MOUNTEDVOLUMES MOVE MOVIE MOVIE MOVIEACTIVE? MOVIEACTIVESEGMENT MOVIEBOUNDSRGN
                   MOVIEBOX MOVIEBOX MOVIEBOX MOVIECLIPREGION MOVIEDISPLAYBOUNDSRGN MOVIEDISPLAYCLIPREGION
                   MOVIEFRAMERENDERER MOVIEFRAMERENDERER MOVIEFRAMERENDERERMEDIA MOVIEFRAMERENDERERMEDIA
                   MOVIEFY MOVIEGCOSPTR MOVIEGCOSPTR MOVIEGWORLD MOVIELANGUAGE MOVIEMATRIX MOVIENEXTINTERESTINGTIME
                   MOVIEPARENT MOVIEPICT MOVIEPICTGCHANDLE MOVIEPICTTIMEVALUE MOVIEPICTURE MOVIEPICTURE MOVIEPICTURE
                   MOVIEPOSTERPICT MOVIESEGMENTDISPLAYBOUNDSRGN MOVIESELECTION MOVIEVOLUME NAME NEW NEWEDITSTATE
                   NEWMOVIEFROMFILE NEWSTATEWHENDONE NEWSTATEWHENDONEVALUES NEWSTATEWHENDONEVALUES NEWSTATEWHENDONEVALUES
                   NEWYORKFONT NEXTBYTE NEXTCHARACTER NEXTINTERESTINGTIME NEXTLINE NEXTWORD NUMBER NUMBEROFCYCLES
                   NUMBEROFOBJECTS NUMBEROFTRACKS NUMBERTOFIXED NUMBERTOFRACT NUMBERTOSHORTFIXED OBJECT OBJECTFROMOBJECTID
                   OBJECTIDFROMOBJECT OBJECTNAME OBJECTS OBJECTSREGISTEREDFORLOWLEVELIDLE OKAY-TO-ACTIVATE-PORT
                   ONSTAGE OPENED OPENMOVIE OPENPROJECT OPENPROJECTFILE OPERATION OPTIONKEYDOWN OPTIONS 
                   ORIGINALANCESTOR ORIGINALOBJECT
                   OSAETARGET OSPATHNAME OTHERPARENTS OUTPUTPORTS OWNEDREGION PALATINOFONT PARENTS PASTEMOVIESELECTION
                   PASTESELECTION PAUSE PAUSEWITHHIGHQUALITY PERSISTENTINDEX PHYSICALNAME PLAY PLAYER PLAYNEWMOVIE
                   PLAYWITHNOOTHERACTIVITY POINTERSTATE POINTINMOVIE? PORTFILTER PORTOBJECT PORTPROPERTY
                   PORTS PORTS* PORTSCOMPATIBLE PORTTYPE POSTER POSTER POSTER POSTERBOX POSTERBOX POSTERBOX
                   POSTERPICTGCHANDLE POSTERPICTGCHANDLE POSTERPICTGCHANDLE POSTERPICTURE POSTERPICTURE POSTERPICTURE
                   POSTERTIME POSTERTIME POSTERTIME PREFERENCES PREFERREDRATE PREFERREDSIZE PREFERREDVOLUME PRELOADMOVIE
                   PREROLL PRESERVE PREVIEWMODE PREVIEWSEGMENT PREVIEWSEGMENT PREVIEWSEGMENT PREVIOUSEVENTMODE
                   PREVIOUSREALTIME PREVIOUSSTATE PRINTERS PRIVATE PRIVATEOBJECT PROCESSOR PROCESSERIALNUMBER PROGRESSPROC
                   PROJECT PROJECTHANDLERS PROPAGATABLEVALUE PROPAGATEFROM PROPAGATEVALUE PROPERTIES PROPERTIESWITHVALUE
                   PROPERTY PROTOTYPE PUBLISHSYMBOL PUTFILEPREVIEW PUTMOVIEONSCRAP PUTONSCRAP QUICKTIMEMEDIA
                   QUICKTIMETRACK QUIT RATE READBYTE READCHARACTER READLINE READONLYPROPERTY READSTREAMITEM
                   READWORD REALLYENABLED REALPROPERTIES REALPROPERTY RECONCILED RECONCILED RECONCILETRACKCOLLECTIONWITHMOVIETRACKS
                   RECONCILETRACKCOLLECTIONWITHMOVIETRACKS RECORDDESCRIPTOR REFERENCES REGISTERASTRAP REGISTERFORLOWLEVELIDLE
                   REMOVE-TRACK REMOVECONSTANT REMOVEFRAME REMOVEFUNCTION REMOVEHANDLER REMOVEPARENT REMOVEPORTS
                   REMOVEPROPERTY REMOVEVARIABLE REMOVINGMEASPARENT RENDER REPEATING REPLACEPARENT REPLY
                   REQUIREDPROJECT REQUIREDPROJECTS REQUIREMOVIESINITIALIZED REQUIREQUICKTIMEINITIALIZED
                   REQUIRINGPROJECTS RESET RESFILEREFNUM RESFILEREFNUMGCHANDLE RESIZE RESIZEACTORFROMMOVIE
                   RESIZEFILLFROMMOVIE RESIZEFRAMEFROMMOVIE RESIZEMOVIEFROMBOUNDS RESIZEMOVIEFROMFILL RESIZEMOVIEFROMFRAME
                   RESIZEMOVIEFROMRENDEREDREGION RESIZERENDEREDREGIONFROMMOVIE RESIZINGSTYLE RESIZINGSTYLEVALUES
                   RESIZINGSTYLEVALUES RESOURCEFILE RESOURCEID RESOURCENAME RESTORE RESTYPE RESUME RUNNING
                   RUNTIMEINDEX SAMPLEDESCRIPTION SAMPLEDESCRIPTIONCOUNT SAMPLENUMBERTOTIME
                   SAVEPROJECT SAVEPROJECTAS SCALESEGMENT SCRIPTTAG SELECTION SELECTMOVIEALTERNATES SEND
                   SEQUENCE SERVICING SETFRAMESIZE SETGRAPHICSMODE SETMASTERTIMEBASE SETMEDIADATAREF SETMOVIEACTIVESEGMENT
                   SETMOVIEBOX SETMOVIEFILLCOLOR SETMOVIEGWORLD SETMOVIEPLAYHINTS SETMOVIEPOSTERFILLCOLOR
                   SETMOVIESELECTION SETPROPERTYVALUE SETTRACKDIMENSIONS SETVALUE SHIFTKEYDOWN SHORTFIXEDTONUMBER
                   SHOWPOSTER SIGNATURE SIMPLEOBJECTSTRING SIZE SK8 SKIPINITIALIZATION SLAVES SOUNDBALANCE SPECIALIZED START
                   STARTED STARTTIME STATE STATEVALUES STEPBY STOP STOPPED STOPPEDCOLOR STORAGEDEVICES
                   STR STREAMPOSITION STREAMREADERINFO STREAMWRITERINFO STRING SUPPRESSINGVISUALTRACKS SUSPEND
                   SYMBOL SYMBOLFONT SYSTEMEVENT SYSTEMLOG TAGPART TAGS TEXTSTYLES TICK TICKEVENTCLOCK
                   TICKING TICKSPERSECOND TIMEBASE TIMECHANGED TIMEINFO TIMEPERTICK TIMESCALE TIMESFONT TIMETOSAMPLENUMBER
                   TIMEVALUE TOTALTICKS TRACK TRACKALTERNATE TRACKBOUNDSREGION TRACKCLIPREGION TRACKDIMENSIONS
                   TRACKDISPLAYBOUNDSREGION TRACKENABLED? TRACKFROMID TRACKFROMID TRACKID TRACKLAYER TRACKMATRIX
                   TRACKMATTE TRACKMOVIEBOUNDSRGN TRACKNEXTINTERESTINGTIME TRACKOFFSET TRACKOSPTR TRACKOSPTR
                   TRACKPICT TRACKS TRACKSEGMENTDISPLAYBOUNDSREGION TRACKTIMETOMEDIATIME TRACKVOLUME TRAPARGUMENTS
                   TRIGGERBEFORE TTYFONT TYPE TYPESATISFIED UNCOVER UNDISPOSABLE UNLINKMOVIEFROMFILE UNMOUNT
                   UNMOVIEFY UNMOVIEFY UNMOVIEFY UNREGISTERFORLOWLEVELIDLE UNWIREPORT UNWIREPORTS UP UPDATE-DISPATCH-METHOD
                   USEEDITSTATE USERDATA V VALIDLOGICALNAME VALIDPHYSICALNAME VALUEPROPAGATEDFROM VALUETYPES
                   VARIABLES VECTOR VERSION VIRTUALPROPERTIES VISUAL VISUAL VOLUME VT100 VT320 WIREDTO
                   WIREPORTS WITHCURSOR WITHPROJECT WRITEBYTE WRITECHARACTER WRITELINE WRITEOBJECT WRITESTREAMITEM
                   WRITESTRING WRITEWORD [PORTOBJECT] [WIREDTO*])

                  ("SK8Script"
                   & * + - <> A ABORTBREAK ABORTERROR ABORTEVENT ACTIVATE ACTIVATETEXT ACTORTEXTSIZE
                   ACTUALBASETEXT ACTUALBASETEXTANDRANGE ACTUALSOURCE ACTUALSOURCEANDRANGE AFTER ALL AM AN
                   AND ANY ANYELEMENT ANYSTATE ANYTHING APPLEEVENTERROR APPLY ARE AREN ARENT ARGUMENTNAME
                   ARGUMENTS ARITHMETICOVERFLOWERROR ARRAY AS AS\ A ASCII AT AUTOKEY AVAILABLEVERSIONS BACK
                   BASECOLLECTION BASETEXT BEEP BEFORE BEGINNING BEHIND BESTSIZE BODY BUT BUTTONPANEL BY
                   BYREFERENCE BYVALUE CALL CALLIN CALLLOGGING CALLSPEC CANCELKEYACTION CANDO CANLOGIT CANTCHANGECONSTANTERROR
                   CHARACTER CHOOSEELTS CHOOSETYPEDELTS CHOOSETYPEDELTSOFELTS CLEANUP CLOSEPROJECT COERCIONERROR
                   COLLECTIONLIKE COLLECTIONPROPERTY COLLECTIONSTRUCTURESHARED COMPILATIONERROR CONSTANT CONSTANTNAME CONTAIN
                   CONTAINED CONTAINER CONTAINS CONTAINSACTIVEBREAKPOINT CONTAINSSUBCOLLECTION CONTENTS CONTENTS\ FOR\ MODS
                   COPYNEXTSTATE COPYSTATE CREATETEXTDISPLAYITEM CURRENTCHARACTER CURRENTCONDITION CURRENTELEMENT
                   CURRENTINVOKABLECONDITIONRESPONSES CURRENTITEM DATA DEACTIVATEALLBREAKPOINTS DEACTIVATETEXT
                   DEFAULTING DEPENDENTSTATES DESCENDANT DESCRIPTION DEV-MODE DIRTY DISK
                   DISMISSHANDLEREDITORS DISPOSEDOBJECTERROR DISPOSEMEM DIV DIVISIONBYZEROERROR DO DOES DOESN
                   DOESNT DOLLARSTRING DON DONT DOWNARROW DRAG DRAGGINGMOUSEWITHIN DROPPED EDITHANDLER EDITHANDLEROBJECT
                   EDITOR EIGHTH ELEMENTN ELEMENTNFROMEND ELEVENTH ELSE ELTSOFELTS EMPTY EMPTYROW EMPTYROWSELECTED
                   ENABLED END ENDS ENDS\ WITH ENDSWITH ENSUREHANDLERSSAVED ENTER ENTERINGSTAGE EQUAL EQUALS
                   EQUALTO ERRORCAUSE ERRORID ERRORPOSITION ERRORSYSTEMERROR ESCAPE EVALUATESCRIPTCOMMAND
                   EVALUATESCRIPTEXPRESSION EVALUATESCRIPTHANDLER EVALUATESCRIPTTRANSLATION EVENTMODEERROR
                   EVERY EVERYTHING EXECUTIONTRACING EXIT EXITBREAK EXPECTEDTYPE EXPRESSIONFIELD EXPRTITLELABEL
                   EXPT EXTENDEDMOUSEDOWN EXTRACTSUBCOLLECTION FAILTOBRINGUPHANDLER FALSE FIELDS FIFTH FILENOTFOUNDERROR
                   FILTER FILTERS FINALSTATE FINALSTATETYPED FINDDROPITEM FINDHANDLEREDITOR FIRST FOR FOREIGN
                   FOREVER FORWARDMAPPER FORWARDMAPPERFORMODS FORWARDSCANNER FOURTH FROM FROMSTATE FRONT
                   FULLYALIASEDCOLLECTION GET GETATTENTION GETFROMUSER GIVEN GLOBAL GLOBALVARIABLES GOBUTTON
                   GREATER GREATERTHAN HANDLERARGUMENT HANDLERARGUMENTSSTRING HANDLERDISPOSED HANDLERNAME
                   HANDLERS HANDLERSTEPPED HANDLERVERSIONSAVED HAS HORIZONTALSCROLL HSPLITTER HSPLITTERLOCATION
                   HSPLITTERNUB I IF IN INCLUDEHIDDENERRORCONTEXT INCORRECTARGUMENTSERROR INCORRECTSUBSCRIPTSERROR
                   INDEX INDEXEDRANGEOFELTS INDEXOUTOFBOUNDSERROR INHERITED INITIALIZE INITIALIZEMEM INITIALSTATE
                   INITIALSTATETYPED INOUT INPUT INPUTHANDLER INPUTHANDLERID INSERT INSERTAFTERCURRENTELEMENT
                   INSERTAFTERCURRENTITEM INSERTBEFORECURRENTELEMENT INSERTBEFORECURRENTITEM INSERTINTO INSERTROW
                   INTERACTIVEERRORS INTERNALERRORANDBREAK INTO INVOKABLE INVOKE IS IS\ A ISN ISNT ISNT-A
                   IT ITEM ITEMHANDLER ITEMS ITEMSLIST ITEMTYPE ITS ITSELF KEYDOWN LAST LEAVINGSTAGE LEAVINGVERSIONDISPLAYED
                   LEFTARROW LESS LESSTHAN LIST LOADFOREIGN LOCAL LOCALPROPERTIES\ FOR\ MODS LOCALVARIABLES
                   LOCALVARIABLESUSED LOGCALLS LOGOBJECTSTRING MAC68KMPWCCALLSPEC MAC68KPASCALCALLSPEC MAC68KTRAPCALLSPEC
                   MAINTAINTYPETABLES MAKE-SK8-CONDITION MAKESAVEABLE MAKEUNSAVEABLE MAPCHARACTERCHUNKS MAPCHARACTERCHUNKSFORMODS
                   MAPCHARACTERS MAPCOLLECTION MAPCOLLECTIONINREVERSE MAPITEMS MAPITEMSTYPED MAPLINECHUNKS
                   MAPLINECHUNKSFORMODS MAPPARAGRAPHCHUNKS MAPPARAGRAPHCHUNKSFORMODS MAPSTATE MAPSTATEINREVERSE
                   MAPSTATES MAPSTATESFORMODS MAPSTATESFORMODSTYPED MAPSTATESTYPED MAPWORDCHUNKS MAPWORDCHUNKSFORMODS
                   MAYBEPRINTOBJECTNAME MAYBEPRINTPROJECTQUALIFICATION ME MEMARRAY MEMDISOWN MEMOWN MEMRECORD
                   MENUSELECT MIDDLE MIDDLEELEMENT MIDDLESTATE MILLISECOND MILLISECONDS MINIMUMSIZE MINUTE
                   MINUTES MOUSEDOWN MOUSEENTER MOUSELEAVE MOUSEUP MOUSEWITHIN MOVED MY MYEDITORSPLITTER
                   MYFIELD MYGLOBALS MYHSCROLLER MYLOCALS MYRESIZER MYSCROLLER MYSELF MYTOGGLER MYVARSPLITTER
                   MYVSCROLLER NAME NAMED ND NEW NEWCONTAINEROK NEWINDIRECTTEXT NEWLINE NEWMEMHANDLE NEWMEMPOINTER
                   NEXT NEXTSTATE NEXTSTATETYPED NINTH NO NOT NTHITEM NTHITEMTYPED NTHPREVIOUSSTATE NTHPREVIOUSSTATETYPED
                   NTHSTATE NTHSTATETYPED NUMBER NUMELEMENTS NUMITEMS NUMITEMSTYPED OBJECT OBJECTAS OBJECTASLIST
                   OBJECTASNUMBER OBJECTASSTRING OBJECTS OBJECTSTRING OF ON ONE OPERANDS OPERATION OR ORIGINALCONDITION
                   OUT OVER OWNEROBJECT PARA PASS PATH PI POSITIONOFITEM POSTABORTHANDLER PREPAREFORNEWHANDLER
                   PREPAREFORNEWHANDLERVERSION PREPAREFORRUNNINGMODE PREVIOUSSTATE PRINTOBJECT PRINTREREADABLY
                   PRINTUNINTERESTINGOBJECT PRIVATE PROCESSELTS PROCESSINGEVENTS PROCESSOR PROCESSORS PROJECT
                   PROPERTIES PROPERTIES\ FOR\ MODS PROPERTYNAME PUBLIC RANGE RANGECOLLECTIONANDENDPOINTS
                   RANGEOFELTS RANK RD REGA0 REGA1 REGA2 REGA3 REGA4 REGA5 REGD0 REGD1 REGD2 REGD3 REGD4
                   REGD5 REGD6 REGD7 REMOVE REMOVECURRENTELEMENT REMOVECURRENTITEM REMOVEROW REPEAT RERAISE
                   RERAISE-SK8-CONDITION RESETLAYOUT RESIZED RESIZER RESPONSE RESULT RETURN
                   RETURNS REVERSEMAPCHARACTERCHUNKS REVERSEMAPLINECHUNKS REVERSEMAPPARAGRAPHCHUNKS REVERSEMAPPER
                   REVERSEMAPWORDCHUNKS REVERSESCANNER RIGHTARROW RUNNINGHANDLERINFO SAME SAME\ OBJECT SAVEERRORCONTEXTVARS
                   SAVEVERSIONDISPLAYED SCRIPTEDITORPROTOTYPE SCRIPTERRORDESCRIPTION SCRIPTERRORPOSITION
                   SCRIPTINCOMPLETEERROR SCRIPTINPUTCOMPLETED SCRIPTPOPUP SCRIPTTRANSLATIONERROR SECOND SECONDS
                   SELECTEDITEMS SELECTEDROW SELECTEDTEXT SELECTIONCOMPLETED SENDTOLOG SET SETTER SEVENTH
                   SIGN SIMPLEOBJECTSTRING SIXTH SK8-CONDITION SK8-ERROR SOME SOURCE SOURCEARGS SOURCESETTER
                   SPACE SQRT SQUAREROOT ST STACK START STARTS STARTS\ WITH STARTSWITH STATEEQUAL STATEGREATEROREQUAL
                   STATEGREATERTHAN STATELESSOREQUAL STATEN STATENFROMEND STATEOFITEM STEPBUTTON STOPLOGGINGCALLS
                   STRING STRINGS SYMBOL TAB TABTONEXTACTOR TARGETPROJECT TELL TENTH TEXT\ FOR\ MODS TEXTCOLOR
                   TEXTFONT TEXTSIZE TEXTSTYLE TH THAN THAT THE THEN THING THINGS THIRD THIS THROUGH THRU
                   TICK TICKS TIMES TITLE TO TOMEMHANDLE TOMEMPOINTER TOSTATE
                   TRUE TWELFTH TYPE TYPEFILTERS TYPENAME UNBOUNDVARIABLEERROR
                   UNDEFINEDERRORERROR UNDEFINEDHANDLERERROR UNLESS UNTIL UPARROW UPDATE UPDATESTATES USING
                   VALTITLELABEL VARIABLENAME VECTOR VERSIONDISPLAYED VISIBLE VSPLITTER VSPLITTERLOCATION
                   WAIT WARNIFINSUPERPROJECT WATCHER WATCHING WATCHINGMENUWATCHINGSTATE WHERE WHETHER WHILE
                   WHOSE WITH WITH\ TARGETOBJECT WITHOUT WRITELOGOBJECT WRITEOBJECT ^ \­ \² \³ \Ö)

                  ("store"
                   AUDIT EARLYINITIALIZEFROMSTORE INITIALIZE INITIALIZEFROMSTORE LIBID-TO-PROJID LIBRARIES
                   OBJECT OPENED PHEAP PROJID-TO-LIBID REQUIREDPROJECT ROOTOBJECTS SAVEDFUNCTIONS SAVEDGLOBALS
                   SAVEDHANDLERS SAVETOSTORE VERSION LOCALPROPERTIESTOSAVESPECIALLY LOCALPROPERTIESTOSAVEASFALSE
                   PROPERTIESTOSAVESPECIALLY PROPERTIESTOSAVEASFALSE PROPERTIESTOSAVENORMALLY)

                  ("User Interface"
                   *DRAGGING-FRAMECOLOR* ACCEPTSDROPS ACTIONTEXT ACTIVATETEXT ACTIVE ACTOR ACTORATHVCOORDINATES
                   ACTORTODRAW ACTORTOREPLICATE ADDCONSTANTDIALOG ADDEDMEASPARENT ADDFUNCTIONDIALOG ADDHANDLERDIALOG
                   ADDITEM ADDPARENTDIALOG ADDPORTDIALOG ADDPROPERTYDIALOG ADDVARIABLEDIALOG ALIGN ALIGNSELECTION
                   ALL ALLOWEMPTYSTRINGS ALLOWRETURNS ALLOWSPACES ANALYZEACTORSFORSELECTION APPEARINFINITE
                   ARROWSIZE AUTOHIGHLIGHT AUTOKEY AUTOTAB AVOIDING BACKGROUNDRENDERER BESTSIZE BOUNDEDBYCONTENTS
                   BROWSERCOMPONENT BROWSERHIGHLIGHT BROWSERMENUBAR BROWSERPAPER BROWSERUNHIGHLIGHT BUILDSTANDALONECHECK2
                   BUILDSTANDALONEDIALOG CACHESPIXMAP CANCELBUTTON CAPTUREPICTURE CHANGED CHECK CHECKCOLOR
                   CHECKMARK CLEARALLREFERENCES CLEARREFERENCES CLEARS CLEARSELECTION CLICK COLLECT
                   COLUMNLINESSIZE COLUMNS COLUMNSPACING COLUMNSRIGID COLUMNWIDTHS COMMANDKEYEVENT COMPONENTFROM
                   COMPUTECOLUMNWIDTHS COMPUTEROWHEIGHTS CONSHOWOBJS CONSTANTDATARECT CONSTANTS CONSTRUCT-LIST
                   CONTAINER CONTAINERS COPYTEXTPROPERTIES CREATEARROW CREATEDISPLAYITEM CREATEDNEWPROJECT
                   CREATEICON CREATESECONDITEM CREATETEXTCOLOR CREATETEXTCOLORS CREATETEXTDISPLAYITEM CREATETEXTITEMSTYLE
                   CREATETEXTSTYLE CREATETEXTSTYLES CREATIONOBJECT CREATIONOBJECTS CREATIONPROJECT CROSSAUTHORABLE
                   CURRENTDIRECTORY CURRENTFUNCTION CURRENTTOOL CURRENTVALUE DEACTIVATETEXT DELETEMENUITEMTEXT
                   DESELECTED DESKTOPBUTTON DIMENSIONS DIRTY DISABLEFILES DISPLAYEDITOR DISPLAYING DISPLAYRESOURCE
                   DISPLAYTYPE DISPOSEDIALOG DISPOSEHANDLE DISTRIBUTE DOBOOKKEEPING DOFIRSTCLICK DOTSIZE
                   DOUBLECLICK DOUBLECLICKSTYLE DRAGGABLE DRAGGINGMOUSEENTER DRAGGINGMOUSELEAVE DRAGGINGMOUSEWITHIN
                   DRAWWITH DRAWXORFRAME DRAWXORLINE DRAWXORRECTANGLE DROP DROPPED DUPLICATE EDITHANDLERDIALOG
                   EDITHANDLEROBJECTDIALOG EDITING EDITINGLIST EDITITEM EDITOR EDITORINCLUDED EDITPARENT
                   EDITTEXT ELEMENT ELEMENTS ENABLED ENTERINFIELD ENTERINGSTAGE ESCAPEACTION EVALUATE EXACTMATCH
                   EXPRFUNCTION EXTENDEDMOUSEDOWN FILEACTION FILENAMEGETTER FILLCOLOR FILLSELECTION FILTER
                   FILTERPROJECT FINDANDSELECT FINDNEXTFOLDER FINDSELECTEDACTORS FINDSELECTEDACTORSGROW FIRST-STRINGS
                   FITTOBOUNDS FITTOSELECTEDITEMS FLASHITEM FLASHLINE FOREGROUNDRENDERER FRAMECOLOR
                   FUNCTIONDATARECT FUNCTIONS GENERATEITEMS GETANSWERFROMUSER GETCONTENTFROMUSER GETDUPLICATEFROMUSER
                   GETFILES GETFROMUSER GETFROMUSERBUTTON GETFROMUSERDIALOG GETITEMPOSITION GETLINEPOSITION
                   GETNEWFROMUSER GETOBJECTFIELD GETOBJECTFIELDGETFROMUSERBUTTON GETOBJECTFIELDSIMPLETEXT
                   GETOBJECTFIELDTEAROFFRECT GETRECTSHAPEFROMUSER GETSHAPEFROMUSER GETTERBUTTON GETVALUEFROMUSER
                   GLOBALDATARECT GLOBALS GRAPHER GRAPHIC HANDLEHOLDERS HANDLER HANDLERDATARECT HANDLERNAME
                   HANDLERPICKERITEMDISPOSE HANDLERPICKERNEWMENUITEM HANDLERPICKERSHOWPRIVATE HANDLERPICKERVIEWTYPEMENUITEM
                   HANDLERVIEWERTEXT HEIGHT HIERARCHICALOBJECTPICKER HIGHLIGHT HIGHLIGHTCOLOR HIGHLIGHTERHALO
                   HIGHLIGHTSELECTION HIGHLIGHTSTATE HISTORY HISTORYEND HISTORYLENGTH HISTORYMENU HISTORYVIEWER
                   HORIZONTALCENTER HORIZONTALSCROLL HORIZONTALSPACING ICONSIZE IMAGEARRAY INHERITABLECHECK
                   INHERITED INITIALIZE INITIALSTATEFORNEWMOVIEPARENT INNERRECT INPUTHANDLER INPUTHANDLERS
                   INPUTMENU INPUTMENUBAR INPUTOBJECT INPUTOBJECTS INPUTPROJECT INPUTPROPERTY INPUTPROTOTYPE
                   INPUTSTRING INSETSIZE ITEM ITEMBOUNDSRECT ITEMCONTENTS ITEMS ITEMVISIBLE KEYDOWN KEYUP
                   LABEL2 LABEL3 LABELTEXT LASSO LASTSELECTED LASTSELECTION LAYOUTDIALOG LEAVINGSTAGE LINECOLOR
                   LINESPACING LIST LIVERESIZE LOCAL LOCALVIRTUALPROPERTIES MACFILETYPE MAKEBOUNDSREGION
                   MAKEFILLREGION MAKEFRAMEREGION MAKEMENU MAPITEMS MARKRENDERER MARKS MAXIMUMLENGTH MENUFORHANDLERPICKERS
                   MENUFOROBJECTPICKERS MENUFOROBJECTPICKERSITEMDISPOSE MENUFOROBJECTPICKERSNEWMENUITEM MENUFORPROPERTYPICKERS
                   MENUFORVALUEEDITORPICKERS MENUITEMPROTOTYPE MENUPROTOTYPE MENUSELECT MESSAGETOUSER MHOPRELATION
                   MHOPSWATCHESSHOWN MINHEIGHT MINWIDTH MIXINFOROBJECTPICKERS MIXINFOROBJECTPILES MIXINFORPROJECTDATAPICKERS
                   MIXINFORPROPERTYHANDLERPICKERS MOUSEDOWN MOUSEENTER MOUSELEAVE MOUSESENSITIVITY MOUSEUP
                   MOVEOFFSTAGE MOVEONSTAGE MULTIPLEDRAW MYRENDERER NAMEFIELD NEWCONSTANTMI NEWFILEDIALOG
                   NEWFUNCTIONMI NEWMENUITEMTEXT NEWPROJECTDIALOG NEWSTATEWHENDONE NEWVARIABLEMI NUMBER NUMBER1
                   NUMBER2 NUMBER3 NUMBER4 OBJECT OBJECTDATARECT OBJECTFROM OBJECTLIST OBJECTNAMEDIALOG OBJECTS
                   OFFSET OKBUTTON OKSK8CHARACTER OKTOGETVALUEFROMUSER OLDITEMS ONSTAGE OPENALREADY OPENBUTTON
                   OPENEDPROJECT OPENFILEDIALOG OPENPROJECTDIALOG OUTPUTCONSTANT OUTPUTFILE OUTPUTFUNCTION
                   OUTPUTHANDLE OUTPUTHANDLER OUTPUTMENU OUTPUTMENUITEM OUTPUTOBJECT OUTPUTOBJECTS OUTPUTPROPERTY
                   OUTPUTSTRING OUTPUTVARIABLE PARENTS PARTNERHSCROLLER PARTNERSCROLLER PARTNERVSCROLLER
                   PAUSEWITHHIGHQUALITY PCPEDITPARENT PCPGETTERBUTTON PCPINHERITABLEBOX PCPPRIVATEBOX PCPPROPAGATE
                   PCPREINHERIT PCPSETTERBUTTON PDPMENU PDPMENUITEMDISPOSE PENSIZE PHYSICALSCALE PICKER PICKERMENU
                   PICKERMENUITEM PLAYWITHNOOTHERACTIVITY POINTONWHICHPART PORTTYPE PRESERVE PREVIEWMODE
                   PREVIOUSSTATE PRIVATECHECK PROJECT PROJECTDATASHEETPICKER PROJECTNAMEGETTER PROPAGATEBUTTON
                   PROPERTYCONTROLPANEL PROPERTYDATARECT PROPERTYHANDLERSHEETPICKER PROPERTYNAME PROPERTYPICKERITEMDISPOSE
                   PROPERTYPICKERNEWMENUITEM PROPERTYPICKERPORTMENUITEM PROPERTYPICKERSHOWPRIVATE PROPERTYPICKERVIEWTYPEMENUITEM
                   PROPERTYSHEETPICKER QUERYFIELD QUERYFIELDHISTORYMENU QUERYFIELDSCRIPTEDITTEXT RECOMPUTESIZES
                   REINHERITBUTTON RELATION REMEMBERACTORS REMEMBEREDACTORS REMOVECONSTANTDIALOG REMOVEFUNCTIONDIALOG
                   REMOVEHANDLERDIALOG REMOVEPARENTDIALOG REMOVEPROPERTYDIALOG REMOVEVARIABLEDIALOG RENDER
                   REPEATING RESET RESIZABLE RESIZED RESIZINGSTYLE RESTORE RESTYPE RETURNACTION RETURNINFIELD
                   RETURNVALUE ROWHEIGHTS ROWLINESSIZE ROWS ROWSPACING ROWSRIGID RUNNING SCALE SCRIPTINPUTCOMPLETED
                   SEARCHFIELD SEARCHFIELDSIMPLETEXT SEARCHSCRIPTS SELECTALL SELECTBYROWS SELECTED SELECTEDITEM
                   SELECTEDITEMS SELECTEDITEMSBOUNDSRECT SELECTFROMCOLLECTIONDIALOG SELECTION SELECTIONARRAY
                   SELECTIONBORDER SELECTIONCOMPLETED SELECTIONFUNCTION SELECTIONRENDERER SELECTIONSTYLE
                   SELECTWITH SENDUPDATEEVENT SERVICING SETINFORM SETOUTPUTSTRING SETTERBUTTON SETUP SETUPFORPROJECT
                   SETUPIMAGES SETUPITEMS SETUPSELECTIONARRAY SETUPTEXTCOLORS SETUPTEXTSTYLES SHOWORIGINALSIZE
                   SHOWSCONSTANTS SHOWSELECTION SHOWSFUNCTIONS SHOWSHANDLERS SHOWSOBJECTNAMES SHOWSOBJECTS
                   SHOWSPRIVATES SHOWSPROPERTIES SHOWSVARIABLES SIZE SPEEDCONTROL SPLICENEWPARENT STATE STRING
                   STYLETODRAW SURROUNDOBJECT SWATCHESSHOWN SYMBOL TABLEHOFFSET TABLEPICKER TABLEVOFFSET
                   TAGDIALOG TAGGEDOBJECT TARGETPROJECT TEAROFFRECT TEXTCOLOR TEXTCOLORS TEXTFIELD TEXTFONT
                   TEXTLOCATION TEXTSTYLE TEXTSTYLES THEFILE THEPARENT TILE TWOBYNBROWSERPICKER TYPEOFSAMPLE
                   UISELECTION UNDOABLESET UNDOABLESETLOG UNDOLASTSET UPDATE UPDATE-HORIZONTAL-PARTNERSCROLLER
                   UPDATE-VERTICAL-PARTNERSCROLLER UPDATESECONDITEMS UPDATETABLEPICKER VAL VALUE VALUEEDITORPICKER
                   VALUEEDITORPICKERITEMDISPOSE VALUEEDITORPICKERNEWMENUITEM VALUEFROMUSERASAMENU VALUELIST
                   VALUETEXT VERTICALCENTER VERTICALSCROLL VERTICALSPACING VIEW VIEWBY VIEWTYPE VISIBLE WANTSIDLE
                   WIDTH WINDOWSTYLE WINDOWTITLE WRITEVALUE YESORNODIALOG ZOOMBOUNDSRECT ZOOMRECT)

                  ("SKIL SK8Script"
                   CHARACTERPOSITIONOFERROR CLEARALLBREAKPOINTS CLEARBREAKPOINT COMPILESCRIPTHANDLER CONTAINSACTIVEBREAKPOINTS
                   CREATEMODULE DEBUGABORT DEBUGGO DEBUGSTEP DEFAULTMODULE DESCRIPTIONOFERROR EVALUATEEXPRESSIONINLOCALCONTEXT
                   EVALUATESCRIPTTRANSLATION EXAMINABLEHANDLERS HANDLERIDFROMSCRIPT HANDLERIDTOHANDLEROBJECT
                   LINEOFERROR MAKE-SYMBOL-A-FUNCTION MAKE-SYMBOL-A-HANDLER REGISTEREXPRESSIONFORRUNTIMEUSE
                   SETBREAKPOINT TRANSLATESCRIPTCOMMANDOREXPR)

                  )
#|
	Change History (most recent last):
	9  	 2/ 7/96	Brian   	
	10 	 2/ 8/96	sidney  	
	2  	 4/29/96	Hernan  	Adding sleep which is provided as a sk8-function in the
						processes file.
	3  	 5/ 7/96	sidney  	
	4  	 5/ 8/96	Hernan  	
	5  	 5/ 9/96	sidney  	
	6  	 5/20/96	sidney  	
	7  	 5/23/96	sidney  	
	8  	 7/ 7/96	sidney  	changes for native PPC build
	9  	 8/ 5/96	Hernan  	
	10 	 9/30/96	sidney  	changes to put sk8 windows in separate threads
	11 	10/ 7/96	Brian   	adding maintaintypetables.
	12 	10/10/96	Hernan  	Replacing compactProject with compactProjectCode, a
						function that removes every old version of every handler
						and function saved with the project.
	13 	10/17/96	Hernan  	Adding actor to printer.
	14 	10/17/96	Hernan  	Adding aboutbox
	15 	10/18/96	sidney  	remove some no longer used symbols
	16 	11/22/96	Hernan  	Adding originalAncestor.
	17 	11/25/96	Hernan  	Adding the AppleScript Object.
	18 	 2/27/97	Hernan  	
|# ;(do not edit past this line!!)
