;;; SK8 © 1997 by Apple Computer, Inc.
;;; The code in this file is protected under the terms of the current SK8 License.
;;; For information on this license, see http://sk8.research.apple.com
;;; Apple Computer, Inc. -- Apple Research Laboratories


;; Exports updated  1-18-95  10:12 am

(in-package :SK8)



(SK8-declare-syms :SK8 :private

                  ("2-d graphics"
                   $BREAKPOINT-PANE-WIDTH $CLICKCORRECTATLINEEND $CLICKCORRECTATLINESTART $CLICKINCORRECTATLINEEND
                   $CLICKINCORRECTATLINESTART *$CRSRNEW* $DOUBLECLICKDIST $HILITE *$MOUSE* *$MTEMP* *$RAWMOUSE* $SCRAPVARS
                   *ACTIVE-MOVIE-CONTROLLERS*
                   *ACTIVE-MOVIES-WITHOUT-CONTROLLERS*
                   *movies-with-bogus-file*
                   *ACTORUNDERDRAGGING*
                   *ARROW-POINT-VECTOR*
                   *BOTTOM-EDGE* *CLIP* *COLLISIONS-OCCURED* *CURRENTVIEWER* *DEEPCOPYNS* *DIRTY-PARENTS*
                   *DRAGGEDOVER-EDITTEXT-FRAMECOLOR* *ED-FRED-UNDOING-P* *EVENT-LOCATION* *EVENT-WINDOW*
                   *EVENT-X* *EVENT-Y* *FIELD-INITIATED-CHANGE-P* *FIELD-UPDATE-HOOK* *FORBIDDEN-FIELD-TEXT-COLOR*
                   *FORBIDDEN-FIELD-TEXT-COLOR.BLUE* *FORBIDDEN-FIELD-TEXT-COLOR.GREEN* *FORBIDDEN-FIELD-TEXT-COLOR.RED*
                   *GNODE-SEPARATION* *GNODE-TOLERABLE-SPREAD* *GNODES-DRAWN* *LAST-CLICK-LOCATION* *LAST-CLICK-TIME*
                   *LAST-EVENT-LOCATION* *LAST-MOUSEDOWN-LOCATION* *LAST-MOUSEDOWN-OBJECT* *LAST-MOUSEDOWN-TIME*
                   *LIVE* *MAKING-MASK* *MODAL-DIALOG-UP* *MOVIES-INITIALIZED* *NO-UI-WINDOWS* *OBJECT-UNDER-MOUSE*
                   *POST-GC-CURSOR* *PRESERVED-RECORDS* *SCRIPT-ERROR-BOX* *SCRIPTEDITTEXTS-ONSTAGE-&-SHOWINGACTIVE*
                   *SCROLLING* *SK8-ED-FRED-COMTAB* *SK8-PEN-MODES* *SK8-SCRIPT-FRED-COMTAB* *SK8-WINDOW-CLASS*
                   *STAGE-COVERED-WHEN-APP-SAVED* *TBDISPLAYITEM-HEIGHT* *TBDISPLAYITEM-WIDTH* *THE-PEN*
                   *TOP-EDGE* *WINDOWS-RECREATED* 0.5PI 1.5PI 2PI ABORT-ATTACH-TO-ACTOR ABORT-ATTACH-TO-STAGE
                   ACTIVATE-FIELD ACTOR-LINE-HEIGHT ACTOR-TEXT-SIZE ACTOR-TO-PICT ADD-ACTOR-TO-WINDOW ADD-ARROWS
                   ADD-FIELD-TO-WINDOW ADD-MENU ADD-MENUS ADD-ONE-NODE-TO-WINDOW ADD-THE-ARROWS ADD-TO-EDGE
                   ADD-TO-SEARCH-STRING ADJUST-POINTS-FOR-STAGE ADJUST-SIZE-TO-MULTIPLES ADOPT ARROWLINE?
                   ARROWS-LINE-POINTS-TO-PROPERTIES ARROWS-LINE-PROPERTIES-TO-POINTS AT-HANDLER-END? ATTACH
                   ATTACH-TO-ACTOR ATTACH-TO-STAGE ATTACHDYNAMICRENDERER AVG-KIDS BEST-OBJECTSTRING-FOR-HANDLERCALL
                   BIND-LABEL-TEXT BLOCK-P BUILDPICKERTEXT BWPATTERNINCLIPBOARD CALC-ICONTEXTPICKER-LINEHEIGHT
                   CALC-ROUNDEDNESS CENTERONITEM CHANGE-LINE-TYPE CHANGING-POLY-RECT CHECK-AND-CORRECT-COLLISIONS
                   CHECK-CHANGE-IN-ACTOR-PARENTS CHECKBOXCHECK-DRAW CHECKCONTENTS CHECKMENUBARFORCMDKEY CHECKMENUFORCMDKEY
                   CICNINCLIPBOARD CLEANSCROLLERS! CLEAR-ALL-SAVED-FIELD-TEXT CLEAR-PRESERVED-INFO CLEAR-SAVED-FIELD-TEXT
                   CLEAR-SEARCH-STRING CLEAR-YEDGE CLOSEST-POINT-TO CM-COORDS COLLECT-OBJECTS COLLISIONS-PERSIST
                   COLORCURSORHOOK COLORCURSORINCLIPBOARD COLORMASKEDACTORDRAW COLORPATTERN-TO-PORT-TO-REGION
                   COLORPATTERNINCLIPBOARD COMPACTSK8 COMPILE-BOTTOM-EDGE COMPILE-BOTTOM-EDGE-FOR-KIDS COMPILE-IMPORTABLE-RESOURCES
                   COMPILE-ITEM-INDECES COMPILE-SELECTION-LIST COMPILE-TOP-EDGE COMPILE-TOP-EDGE-FOR-KIDS
                   COMPUTE-GLOBALVARS-LIST COMPUTE-HANDLERCALLS-LIST COMPUTE-LOCALVARS-LIST COMPUTE-PIXEL-VALUE
                   CONNECTORS-AND-ACTORS CONNECTTHEITEMS CONSTRUCT-RECT-CACHE COORDS-DISTANCE COORDS-EQUAL-P
                   COORDS-IN-RECT-P COPY-ED-FRED COPY-FIELD COPY-LINEINFO COPY-PT COPY-RECT COPY-SK8RECT
                   COPYRESOURCETOMEDIA COPYRESOURCETOMEDIAHOLDER COPYRESOURCETOPROJECT CORRECT-LEAFDOM CORRECT-MISTAKES
                   COVERED-BY-SIBLINGS? CREATE-NECESSARY-CONNECTORS CREATE-TBDISPLAYITEM CURSOR-KEY-P CURSORINCLIPBOARD
                   CURVAL-TO-STARTTHUMB DELETE.CALC-BUFFER-KILLED-AND-DIRTY-LINES DELETE.UPDATE-LINEINFO
                   DETACH DETACH-FROM-ACTOR DETACH-FROM-STAGE DETACHDYNAMICRENDERER DIRTYSCROLLERS! DISABLE-MENUS
                   DISABLE-NON-STANDARD-MENU-ITEMS DISCONNECT-SCROLLER-PORTS DISPATCH-CLICK DISPOSE-FIELD
                   DISPOSE-SUBTREE DISTANCE DO-SK8-WINDOW-ACTORS DODRAGEVENTSIFNECESSARY DONONLIVEDRAGONSTAGEDRAW
                   DRAG-MOVE-IF-NECESSARY DRAW-CONNECTIONS DRAW-FRED-WITH-CURSOR DRAW-GNODE DRAW-MENU-AS-POPUP
                   DRAW-ONE-LEVEL DRAW-RUNNINGLINE-ARROW DRAW-RUNTIMEERROR-MARKER DRAW-SEGMENT DRAW-SIMPLE-LINE
                   DRAW-TEXT-NOT-WRAPPED DRAW-TREE DRAWMULTILINEPICKERITEM DRAWMULTILINEPICKERTEXT DRAWPICTFILE
                   DYNAMIC-NUMBER DYNAMIC-PLANT-AND-RESHAPE ED-DELETE-WITH-UNDO ED-FRED-DEFAULT-KEY-HANDLER
                   ED-FRED-DELETE ED-FRED-DELETE-CHAR ED-FRED-DELETE-WORD ED-FRED-INSERT ED-FRED-INSERT-CONTINUATION
                   ED-FRED-MAYBE-SHRINK-LINEHEIGHT ED-FRED-REPLACE-RANGE ED-FRED-REPLACE-RANGE-WITH-UNDO
                   ED-FRED-RUBOUT-CHAR ED-FRED-RUBOUT-WORD ED-INSERT-WITH-UNDO ED-NEXT-LINE ED-NEXT-LINE-POS-WRAPPED
                   EDITOR-BREAKPTINFO->INTERNAL-BREAKPTINFO EDITOR-BREAKPTINFO->INTERNAL-CONDITIONEXPRS EDITTEXT-DRAW
                   EFFECT-GWORLD-TO-WINDOW EMPTY-FUNCTION EMPTY-SCRIPT-LINE-P ENFORCE-WITHIN-RECT ENROLL-IN-TAKEN-SPOTS
                   ENROLL-TREE-IN-TAKEN-SPOTS ERASE-RUNTIMEERROR-MARKER EVERY-SUBACTOR EXIT-SCRIPT-RUNNING-MODE
                   F* F+ F- F.CEILING F.FLOAT F.FRACT F.ROUND F.TRUNC F/ FASTPICKER-DRAW FAVERAGE FDECF FDOUBLE
                   FHALF FIELD-ACTIVATED-P FIELD-CHAR-AT-POINT FIELD-POINT-AT-CHAR FIELD-SELECTION-HILITED-P
                   FIELD-TO-GWORLD FINCF FIND-ARROW-POINTS FIND-COLLISION-MAGNITUDE FIND-DH-AND-DV FIND-DY
                   FIND-EXTENT-SIZE FIND-NEXT-ACTOR FIND-POINTS-FOR-ARROWS FIND-RECT-TO-BIND-CONTENTS FIND-RESIZE-DIRECTION
                   FIND-ROOT-AND-CLEAR-HANDLES FIND-ROOT-POSITION FIND-SAFE-DV FIND-SIBLINGS-TO-THE-BOTTOM
                   FIND-SIBLINGS-TO-THE-TOP FIND-SPOT-BY-ANCESTRY FIND-TRANSLATOR FIND-WORD-BREAK FIND-WORST-CRASH
                   FINDIMPORTTRANSLATOR FINDLINEOF-CONTAINING-IFONEOF FINDLINEOF-CONTINUATIONSTART FINDLINEOF-IF-MATCHING-ELSE
                   FINDLINEOF-IF-MATCHING-ENDIF FINDLINEOF-MATCHING-PLAINBLOCKSTART FINDLINEOF-PREVIOUS-CASECLAUSESTART
                   FINDVALIDDROPRECIPIENT FIX-SPLITTER-DAMAGE FIXED-POINT FIXED-POINT-P FLOAT-TO-FIXED FMOD
                   FOCUS-VIEW FREC-LINEHEIGHT FRED-MOUSE-POS GENERIC-PLANT GET-ARROW-POINTS GET-BOUNDSRECT-COORDS
                   GET-BOUNDSRECT-FROM-ENDPOINTS GET-CHAR-NUMBER GET-COLOR-FROM-USER GET-EDITTEXT-STYLE-ASPECT
                   GET-FIELD-AUTOWRAP GET-FIELD-BOTTOMLINE GET-FIELD-MEASUREMENTS GET-FIELD-SCROLL GET-FIELD-TEXT
                   GET-FIELD-TOPLINE GET-FROM-SCRAP GET-GNODE-KIDS GET-HANDLER-WATCHEXPRESSIONS GET-LINE-NUMBER
                   GET-LINEHEIGHT GET-NTH-CHARS-BOUNDS GET-NTH-ITEMS-BOUNDS GET-NTH-LINES-BOUNDS GET-NTH-PARAGRAPHS-BOUNDS
                   GET-NTH-WORDS-BOUNDS GET-PRESERVED-INFO GET-TOP-LEFT-POINTS GET-TYPE-FROM-SCRAP GETTEXTFROMMCLSCRAP
                   GLOBALREF GN-LOCATION GNODE-DRAWN GROW-THE-TREE HANDLE-IDLE HANDLE-KEY HANDLE-MOUSEDOWN
                   HANG-ON HILITE-FIELD-SELECTION ICON-TEXT-PICKER-DRAW IMPORTTRANSLATORSAPPLICABLE IMPORTTYPES
                   INIT-OVERVIEWER INIT-OVERVIEWER-HILITE INITIALIZE-FOR-NEW-ACTOR-PARENT INITIALIZE-FOR-NEW-POLYGON-PARENT
                   INITIALIZE-INSTANCE INITIALIZE-SNAPSHOT-PIXMAP INITIALIZE-STRUCT INITIALIZE-TREEBROWSER
                   INSERT-AT-END INSERT-IN-TAKEN-POSITIONS INSERT.CALC-BUFFER-ADDED-AND-DIRTY-LINES INSERT.UPDATE-LINEINFO
                   INSERTABLE-KEY-P INSET-RECT INSTANT-MENU INT-TO-FIXED INTERNAL-BREAKPTINFO->EDITOR-BREAKPTINFO
                   INTERNAL-H INTERNAL-LOCATION INTERNAL-SETLOCATION INTERNAL-V INTERSECT-RECTS JUST-MODIFIED-SCRIPTTEXT
                   JUST-MODIFIED-SCRIPTTEXT-FOR-1ST-TIME LAST-KEY-TIME LET+ LEVEL-TO-X LINE-INDENTATION-LEVEL
                   LINE-POINTS-TO-PROPERTIES LINE-PROPERTIES-TO-POINTS LINEBREAKINFO-ADD-CONDITION LINEBREAKINFO-BREAKON?
                   LINEBREAKINFO-CONDITIONFORM LINEBREAKINFO-CONDITIONSTRING LINEBREAKINFO-CONDITIONVISIBLE?
                   LINEBREAKINFO-HIDE-CONDITION LINEBREAKINFO-SHOW-CONDITION LIVE-LINE-RESIZE LIVEDRAG LOAD-FIELD-TEXT
                   MAKE-IMAGERENDERER-FROM-NEW-MEDIA MAKE-INSTANT-MENU MAKE-ITEM-MENU MAKE-LINEINFO MAKE-LINEINFO-VECTOR
                   MAKE-PT MAKE-RECT MAKE-SCRIPT-ERROR-BOX MAKING-PICKER-DIRTY MALFORMED-HANDLER-DEFINITION?
                   MASK-TO-QD-REGION MAYBE-ADD-TO-*SCRIPTEDITTEXTS-ONSTAGE-&-SHOWINGACTIVE* MAYBE-COMPLAIN-ABOUT-ACCESSOR-METHOD
                   MAYBE-COMPLETE-SCRIPT MAYBE-ENTER-SCRIPT-RUNNING-MODE MAYBE-HANDLE-COMPLETE-SCRIPT MAYBE-REFRESH-SCRIPTEDITOR-VARLISTS
                   MAYBE-WITH-CLIPPED-REGION MCL-COLOR MERGE-WITH-CURRENT-FONT-SPEC MODE-ARG MOST-NEGATIVE-LONGINT
                   MOST-POSITIVE-LONGINT MOUSEDOWN-IN-BREAKPOINTS-STRIP MOVE-DIRTY-GNODES MOVE-TO-POSITION-HELP
                   MOVETOPOSITION MULTILINEPICKER-DRAW NEW-FIELD NEW-FRED NEW-SCALED-SIZE NMAPCAR NONLIVEDRAG
                   NONLIVEDRAGONSTAGE NORMAL-LINE-POINTS-TO-PROPERTIES NORMAL-LINE-PROPERTIES-TO-POINTS NORMALLINE?
                   NUM-TO-STYLE OFFSET-POINT-LIST OFFSET-POLY-POINTS OFFSET-RECT OFFSET-RECTS-AND-DIRTY-THE-REST
                   OFFSET-VECTOR-IN-PLACE OV-DRAW-GNODE OVERVIEWER-DRAW PARSE-STYLELIST PARSEPICKERTEXT PATTERN-TO-PORT-TO-REGION
                   PEN-INSTALLED PICKER-DOUBLECLICK-FILTER PICKER-STRING-SEARCH PICKERTIMEISUP PICTFILETOHANDLE
                   PICTINCLIPBOARD PIXMAP-TO-PIXMAP PLANT-A-BRANCH PLANT-A-LEAF PLANT-A-WHAT PLANT-NEW-CHILDREN
                   PLANT-NEW-ROOT POINT-ON-WHICH-GNODE POPUP-MENU-DRAW POPUPBALLOONFORHELP POSITION-ITEM-VISIBLE
                   PREPARE-FOR-WDEF-REGION-CALCULATION PREPARE-NEW-LINE PREPARE-TO-MODIFY-SCRIPTTEXT PRESERVE-ACTOR
                   PRESERVE-CLOS-WINDOW PRESERVE-RENDERERS PRESERVE-SK8 PRESERVE-SK8-CLOCK-STATE PRESERVE-SK8-GLOBALS
                   PRESERVING-GNODE-ORIGIN PROCESS-SEARCH-STRING PROPAGATE-IF-NECESSARY PROPAGATE-LOCATIONS-TO-IMMEDIATE-PARENT
                   PROPAGATE-LOCATIONS-TO-LEFT PROTECTED-SUBSEQ-EQUALITY PT PT-H PT-P PT-V PURGE-DISPOSED-*SCRIPTEDITTEXTS-ONSTAGE-&-SHOWINGACTIVE*
                   PUT-HANDLES-AWAY QD-REGION-TO-MASK QDRECT-OFFSET-AND-FIX-SIZE RATIO-TO-FIXED REAL-MENUITEMS
                   REAL-RENDER-AN-ERROR RECT RECT-BOTTOM RECT-CENTER-COORDS RECT-CENTER-POINT RECT-IN-REGION-P
                   RECT-LEFT RECT-P RECT-RIGHT RECT-SIZE RECT-TOP RECTMAPPOINTS RECTS-OVERLAP-P REDRAW-BREAKPOINTS-STRIP
                   REDRAW-FIELD-PIX REDRAWING-OVERVIEWER REENABLE-MENUS REFRESH-VAR-AND-HANDLER-WARNINGS
                   REGION-LOCATION REGION-SIZE REINDENT-LINES RELATIVIZE-PATHNAME RELOCATE-GNODE RELOCATE-GNODE-IF-NECESSARY
                   REMOVE-FIELD-FROM-WINDOW REMOVE-FROM-*SCRIPTEDITTEXTS-ONSTAGE-&-SHOWINGACTIVE* REMOVE-FROM-TAKEN-SPOTS
                   REMOVE-INTERSECTION REMOVE-MENU REMOVE-MENUS REMOVE-TREE-FROM-TAKEN-SPOTS RENDER-AN-ERROR
                   RENDER-ICON-MEDIA RENDER-PICT-STRETCHED RENDER-PICT-TILED RENDER-PICT-UNSTRETCHED RENDER-STRING
                   RENDER-TEXT RESET-MENU-NUMBERS RESETLINEINFO RESTORE-ACTOR RESTORE-CLOS-WINDOW RESTORE-CURSOR
                   RESTORE-LINEINFO-FROM-HISTORY RESTORE-PROJECT-WINDOWS RESTORE-SCRIPTEDITTEXT-FONTATTRIBUTES
                   RESTORE-SK8 RESTORE-SK8-GLOBALS RESTORE-SK8-INSTANT-MENUS RESTORE-SK8-INTERNALS RESTORE-SK8-MENUBAR
                   RESTORE-SK8-SETF-MOUSELOC RESTORE-SYSTEMEVENTMASK RESTORE-TEXT-STATE RESTOREITEMPOSITION
                   RESTYPE-STRING RETURN-EMPTY-BOUNDS RETURN-THE-HANDLES REVALIDATE-SNAPSHOT-PIXMAP REVALIDATE-SNAPSHOT-PIXMAP-INTERNAL
                   REVERSE-PICKER-MAPSTATE ROOT-GNODE ROOTONITEM ROTATE-COORDS-2D ROUND-UP SAVE-FIELD-TEXT
                   SAVE-HANDLER-WATCHEXPRESSIONS SCALE-TO-OV-X SCALE-TO-OV-Y SCRIPT-SYNCH-SCRIPTEDITTEXT-TO-FILLREGION
                   SCRIPT-WINDOW-ERROR-SHOWN? SCRIPT-WINDOW-ERROR-TEXT SCRIPTEDITTEXT-DRAW SCRIPTEDITTEXT-INSERTION-NEEDS-LEADINGSPACE?
                   SCRIPTEDITTEXT-INSERTION-NEEDS-TRAILINGSPACE? SCROLL-TO-SEL-IF-NECESSARY SCROLLER-PIXEL-VALUE
                   SCROLLERORIENTATION SCROLLERSDIRTY? SEARCH-STRING SELECT-CORRECT-ACTOR-DRAW-FUNCTION SELECT-ENTIRE-LINE
                   SELECT-FIRST-ITEM SELECT-LAST-ITEM SELECT-NEXT-ITEM SELECT-PREV-ITEM SELECT-WHOLE-RANGE
                   SENDTEXTTOMCLSCRAP SEPARATE-THE-WATERS SET-ANCHOR SET-BLOCK SET-CURSOR-INTERNAL SET-EDITTEXT-STYLE-ASPECT
                   SET-FIELD-AUTOWRAP SET-FIELD-BOTTOMLINE SET-FIELD-OWNER SET-FIELD-SCROLL SET-FIELD-SEL-MODES
                   SET-FIELD-SELECTION SET-FIELD-SIZE SET-FIELD-TEXT SET-FIELD-TOPLINE SET-FIELD-TYPESTYLE
                   SET-LAST-KEY-TIME SET-LINE-INDENTATION SET-MAGNIFIC SET-PEN-FOR-HILITE SET-POINT SET-POINTS-ON-STAGE
                   SET-PRESERVED-INFO SET-RECT SET-RECT-CENTER SET-RECT-SIZE SET-RECTANGLE-INTERNAL SET-SCROLLER-PIXEL-VALUE
                   SET-SEGMENT-POINTS-ON-STAGE SET-TEXT-STATE SET-VERSIONDISPLAYED* SETF-TLA-BOUNDSRECT SETF-TLA-LOCATION
                   SETQUICKDRAWFONTSTUFF SETUP-SCRIPTEDITOR-HANDLER-FROM-STORE SETUP-SCRIPTEDITOR-HANDLER-TEMPLATE
                   SETUP-SCRIPTEDITOR-HANDLER-TEMPLATE-FOR-ACCESSOR SETUPARROWS SETUPICONS SETUPOFFSETS SETWINDOWRECT
                   SETWINDOWRECT-FOR-TOOLWINDOW SHADOW-TEXT-INSERTION SHIFT-GNODE-ANCHORING-BY SHIFT-KIDS-TO-TOP
                   SHIFT-PLAUSIBLE SHIFT-SUBTREE-BY-DY SHIFT-TOP-SIBLINGS SHIFT-TREE-BY-DY SHOW-ERROR SHOWTHEITEMS
                   SHOWTREE SHRINK-FOREST SILLY-FIELD-FORCE-UPDATE SIMPLE-LINE-PROPERTIES-TO-POINTS SIMPLELINE?
                   SK8-BUFFER-REPLACE-FONT-SPEC SK8-FREC-LINE-START SK8-FREC-SCREEN-LINE-NUM SK8-FRED SK8-RECT-TO-LIST
                   SK8-SCRIPT-FRED SK8-SETEVENTMASK SK8IMPORTABLERESOURCES SK8RESTOREMENU SKIP-WHITESPACE
                   SNDINCLIPBOARD SPECIAL-FORCEREDRAW SPECIALDRAG SPLICE SPLICEATPOSITION STARTTHUMB-TO-CURVAL
                   STATE-ITEMS STATE-STRINGS STATIC-OVERVIEWER-DISPLAY STATICDISPLAY STEFIELD STRING-PRECEDES-SCRIPTEDITTEXT-INDEX
                   STYLEDPICKER-DRAW SWITCH-OUT-OF-RUNNING-MODE SYNCH-SCRIPTEDITTEXT-TO-FILLREGION SYSTEM-SCRAPCOUNT
                   TLA-BOUNDSRECT TLA-DRAG TLA-LOCATION TRACK-MOUSEDOWN TRACKINGMOUSEDOWN TRANSFER-SNAPSHOT-PIXMAP
                   TRANSFORMING-ORIGINALS-TO-POLY-POINTS TRANSLATESTYLE TREEVIEWER-DRAW TRUE-BOUNDS UNDO
                   UNION-RECTS UNIQUERESID UNSCALE-X UNSCALE-Y UNWIRE-TREEVIEWER-PORTS UPDATE-COMPLETE-LINE
                   UPDATE-DIRTY-LINES UPDATE-FIELD-IF-NECESSARY UPDATE-LINEINFO-HISTORY UPDATE-PARTNERSCROLLER
                   UPDATE-POINTS UPDATE-POINTS-ON-STAGE UPDATE-SCRIPT-RUNNING-MODE UPDATE-WINDOWS-FOR-NEW-DEPTH
                   UPDATEPARTNERSCROLLER UPDATESCROLLERS VECTOR-SHIFT-END* VIEW-CONTAINER VISUAL-EFFECT-BLIT
                   WINDOW-SHOW-CURSOR WITH-FAST-NODE-SLOTS WITH-FRED-DRAWING WITH-FRED-PORT WITH-HILITECOLOR
                   WITH-TEMPORARY-PORT WITHIN-BOUNDSRECT? WITHLOCKEDCURSOR WITHPEN WITHVISUALEFFECT WORST-COLLISION
                   WRITEHANDLETOPROJECTFILE X-TO-LEVEL YEDGELINE _FSCLOSE _FSOPEN _FSREAD _GETEOF _SETFPOS)

                  ("Development Utilities"
                   *TIMER-DEPTH* *TIMER-HASH-TABLE* *TIMER-PRINT-ARGS* *TIMER-PRINT-INDIVIDUAL-CALLS* *TIMER-VECTOR*
                   *TIMER-VECTOR-LENGTH* ADD-TIMERS DO-FUNCTION-REFS-INTERNAL FORMAT-TAB INITIALIZE-TIMERS
                   LISP-HEAP-SIZE LIST-CALLERS LIST-FUNCTION-REFERENCES LIST-REFERENCES MAP-CALLERS MAP-DYNAMIC-SPACE
                   MAP-LISP-SPACE MAP-REFERENCES MAP-STATIC-SPACE PRINT-CALLERS PRINT-REFERENCES PRINT-TIMER-TOTALS
                   REMOVE-TIMERS RESET-TIMER-TOTALS TIMED-FUNCTIONS WITH-CLEAN-TIMERS)

                  ("Function Library"
                   CURRENT-SECS-SINCE-1904 !WRITEMAYBEESCAPEDCHAR *COLLECTIONSBEINGWRITTEN* *SPECIALSTRINGCHARESCAPES*
                   *SPECIALSTRINGCHARS* ABSOLUTETIMESTATS DATE-SCRAP-CACHE DAYS-IN-MONTH-OF-YEAR LONGDATETIMETONUM
                   LUNAR-PHASE-FROM-MAC-SECONDS NUMTOLONGDATETIME REDUCE-ANGLE SETABSOLUTETIMEBYCALENDER
                   STRING-OUTPUT-STREAM TIMESTRINGTOABSOLUTETIME UNREADABLEENDCHARACTER UNREADABLESTARTCHARACTER
                   WRITEARGSNICELY WRITEESCAPEDCHAR WRITEESCAPEDSTRING)

                  ("macframes"
                   INHERITEDPROPERTIESTOSAVESPECIALLY INHERITEDPROPERTIESTOSAVEASFALSE PROPERTIESTOSAVENORMALLYINCLUDINGINTERNALS
                   QTRSTATEVALUES QTRNEWSTATEWHENDONEVALUES QTRMAINTAINASPECTRATIOVALUES $NEXTRESMAPHANDLE
                   $RESFILENUMBER %GETBIT *ACTIVE-MOVIE-CONTROLLERS* *ACTIVE-MOVIES-WITHOUT-CONTROLLERS*
                   *AE-RETURN-ID* *AE-TARGET-PTR* *CURRENT-SOUNDS* *INPUT-PORT-HASH-TABLE* *KEYWORDS-DURING-INITIALIZE*
                   *MEDIA-RESTORING-ALLOWED* *MOVIES-TO-INITIALIZE* *MOVIES-WITH-BOGUS-FILE* *NEWMOVIEACTIVE*
                   *OUTPUT-PORT-HASH-TABLE* *PORT-FEEDBACK-HISTORY* *RECEIVED-AETARGETS* *TERMINATION-TRAP-WRAPPERS*
                   ACTIVATE-MASTERS ACTIVATE-OUTPUT-PORT-PREAMBLE ALLOWING-MEDIA-RESTORING ASSUMEMOVIEGCOSPTR
                   ASSUMEMOVIEPARENT BACKTRANSLATE-PHYSICAL-PATHNAME BOUNDSREGIONGCHandle CHECK-FOR-RESERVED-NAME
                   CHECK-SK8-TYPE CHECKING-ERROR-DISPOSE-RECORD CHECKING-ERROR-MAKE-RECORD CHECKING-TOOLBOX-ERROR
                   CHECKLEGALVALUE CHECKRESIZINGSTYLE CLIPREGIONGCHandle CLONER CLOSEPROJECTFILES COERCE-TO-STRING
                   COMPATIBLE-SIGS-P CONSTANT-RECORD-TABLE COPYFILE COPYQUICKTIMEMOVIE DEACTIVATE-MASTERS DEAL-WITH-MOVIES-WITH-BOGUS-FILES
                   DEFINE-MUMBLE-FUNCTION DEFINE-PROJECT-FUNCTION DEFINE-SK8-CONSTANT* DEFINE-SK8-VAR* DEFSHAREDMOVIEPARENTPROPERTY
                   DISPLAYCLIPREGIONGCHandle DISPOSEMATTE DISPOSEMOVIEEDITSTATE DISPOSETRACKEDITSTATE DOREDRAW
                   DORESIZING DOUNMOVIEFY EXIT-MOVIES FEEDBACK-CHECK-OKAY? FILES-INTERNAL FINALIZEQUICKTIMEMOVIES
                   FINDENABLEDVISUALTRACKS FLATTENPARENTS FONTNAME-TO-FONT FONTNAME-TO-FONT-HELPER FONTNAME-TO-NUM
                   FUNCTION-RECORD-TABLE GET-PARAMETER GETMOVIEFILEFROMUSER GETRESOURCEINFO
                   GUESS-AE-TYPE HANDLEONSTAGEANDDISPLAYING HANDLER-RECORD-TABLE IGNORE-ERRORS-BUT-SENDTOLOG
                   INCOMING-APPLEEVENT INITIALIZE-COMPONENTS-TRAP-NULL-PTR-VALUES INITIALIZE-MOVIES-TRAP-NULL-PTR-VALUES
                   INITIALIZE-TRAP-NULL-PTR-VALUES INITIALIZEMOVIEFROMDATAFILE INITIALIZEMOVIEFROMHANDLE
                   INITIALIZEMOVIEFROMMOVIEGCOSPTR INITIALIZEMOVIEFROMNOTHING INITIALIZEMOVIEFROMRESOURCEFILE
                   INITIALIZEMOVIEFROMRESOURCEFILECREATE INITIALIZEMOVIEFROMSCRAP INITQUICKTIMEMOVIE INSTALL-OUTPUTTY-PORT
                   IS-MOVIE-CONTROLLER-EVENT LET+ LOGIFY-PATHNAME MAKE-AEDESC MAKE-CLOS-CLASS-SHADOW MAKE-FASTGCOSPTR
                   MAKE-OBJECT-GCABLE MAKE-PT MAKE-RECT MAPANCESTORS1 MAXINTERESTINGMEDIATYPES
                   MAYBE-TICK MCL-NAMESTRING-TO-SK8-FILENAME MOUNTED-VOLUMES MOVIE-CONTROLLERS-IDLE MOVIE-DRAW-CONTENTS
                   MOVIEDRAW MOVIES-TASK MYGETGWORLD NAMESTRING-HACKING-LOGICAL-SYNTAX NEWGWORLD NEWMOVIEFROMSCRAP
                   NEWQUICKTIMEMOVIE NMAPCAR OPENRESFILENUMS OSAETARGET-EQ PACKAGE PATH-FROM-FSSPEC PATHNAME-ALIAS-P
                   PATHNAME-FLAG-BITS PATHNAME-INVISIBLE-P PATHNAME-NAME&TYPE PORT-CHECK-SK8-TYPE PORTS-WIREABLE-CHECK
                   PRESERVE-COMPONENTS-TRAP-NULL-PTR-VALUES PRESERVE-MOVIES-TRAP-NULL-PTR-VALUES PRESERVE-TRAP-NULL-PTR-VALUES
                   PRINT-OBJECT PT QTMFINALIZEINITIALIZATION RAISESYSTEMERROR RECT RELEASEOSPTRS REMOVESPACES
                   RESET-ROOT-ALIAS RESTORE-FILE-ENVIRONMENT RESTOREORINITIALIZEFROMSTORE RESTORE-SK8-FONTS
                   ROOT-DIRECTORY ROOT-DIRECTORY-PATHNAME-P RREFTIMEVALUE64 RSETTIMEVALUE64 SET-INITARGS
                   SET-PARAMETER SETTERP SIMPLEPICTURE SK8-FILENAME-TO-MCL-NAMESTRING SK8-FILENAME-TO-MCL-PATHNAME
                   SLAVES-RUNNING? STOP-ALL-SOUNDS TC_AUTOSELECTEXPORTCOMPONENTINSTANCE TC_AUTOSELECTIMPORTCOMPONENTINSTANCE
                   TC_AUXILIARYEXPORTDATAUNAVAILABLE TC_BADCOMPONENTINSTANCE TC_BADCOMPONENTSELECTOR TC_BADCOMPONENTTYPE
                   TC_BADCONTROLLERHEIGHT TC_BADDATAREFINDEX TC_BADEDITINDEX TC_BADEDITLIST TC_BADIMAGEDESCRIPTION
                   TC_BADPUBLICMOVIEATOM TC_BADTRACKINDEX TC_BASEMEDIATYPE TC_CALLBACKATEXTREMES TC_CALLBACKATINTERRUPT
                   TC_CALLBACKATRATE TC_CALLBACKATTIME TC_CALLBACKATTIMEJUMP TC_CANNOTMOVEATTACHEDCONTROLLER
                   TC_CANNOTSETWIDTHOFATTACHEDCONTROLLER TC_CANTCREATESINGLEFORKFILE TC_CANTENABLETRACK TC_CANTFINDHANDLER
                   TC_CANTOPENHANDLER TC_CANTPUTPUBLICMOVIEATOM TC_CMPWANTSREGISTERMESSAGE TC_COMPONENTAUTOVERSIONINCLUDEFLAGS
                   TC_COMPONENTDOAUTOVERSION TC_COMPONENTDONTREGISTER TC_COMPONENTNOTCAPTURED TC_COMPONENTWANTSUNREGISTER
                   TC_CONTROLLERBOUNDSNOTEXACT TC_CONTROLLERHASFIXEDHEIGHT TC_CONVERTALLTRACKS TC_COULDNOTRESOLVEDATAREF
                   TC_COULDNOTUSEANEXISTINGSAMPLE TC_CREATEMOVIEFILEDELETECURFILE TC_CREATEMOVIEFILEDONTCREATEMOVIE
                   TC_CREATEMOVIEFILEDONTOPENFILE TC_DATAALREADYCLOSED TC_DATAALREADYOPENFORWRITE TC_DATAHANDLERTYPE
                   TC_DATANODATAREF TC_DATANOTOPENFORREAD TC_DATANOTOPENFORWRITE TC_DATAREFSELFREFERENCE
                   TC_DATAREFWASNOTRESOLVED TC_DEFAULTCOMPONENTANYFLAGS TC_DEFAULTCOMPONENTANYFLAGSANYMANUFACTURER
                   TC_DEFAULTCOMPONENTANYFLAGSANYMANUFACTURERANYSUBTYPE TC_DEFAULTCOMPONENTANYMANUFACTURER
                   TC_DEFAULTCOMPONENTANYSUBTYPE TC_DEFAULTCOMPONENTIDENTICAL TC_DFANTIALIAS TC_DFCLIPTOTEXTBOX
                   TC_DFCONTINUOUSSCROLL TC_DFDONTAUTOSCALE TC_DFDONTDISPLAY TC_DFDROPSHADOW TC_DFFLOWHORIZ
                   TC_DFHORIZSCROLL TC_DFKEYEDTEXT TC_DFREVERSESCROLL TC_DFSCROLLIN TC_DFSCROLLOUT TC_DFSHRINKTEXTBOXTOFIT
                   TC_DFUSEMOVIEBGCOLOR TC_DOTHERIGHTTHING TC_DROPSHADOWOFFSETTYPE TC_DROPSHADOWTRANSLUCENCYTYPE
                   TC_DSMEMFULLERR TC_EDITINGNOTALLOWED TC_ENDOFDATAREACHED TC_FALSE TC_FEATUREUNSUPPORTED
                   TC_FINDTEXTCASESENSITIVE TC_FINDTEXTEDGEOK TC_FINDTEXTREVERSESEARCH TC_FINDTEXTUSEOFFSET
                   TC_FINDTEXTWRAPAROUND TC_FLATTENACTIVETRACKSONLY TC_FLATTENADDMOVIETODATAFORK TC_FLATTENDONTINTERLEAVEFLATTEN
                   TC_FLUSHFROMRAM TC_FNFERR TC_FSCURPERM TC_GESTALTCOMPONENTMGR TC_GESTALTQUICKTIME TC_HINTSALLOWINTERLACE
                   TC_HINTSHIGHQUALITY TC_HINTSSCRUBMODE TC_HINTSUSESCREENBUFFER TC_HINTSUSESOUNDINTERP TC_INTERNALQUICKTIMEERROR
                   TC_INVALIDCHUNKCACHE TC_INVALIDCHUNKNUM TC_INVALIDCOMPONENTID TC_INVALIDDATAREF TC_INVALIDDATAREFCONTAINER
                   TC_INVALIDDURATION TC_INVALIDEDITSTATE TC_INVALIDHANDLER TC_INVALIDMEDIA TC_INVALIDMOVIE
                   TC_INVALIDRECT TC_INVALIDSAMPLEDESCINDEX TC_INVALIDSAMPLEDESCRIPTION TC_INVALIDSAMPLENUM
                   TC_INVALIDSAMPLETABLE TC_INVALIDTIME TC_INVALIDTRACK TC_KANYCOMPONENTFLAGSMASK TC_KANYCOMPONENTMANUFACTURER
                   TC_KANYCOMPONENTSUBTYPE TC_KANYCOMPONENTTYPE TC_KCOMPONENTCANDOSELECT TC_KCOMPONENTCLOSESELECT
                   TC_KCOMPONENTOPENSELECT TC_KCOMPONENTREGISTERSELECT TC_KCOMPONENTTARGETSELECT TC_KCOMPONENTUNREGISTERSELECT
                   TC_KCOMPONENTVERSIONSELECT TC_KEEPINRAM TC_KFIX1 TC_KFULLVOLUME TC_KMCACTIVATESELECT TC_KMCCLEARSELECT
                   TC_KMCCLICKSELECT TC_KMCCOPYSELECT TC_KMCCUTSELECT TC_KMCDOACTIONSELECT TC_KMCDRAWBADGESELECT
                   TC_KMCDRAWSELECT TC_KMCENABLEEDITINGSELECT TC_KMCGETCLIPSELECT TC_KMCGETCONTROLLERBOUNDSRECTSELECT
                   TC_KMCGETCONTROLLERBOUNDSRGNSELECT TC_KMCGETCONTROLLERINFOSELECT TC_KMCGETCONTROLLERPORTSELECT
                   TC_KMCGETCURRENTTIMESELECT TC_KMCGETMENUSTRINGSELECT TC_KMCGETVISIBLESELECT TC_KMCGETWINDOWRGNSELECT
                   TC_KMCIDLESELECT TC_KMCISCONTROLLERATTACHEDSELECT TC_KMCISEDITINGENABLEDSELECT TC_KMCISPLAYEREVENTSELECT
                   TC_KMCKEYSELECT TC_KMCMOVIECHANGEDSELECT TC_KMCNEWATTACHEDCONTROLLERSELECT TC_KMCPASTESELECT
                   TC_KMCPOSITIONCONTROLLERSELECT TC_KMCREMOVEMOVIESELECT TC_KMCSETACTIONFILTERSELECT TC_KMCSETACTIONFILTERWITHREFCONSELECT
                   TC_KMCSETCLIPSELECT TC_KMCSETCONTROLLERATTACHEDSELECT TC_KMCSETCONTROLLERBOUNDSRECTSELECT
                   TC_KMCSETCONTROLLERPORTSELECT TC_KMCSETDURATIONSELECT TC_KMCSETMOVIESELECT TC_KMCSETUPEDITMENUSELECT
                   TC_KMCSETVISIBLESELECT TC_KMCUNDOSELECT TC_KNOVOLUME TC_LOADBACKWARDTRACKEDITS TC_LOADFORWARDTRACKEDITS
                   TC_LOOPTIMEBASE TC_MAXSIZETOGROWTOOSMALL TC_MCACTIONACTIVATE TC_MCACTIONBADGECLICK TC_MCACTIONCONTROLLERSIZECHANGED
                   TC_MCACTIONDEACTIVATE TC_MCACTIONDRAW TC_MCACTIONGETFLAGS TC_MCACTIONGETKEYSENABLED TC_MCACTIONGETLOOPING
                   TC_MCACTIONGETLOOPISPALINDROME TC_MCACTIONGETPLAYEVERYFRAME TC_MCACTIONGETPLAYRATE TC_MCACTIONGETPLAYSELECTION
                   TC_MCACTIONGETUSEBADGE TC_MCACTIONGETVOLUME TC_MCACTIONGOTOTIME TC_MCACTIONIDLE TC_MCACTIONKEY
                   TC_MCACTIONMOUSEDOWN TC_MCACTIONMOVIECLICK TC_MCACTIONPLAY TC_MCACTIONRESUME TC_MCACTIONSETFLAGS
                   TC_MCACTIONSETGROWBOXBOUNDS TC_MCACTIONSETKEYSENABLED TC_MCACTIONSETLOOPING TC_MCACTIONSETLOOPISPALINDROME
                   TC_MCACTIONSETPLAYEVERYFRAME TC_MCACTIONSETPLAYSELECTION TC_MCACTIONSETSELECTIONBEGIN
                   TC_MCACTIONSETSELECTIONDURATION TC_MCACTIONSETUSEBADGE TC_MCACTIONSETVOLUME TC_MCACTIONSHOWBALLOON
                   TC_MCACTIONSTEP TC_MCACTIONSUSPEND TC_MCFLAGSUPPRESSMOVIEFRAME TC_MCFLAGSUPPRESSSPEAKERBUTTON
                   TC_MCFLAGSUPPRESSSTEPBUTTONS TC_MCFLAGSUSEWINDOWPALETTE TC_MCINFOCLEARAVAILABLE TC_MCINFOCOPYAVAILABLE
                   TC_MCINFOCUTAVAILABLE TC_MCINFOEDITINGENABLED TC_MCINFOHASSOUND TC_MCINFOISINPALINDROME
                   TC_MCINFOISLOOPING TC_MCINFOISPLAYING TC_MCINFOPASTEAVAILABLE TC_MCINFOUNDOAVAILABLE TC_MCMENUCLEAR
                   TC_MCMENUCOPY TC_MCMENUCUT TC_MCMENUPASTE TC_MCMENUUNDO TC_MCNOTVISIBLE TC_MCPOSITIONDONTINVALIDATE
                   TC_MCSCALEMOVIETOFIT TC_MCTOPLEFTMOVIE TC_MCWITHBADGE TC_MCWITHFRAME TC_MEDIAHANDLERFLAGBASECLIENT
                   TC_MEDIAHANDLERTYPE TC_MEDIAQUALITYBEST TC_MEDIAQUALITYBETTER TC_MEDIAQUALITYDRAFT TC_MEDIAQUALITYNORMAL
                   TC_MEDIASAMPLENOTSYNC TC_MEDIASAMPLESHADOWSYNC TC_MEDIATYPESDONTMATCH TC_MOVIECONTROLLERCOMPONENTTYPE
                   TC_MOVIEFILETYPE TC_MOVIEINDATAFORKRESID TC_MOVIEPROGRESSCLOSE TC_MOVIEPROGRESSOPEN TC_MOVIEPROGRESSUPDATEPERCENT
                   TC_MOVIESCRAPDONTZEROSCRAP TC_MOVIESCRAPONLYPUTMOVIE TC_MOVIETOFILEONLYEXPORT TC_MOVIETOOLBOXUNINITIALIZED
                   TC_NEWMOVIEACTIVE TC_NEWMOVIEDONTASKUNRESOLVEDDATAREFS TC_NEWMOVIEDONTAUTOALTERNATES TC_NEWMOVIEDONTRESOLVEDATAREFS
                   TC_NEXTTIMEEDGEOK TC_NEXTTIMEIGNOREACTIVESEGMENT TC_NEXTTIMEMEDIAEDIT TC_NEXTTIMEMEDIASAMPLE
                   TC_NEXTTIMESYNCSAMPLE TC_NEXTTIMETRACKEDIT TC_NIL TC_NILCOMPONENTINSTANCE TC_NODATAHANDLER
                   TC_NODEFAULTDATAREF TC_NOERR TC_NOMEDIAHANDLER TC_NOMOVIEFOUND TC_NONMATCHINGEDITSTATE
                   TC_NORECORDOFAPP TC_PALINDROMELOOPTIMEBASE TC_PASTEINPARALLEL TC_PROGRESSOPADDMOVIESELECTION
                   TC_PROGRESSOPCOPY TC_PROGRESSOPCUT TC_PROGRESSOPEXPORTMOVIE TC_PROGRESSOPFLATTEN TC_PROGRESSOPIMPORTMOVIE
                   TC_PROGRESSOPINSERTMOVIESEGMENT TC_PROGRESSOPINSERTTRACKSEGMENT TC_PROGRESSOPLOADMEDIAINTORAM
                   TC_PROGRESSOPLOADMOVIEINTORAM TC_PROGRESSOPLOADTRACKINTORAM TC_PROGRESSOPPASTE TC_PROGRESSPROCABORTED
                   TC_QTCBNEEDSRATECHANGES TC_QTCBNEEDSSTARTSTOPCHANGES TC_QTCBNEEDSTIMECHANGES TC_RALIASTYPE
                   TC_SHOWUSERSETTINGSDIALOG TC_SMCURRENTSCRIPT TC_SMSYSTEMSCRIPT TC_SMSYSTEMSCRIPT TC_SOUNDMEDIATYPE
                   TC_STALEEDITSTATE TC_TEXTMEDIATYPE TC_TIMEBASEAFTERSTOPTIME TC_TIMEBASEBEFORESTARTTIME
                   TC_TIMENOTINMEDIA TC_TIMENOTINTRACK TC_TRACKIDNOTFOUND TC_TRACKNOTINMOVIE TC_TRACKUSAGEINMOVIE
                   TC_TRACKUSAGEINPOSTER TC_TRACKUSAGEINPREVIEW TC_TRIGGERATSTART TC_TRIGGERATSTOP TC_TRIGGERRATECHANGE
                   TC_TRIGGERRATEEQUAL TC_TRIGGERRATEGT TC_TRIGGERRATEGTE TC_TRIGGERRATELT TC_TRIGGERRATELTE
                   TC_TRIGGERRATENOTEQUAL TC_TRIGGERTIMEBWD TC_TRIGGERTIMEEITHER TC_TRIGGERTIMEFWD TC_TRUE
                   TC_TXTPROCDEFAULTDISPLAY TC_TXTPROCDODISPLAY TC_TXTPROCDONTDISPLAY TC_UNKEEPINRAM TC_UNSUPPORTEDAUXILIARYIMPORTDATA
                   TC_USERDATAITEMNOTFOUND TC_USESTANDARDMOVIEPROGESSFUNCTION TC_VALIDINSTANCESEXIST TC_VIDEOMEDIATYPE
                   TC_WFFILENOTFOUND TERMINATE-MACPTRS-ON-QUIT THE-AEDESC THE-REPLY TIME-IN-INTERVAL TRAP-FLAG-ARG
                   T_ADDRESOURCE T_ADDUSERDATA T_ADDUSERDATATEXT T_CLOSEMOVIEFILE T_COMPONENTFUNCTIONIMPLEMENTED
                   T_CONVERTFILETOMOVIEFILE T_CONVERTMOVIETOFILE T_COPYMOVIESELECTIONGC
                   copyRecordHANDLETORECORDHANDLE copyRecordHANDLETORECORDPTR copyRecordPTRTORECORDHANDLE copyRecordPTRTORECORDPTR
                   T_COUNTCOMPONENTS T_COUNTUSERDATATYPE T_CREATEMOVIEFILEGC T_CUTMOVIESELECTIONGC T_DEACTIVATEGCOSPTR
                   T_DELETEMOVIEFILE T_DETACHRESOURCE T_DISPOSEFILEREFNUMGCHandle T_DISPOSEHANDLE T_DISPOSEMOVIE
                   T_DISPOSEMOVIEFILEREFNUMGCHandle T_DISPOSERECORDHANDLE T_DISPOSERECORDPTR T_DISPOSETIMEBASE
                   T_DISPOSETRACKEDITSTATE T_DISPOSEUSERDATA T_DRAWMOVIEINGWORLD T_FILEREFNUMTOFILEREFNUMGCHandle
                   T_FINDNEXTCOMPONENT T_FSCLOSE T_FSMAKEFSSPECGCFORCREATING T_FSMAKEFSSPECGCFOROPENING T_GESTALT
                   T_GET1RESOURCE T_GET1RESOURCEGC T_GETCCURSORGC T_GETCICONGC T_GETCOMPONENTICONSUITEGC
                   T_GETCOMPONENTINFOGC T_GETCOMPONENTLISTMODSEED T_GETCOMPONENTVERSION T_GETGWORLD T_GETMEDIADATASIZE
                   T_GETMEDIAHANDLERDESCRIPTION T_GETMEDIATIMEANDDURATION T_GETMEDIAUSERDATA T_GETMOVIEACTIVE
                   T_GETMOVIEACTIVESEGMENT T_GETMOVIEBOUNDSRGNGC T_GETMOVIEBOXGC T_GETMOVIECLIPRGNGC T_GETMOVIEDATASIZE
                   T_GETMOVIEDISPLAYCLIPRGNGC T_GETMOVIEDURATION T_GETMOVIEFSSPECGC T_GETMOVIEGWORLD T_GETMOVIEINDTRACK
                   T_GETMOVIEMATRIXARRAY T_GETMOVIEMATRIXGC T_GETMOVIENEXTINTERESTINGTIME T_GETMOVIEPICT
                   T_GETMOVIEPICTGC T_GETMOVIEPOSTERPICTGC T_GETMOVIEPOSTERTIME T_GETMOVIEPREFERREDRATE T_GETMOVIEPREFERREDVOLUME
                   T_GETMOVIEPREVIEWMODE T_GETMOVIEPREVIEWTIME T_GETMOVIERATE T_GETMOVIESELECTION T_GETMOVIETIMEANDDURATION
                   T_GETMOVIETIMEANDRATE T_GETMOVIETIMEBASE T_GETMOVIETIMERECORDGC T_GETMOVIETIMESCALE T_GETMOVIETIMEVALUE
                   T_GETMOVIETRACK T_GETMOVIETRACKCOUNT T_GETMOVIEUSERDATA T_GETMOVIEVOLUME T_GETNEXTUSERDATATYPE
                   T_GETPIXPATGC T_GETPOSTERBOXGC T_GETRECORDHANDLECONTENTS T_GETRECORDPTRCONTENTS T_GETTIMEBASEFLAGS
                   T_GETTRACKDATASIZE T_GETTRACKENABLED T_GETTRACKID T_GETTRACKMEDIA T_GETTRACKMOVIEBOUNDSRGNGC
                   T_GETTRACKTIMEANDDURATION T_GETTRACKUSERDATA T_GETUSERDATA T_GETUSERDATAITEM T_GETUSERDATATEXT
                   T_GOTOBEGINNINGOFMOVIE T_GOTOENDOFMOVIE T_HANDLETOGCHandle T_ISMOVIEDONE T_ISVISUALMEDIATYPE
                   T_LOADMOVIEINTORAM T_MAKEGCOSPTR T_MATRIXARRAYTOMATRIXRECORD T_MATRIXRECORDTOMATRIXARRAY
                   T_MCIDLE T_MCISPLAYEREVENT T_MOVIESTASK T_NEWALIAS T_NEWALIASGC T_NEWCOMPONENTDESCRIPTIONGCHandle
                   T_NEWCOMPONENTDESCRIPTIONGCPtr T_NEWCOMPONENTDESCRIPTIONPTR T_NEWGWORLDGC T_NEWHANDLE
                   T_NEWHANDLEGC T_NEWMENUGC T_NEWMOVIEFROMDATAFORKGC T_NEWMOVIEFROMFILEGC T_NEWMOVIEFROMHANDLEGC
                   T_NEWMOVIEFROMSCRAPGC T_NEWMOVIEGC T_NEWMOVIETRACK T_NEWPIXPATGC T_NEWPTR T_NEWPTRGC newRecordGCHandle
                   newRecordGCHandleCLEAR newRecordGCPtr newRecordGCPtrCLEAR newRecordHANDLE newRecordHANDLECLEAR
                   newRecordPTR newRecordPTRCLEAR T_NEWRGN T_NEWRGNGC T_NEWTIMEBASEGC T_NEWTRACKMEDIA
                   T_NEWUSERDATA T_NEWUSERDATAFROMHANDLE T_OPENCOMPONENTGC T_OPENDEFAULTCOMPONENTGC T_OPENMOVIEFILE
                   T_PASTEMOVIESELECTION T_PREROLLMOVIE T_PTRTOGCPtr T_PUTMOVIEONSCRAP T_PUTUSERDATAINTOHANDLE
                   T_REMOVERESOURCE T_REMOVEUSERDATA T_REMOVEUSERDATATEXT T_SETMOVIEACTIVE T_SETMOVIEACTIVESEGMENT
                   T_SETMOVIEBOX T_SETMOVIECLIPRGN T_SETMOVIEDISPLAYCLIPRGN T_SETMOVIEGWORLD T_SETMOVIEMATRIX
                   T_SETMOVIEMATRIXFROMARRAY T_SETMOVIEPOSTERTIME T_SETMOVIEPREFERREDRATE T_SETMOVIEPREFERREDVOLUME
                   T_SETMOVIEPREVIEWMODE T_SETMOVIEPREVIEWTIME T_SETMOVIERATE T_SETMOVIESELECTION T_SETMOVIETIME
                   T_SETMOVIETIMESCALE T_SETMOVIETIMEVALUE T_SETMOVIEVOLUME T_SETPOSTERBOX T_SETRECORDHANDLECONTENTS
                   T_SETRECORDPTRCONTENTS T_SETTIMEBASEFLAGS T_SETTRACKENABLED T_SETUSERDATAITEM T_SHOWMOVIEPOSTER
                   T_SHOWMOVIEPOSTERINGWORLD T_STANDARDGETFILEPREVIEWGC T_STARTMOVIE T_STOPMOVIE T_UNIQUE1ID
                   T_UPDATEMOVIE T_WRITERESOURCE UPDATE-CLOCK-OFFSETS USEMOVIEDRAWFUNCTION VARIABLE-RECORD-TABLE WHEN-ERROR-SENDTOLOG
                   WITH-MOVIE-ACTIVE WITH-TRACK-IDENTIFIER WITHOPENRESOURCEFILE WITHRESOURCEFILE XENOID-TYPEDEF-NUM)

                  ("Patches to MCL"
                   *ACTIVE-MOVIE-CONTROLLERS* *ACTIVE-MOVIES-WITHOUT-CONTROLLERS* IS-MOVIE-CONTROLLER-EVENT
                   MOVIES-TASK)

                  ("SK8Script"
                   !*INVALIDCPUINSTRCACHE* !*SUPRESSCPUINSTRCACHEFLUSH* !*WARNBEFORECLOSINGUNACTIVATED* !BUILD-SK8-ERROR-HIERARCHY-AND-TABLE
                   !GET-SYM !PRINTMAYBEESCAPEDCHAR !UM $BASIC-SK8-ERROR-HIERARCHY $COMPILATION-PARENTS $KERNEL-ERROR-SK8-EQUIVALENTS
                   $MCL-CONDITION-HIERARCHY $UNDEFINEDHANDLER-PARENTS $UNKNOWN-PARENTS *A-VIRTUAL-COLLECTION-CLASS-WRAPPER*
                   *CHARACTER-NAMES* *DEVELOPER-LISTENER* *DRAGGING-FROM-EXPRWATCHER-PICKER* *MAX-VIRTUAL-COLLECTION-SIZE*
                   *MOUSEDOWN-IN-EXPRWATCHER-PICKER* *NUMBER-PUNCTUATIONS* *PARAGRAPH-DELIMITER* *SPECIALSTRINGCHARESCAPES*
                   *SPECIALSTRINGCHARS* *USER-MENUBAR-HIDDEN?* *USER-MENUBAR-OBJ* *WORD-DELIMITERS* BRING-UP-RUNNING-HANDLER
                   BRING-UP-RUNNING-LFUN-IF-POSSIBLE BUILD-LINEAR-PICKER-STRINGS COMPUTE-RUNTIME-EXPRESSION-STRING
                   COMPUTE-RUNTIME-EXPRESSION-VALUE-AND-STRING CONTAINSQ DEFINITELY-RECOVER-LIST DO-WATCHER-TOGGLE
                   EDITORFIELD-FROM-MENUITEM EDITORWINDOW-FROM-MENUITEM ENABLE-IF-EDITORFIELD-GOING-AND-NOT-IN-ERROR
                   ENABLE-IF-EDITORFIELD-STOPPED-AND-NOT-IN-ERROR ENDSWITH ENDSWITHQ ETLENGTH EXPRWATCHER-ASSOCIATED-HANDLEREDITTEXT
                   FCNINEDITOR? FIND-ITEM-END FIND-ITEM-START GET-ITEM-FROM-STRING HOOK-UP-EDITORSPLITTER
                   IGNORE-ERRORS IGNORE-SK8-MULTIVALS INDIRECTTEXTMAPACTUALBASETEXTANDRANGE INDIRECTTEXTMAPACTUALBASETEXTANDRANGEFORMODS
                   INFOSTRINGFORIDENTIFIER INSERTINTOVECTOR KILLHANDLER MAKE-LINEAR-PICKER-TEXT MAYBE-RECOVER-LIST
                   MOUSEEVENT-IN-WATCHER-DIVIDER? NEW-MEM NEWANONYMOUS POSITION PRINTARGSNICELY PRINTESCAPEDCHAR
                   PRINTESCAPEDSTRING RECOMPUTELOCALSUSED REMOVESTRINGSUBSEQUENCE REMOVEVECTORSUBSEQUENCE
                   REPLACESTRINGSUBSEQUENCE SCRIPT-EDITOR-FIND-WHO-IMPLS SCRIPT-EDITOR-FIND-WHO-REFS SCRIPTEDITOR-VERSIONMENU
                   SCRIPTVERSIONMENU-VERSIONITEMS SETUP-EXPRESSIONWATCHER-ITEMS SHIFTVECTOREND SK8-DESTRUCTURING-BIND
                   SK8-DESTRUCTURING-SETF SK8-MULTIVALS-SEQUENCE SK8-MULTIVAL-BIND SK8-MULTIVAL-SETF SK8-RETURN-NOTHING
                   SK8-MULTIVALS SK8-MULTIVALS-FROM-LIST SK8TOPLEVEL STARTSWITH STARTSWITHQ STRING-OUTPUT-STREAM
                   TEXTTYPEFILTEREDCOLLECTION_INSERTER TOGGLE-SCRIPT-WACTHINGMENUITEM TOSK8MEM UNREADABLEENDCHARACTER
                   UNREADABLESTARTCHARACTER UPDATE-SCRIPTEDITORVERSIONMENU UPDATEFORCHANGEDLOCALS UPDATETEXTDEPENDENTSTATES
                   UPDATEVECTORDEPENDENTSTATES WARNANDKILLHANDLER WATCHERVOFFSET WINDOW-CLOSE WINDOW-SELECT
                   WINDOWKEYTARGET-FROM-MENUITEM WITH-LOCALSVALUES-ALIST WITH-RECOVERABLE-LIST WITH-TEMP-INSTANCE
                   WITH-TEMP-VIRTUAL-COLLECTION WITHRANGESTATESINLIST WRITEINFOFORIDENTIFIER)

                  ("store"
                   *ACTORS-CONTAINED-IN-OTHER-PROJECTS* *TOPLEVEL-ACTORS* CACHEACTORWINDOWS
                   FINALIZEENVIRONMENT HELPFINDMYCHILD INITIALIZEMENUBARS LOAD-CLOS-WINDOW PACKAGE PLEASEFINDMYCHILD
                   RESTORE-PIXMAP-DATA SAVE-PIXMAP-RESOURCE)

                  ("User Interface"
                   %STACKWATCHER-UPDATER *VOWELS* ABC->X1X2 ACTORSINREGION ADD-SELECTEDITEM ALIGN-SELECTION
                   BOTTOM-MOST BREAK-INTO-WORDS CALCLAYOUTPARAMETERS CARTESIAN->POLAR D2PJ->C1C2 D2PSI->C1C2
                   DEEPELCHECK DEEPOBJECTCLEAR DEINSTALL-STACKWATCHER-UPDATER DONEWPROJECTTHING DOPROPERTYDROP
                   DRAWPOINTLIST DRAWREVEALEDSHAPES DRAWSCALEDSHAPES EVENTH->MARKPOS FASTTABLEPICKER-DRAW
                   FILENAMEFROMSTRING FIND-INDICES GETCONTAINERS GETFREEHANDFROMUSER GETHANDLERS GETLINEFROMUSER
                   GETPOLYGONFROMUSER GETPROPERTIES GETPROPSVALUE GETREGULARPOLYGONFROMUSER GETSHORTPROPSVALUE
                   GETSYMEGONFROMUSER GRAPHICHANDLERS GRAPHICPROPERTIES IGNORE-SENSITIVITY-POINT-IN-WHICH-ACTOR
                   IGNORE-SENSITIVITY-POINT-IN-WHICH-NODE INSTALL-STACKWATCHER-UPDATER LEFT-MOST LIST-MATCHES-LIST
                   LIST-MATCHES-ROW LOGSLOTS MAKE-DOTS-REGION MAKEPOLYPOINTSLIST MAKESIMIPOINTSLIST MAKING-TABLEPICKER-DIRTY
                   MAKING-TABLEPICKER-DIRTY-FOR-SELECTION MAP-DIMS MAP-ITEMS MAP-ROWS MAX-LIST-LENGTH NUM-ITEMS-SHOWN
                   OKCHARS PARENTSHANDLERS PARENTSPROPERTIES PATH-TO-ROOT PATHNAME-PARENT-DIRECTORY PJ->P
                   POINTSTOREGION POLAR->CARTESIAN POPSTACKWATCHER PP->D PP->D2 PP->S PPD->P PPD2->R PPP->CLOCKWISE?
                   PPP->INSIDE? PPP->P PPPP->P PPPP->R PS->I PSI->P PUSHINTOSTACKWATCHER REGIONINREGION RIGHT-MOST
                   ROTATEPOINTLIST SELECT-ROW SELECT-ROWS-IF SET-ITEM SET-SELECTION SET-TUPLE SHOW-RANGE
                   SIDESFROMKEYS SIMPLEOBJECTCLEAR SINGLE-SELECT SK8-TABLEPICKER-AREF STACKWATCHER-UPDATE-INTERVAL
                   SWITCH-TO-FILE SWITCH-TO-RESOURCES SWITCH-TO-RESTYPE TOP-MOST TUPLE-P TUPLE-SELECTED UNDOSLOTSET
                   WITHZOOMINGBOUNDS XOR XSI->Y)

                  )
#|
	Change History (most recent last):
	167	 1/18/95	rod     	
	168	 1/21/95	sidney  	
	169	 2/10/95	dy      	tweaks to invocations of macros that reduce to make-terminable-macptr
	170	 2/10/95	sidney  	
	171	 2/14/95	sidney  	
	172	 3/ 9/95	dy      	remove T_ from  T_copyRecordxxx macro names
	173	 3/11/95	dy      	
	174	 3/13/95	dy      	
	175	 3/13/95	dy      	
	2  	 5/ 7/96	sidney  	Changes for new object system
	3  	 5/10/96	sidney  	
	4  	 7/ 7/96	sidney  	changes for native PPC build
	5  	 2/27/97	Hernan  	
|# ;(do not edit past this line!!)
