;;; SK8 © 1997 by Apple Computer, Inc.
;;; The code in this file is protected under the terms of the current SK8 License.
;;; For information on this license, see http://sk8.research.apple.com
;;; Apple Computer, Inc. -- Apple Research Laboratories


;; Exports updated 12-16-94   1:59 pm

(in-package :SK8)

(SK8-declare-syms :SK8 :special

                  ("2-d graphics"
                   menubar function stream abort condition function error
                   ABOUTBOXBUTTON ABOUTBOXCLOCK ABOUTBOXPICT ABOUTBOXTEXT ABOUTBOXTITLE ABOUTBOXVERSION ACTOR
                   ACTORMIXIN ACTORTOTEXTTRANSLATOR ANIMATEDCLOCK ANIMATEDCURSOR ANIMATEDERRORCURSOR ARROW
                   ARROWCURSOR BEVELRENDERER BLACK BLACKTORED BLEND BLENDYELLOW BLUE BLUEBLEND BLUECROSSES
                   BLUECROSSESRSRC BLUEPLAID BLUEPLAIDRSRC BLUESQUARES BLUESQUARESRSRC BLUETUNNEL BOUNDEDBYCONTENTSMIXIN
                   BRICKWALL BRICKWALLRSRC BROWN BWPATTERN1 BWPATTERN10 BWPATTERN11 BWPATTERN12 BWPATTERN13
                   BWPATTERN14 BWPATTERN15 BWPATTERN16 BWPATTERN17 BWPATTERN18 BWPATTERN19 BWPATTERN2 BWPATTERN20
                   BWPATTERN21 BWPATTERN22 BWPATTERN23 BWPATTERN24 BWPATTERN25 BWPATTERN26 BWPATTERN27 BWPATTERN28
                   BWPATTERN29 BWPATTERN3 BWPATTERN30 BWPATTERN31 BWPATTERN32 BWPATTERN33 BWPATTERN34 BWPATTERN35
                   BWPATTERN36 BWPATTERN37 BWPATTERN38 BWPATTERN39 BWPATTERN4 BWPATTERN40 BWPATTERN41 BWPATTERN42
                   BWPATTERN43 BWPATTERN44 BWPATTERN5 BWPATTERN6 BWPATTERN7 BWPATTERN8 BWPATTERN9 BWPATTERNTOPATTRANSLATOR
                   CHECKBOX CHECKBOXCHECK CLIPBOARD CLOSEBOXICON CLOSEBOXRENDERER CLOSEIRIS CLOSEVENETIANS
                   COLORCURSORRSRC COLORCURSORRSRCTOCRSRTRANSLATOR COLORPATTERNTOPPATTRANSLATOR COMPLEXGRADIENT
                   COMPLEXRGBCOLOR CONNECTOR CONTENTSPROPERTYCOLLECTION CRUMPLEDPAPER CRUMPLEDPAPERRSRC CURSORCLOSEHAND
                   CURSORCROSSHAIR CURSORCROSSHAIRDEEP CURSORHELP CURSORHSPLITTER CURSORMENU CURSOROPENHAND
                   CURSORPENCIL CURSORPOINTING CURSORPRESSING CURSORRSRCTOCURSTRANSLATOR CURSORSELECTIONCROSSHAIR
                   CURSORSELECTLASSO CURSORSELECTLASSODEEP CURSORSELECTRECT CURSORTEXTSTRING CURSORVSPLITTER
                   CURSORX CYAN DARKBLUE DARKBROWN DARKER DARKERFLOORTILE DARKGRAY DARKGRAYPATTERN DARKGREEN
                   DARKOAK DARKOAKPICT DARKORANGE DARKPURPLE DARKRED DARKYELLOW DESKTOPCOLOR DESKTOPPATTERN
                   DIRECTIONALCONNECTOR DRAGONSTAGEMODE DYNAMICRENDERER DYNAMICRENDERERACTORMIXIN EDITMENU
                   EDITMENUCLEAR EDITMENUCOPY EDITMENUCUT EDITMENUPASTE EDITTEXT EFFECT ERROR1CURSOR ERROR2CURSOR
                   ERROR3CURSOR ERROR4CURSOR ERROR5CURSOR ERROR6CURSOR ERROR7CURSOR ERRORCOLOR ERRORCOLORRSRC
                   FANHOUSEDOWN FANHOUSELEFT FANHOUSERIGHT FANHOUSEUP FILEMENU FILEMENUCLOSE FILEMENUQUIT
                   FINDERCLOSEDARROW FINDERCLOSEDARROWCICON FINDEREMPTYCLOSEDARROW FINDEREMPTYCLOSEDARROWCICON
                   FINDEREMPTYINBETWEENARROW FINDEREMPTYINBETWEENARROWCICON FINDEREMPTYOPENARROW FINDEREMPTYOPENARROWCICON
                   FINDERINBETWEENARROW FINDERINBETWEENARROWCICON FINDEROPENARROW FINDEROPENARROWCICON FLIPDOWN
                   FLIPLEFT FLIPRIGHT FLIPUP FLOORTILE FLOORTILERSRC GOLDMARBLE GOLDMARBLEPICT GOLDOAK GOLDOAKPICT
                   GRADIENT GRANITE GRANITEPICT GRAPHIC GRAY GRAYBUMPS GRAYBUMPSRSRC GRAYCRAGS GRAYCRAGSRSRC
                   GRAYGRID GRAYGRIDRSRC GRAYMIST GRAYMISTRSRC GRAYPATTERN GRAYSPLOTCH GRAYSPLOTCHRSRC GRAYSQUARES
                   GRAYSQUARESRSRC GRAYTONE05 GRAYTONE10 GRAYTONE15 GRAYTONE20 GRAYTONE25 GRAYTONE30 GRAYTONE35
                   GRAYTONE40 GRAYTONE45 GRAYTONE50 GRAYTONE55 GRAYTONE60 GRAYTONE65 GRAYTONE70 GRAYTONE75
                   GRAYTONE80 GRAYTONE85 GRAYTONE90 GRAYTONE95 GREEN GREENCRAGS GREENCRAGSRSRC GREENLINES
                   GREENLINESRSRC GREENSLASHES GRIDPAPER HATCH HIERARCHICALPICKER HIERARCHICALPICKERITEM
                   HIGHLIGHTED HIGHLIGHTICON HIGHLIGHTRENDERER IBEAMCURSOR ICONRSRCTOCICNTRANSLATOR ICONTEXTPICKER
                   IMAGERENDERER IMAGERENDERERTOCICNTRANSLATOR IMAGERENDERERTOIMAGERSRCTRANSLATOR IMAGERENDERERTOPATTRANSLATOR
                   IMAGERENDERERTOPICTTRANSLATOR INDIRECTTRANSLATOR INVERT LABEL LABELMENU LARGEBRICKWEAVE
                   LARGEBRICKWEAVERSRC LIGHTBLUE LIGHTBOARD LIGHTBOARDRSRC LIGHTBROWN LIGHTER LIGHTGRAY LIGHTGRAYPATTERN
                   LIGHTGREEN LIGHTORANGE LIGHTPURPLE LIGHTRED LIGHTYELLOW LINEDPAPER LINESEGMENT MACSYSTEMRGBCOLOR
                   MASK MASKEDACTOR MENU MENUBARCOLLECTION MENUBOXICON MENUBOXRENDERER MENUCOLLECTION
                   MENUITEM MENUSELECTMODE MENUSPACER METAL1 METAL2 MODALDIALOGMODE MUCHDARKER MUCHLIGHTER
                   MUCHLIGHTERWOODFLOOR MUDDY MUDDYRSRC MULTILINEPICKER MULTIOBJECTSTATECHECKBOX MULTIRENDERER
                   NONSKIDMETAL NONSKIDMETALRSRC OPENIRIS OPENVENETIANS ORANGE OVAL PATSTRETCHPIXELMAP PEN
                   PICKER PICKERCOLLECTION PICTFILEMEDIATOPICTFILETRANSLATOR PINK PINKMARBLE PINKMARBLEPICT
                   PIXELMAP POLYGON PRISONBARS PURPLE PURPLEMARBLE PURPLEMARBLERSRC PUSHDOWN PUSHLEFT PUSHRIGHT
                   PUSHUP QDPICTURETOPICTTRANSLATOR RADIOBUTTON RADIOBUTTONBUTTON RADIOBUTTONHIGHLIGHT RANCID
                   RANCIDRSRC RANDOMROWS RANDOMTILE RECTANGLE RECTANGLETOPICTTRANSLATOR RED REDBLEND REDCROSSES
                   REDCROSSESRSRC RENDERER RESIZEBOXICON RESIZEBOXRENDERER RESIZESCONTENTSMIXIN RGBCOLOR
                   ROUNDRECT SAFEINPUTPORT SAFEOUTPUTPORT SCRIPTEDITTEXT SCROLLER SCROLLERARROW SCROLLERBODY
                   SCROLLERBODYCOLOR SCROLLERDOWNARROW SCROLLERDOWNICON SCROLLERDOWNPRESSEDICON SCROLLERDOWNPRESSEDRENDERER
                   SCROLLERDOWNRENDERER SCROLLERHTHUMBICON SCROLLERHTHUMBRENDERER SCROLLERLEFTICON SCROLLERLEFTPRESSEDICON
                   SCROLLERLEFTPRESSEDRENDERER SCROLLERLEFTRENDERER SCROLLERPATTERN SCROLLERRIGHTICON SCROLLERRIGHTPRESSEDICON
                   SCROLLERRIGHTPRESSEDRENDERER SCROLLERRIGHTRENDERER SCROLLERTHUMB SCROLLERUPARROW SCROLLERUPICON
                   SCROLLERUPPRESSEDICON SCROLLERUPPRESSEDRENDERER SCROLLERUPRENDERER SCROLLERVTHUMBICON
                   SCROLLERVTHUMBRENDERER SERIALTILE SHAPESTAIN SIMPLEMENUBAR SK8ABOUTBOX SK8CLIPBOARD SK8PAINTING
                   SK8SPLASHPICT SKETCHRENDERER SLIDEDOWN SLIDELEFT SLIDER SLIDERIGHT SLIDEUP SLIGHTLYDARKER
                   SLIGHTLYLIGHTER SMALLBRICKWEAVE SMALLBRICKWEAVERSRC SMALLPURPLEWEAVE SMALLPURPLEWEAVERSRC
                   SMOOTHEDGRAYBUMPS SMOOTHEDGRAYBUMPSRSRC SOUNDRSRCTOSNDTRANSLATOR SOUNDTOSNDTRANSLATOR
                   SPLITTER STAGE STANDARDCURSOR STARBURST STRANGEBARS STRINGTOTEXTTRANSLATOR STYLEDPICKER
                   SUNSET SWATCHTEMPSNAPSHOTCOLOR SWATCHTEMPSNAPSHOTMEDIA TAN TBBROWSE TBCENTER TBCOLLAPSE
                   TBCOMPACT TBCONNECTOR TBCONTROLPANEL TBDEPTHTITLE TBDEPTHVIEWER TBDISPLAYITEM TBDRAWTREE
                   TBEDIT TBFLASH TBHSCROLLER TBMENUBAR TBPREFERENCES TBPREFSCANCEL TBPREFSDEPTH TBPREFSDEPTHGETTER
                   TBPREFSDRAW TBPREFSFILTER TBPREFSFILTERGETTER TBPREFSITEM TBPREFSITEMGETTER TBPREFSITEMSIZE
                   TBPREFSITEMSIZEGETTER TBPREFSITEMVSEPARATION TBPREFSITEMVSEPARATIONGETTER TBPREFSLAYOUT
                   TBPREFSLAYOUTTITLE TBPREFSMENUITEM TBPREFSRELATION TBPREFSRELATIONGETTER TBPREFSROOT TBPREFSROOTGETTER
                   TBPREFSSETUP TBPREFSSETUPTITLE TBPREFSTITLEBAR TBRELATIONTITLE TBRELATIONVIEWER TBREROOT
                   TBRESIZER TBROOTTITLE TBROOTVIEWER TBSELECTIONMENU TBSELECTIONTITLE TBSELECTIONVIEWER
                   TBSETDEPTH TBSETFILTER TBSETRELATION TBSETROOT TBSHOWOVERVIEWER TBSKETCHRENDERER TBTOOLSMENU
                   TBVSCROLLER TEXTFIELD TEXTLIST TEXTLISTPICKER TEXTLISTTITLEBAR TEXTLISTVSCROLL TEXTTOTEXTTRANSLATOR
                   TFSCROLLER TRANSLATOR TRANSLUCENCYHELPER TRANSLUCENT TRANSPARENT TRASHEMPTYICON TRASHEMPTYRENDERER
                   TRASHFULLICON TRASHFULLRENDERER TREEBROWSER TREEBROWSERTITLEBAR TREEDRAWING TREEDRAWINGCONTAINER
                   TREEHIGHLIGHTER TREEMENU TREEOVERVIEWER TREEOVERVIEWERTITLEBAR TREEVIEWER UIRECTANGLEINBEVEL
                   UIRECTANGLEOUTBEVEL VISUALEFFECT VOMIT WALNUTSWIRLS WALNUTSWIRLSRSRC WALNUTWAVES WALNUTWAVESRSRC
                   WATCHCURSOR WELCOMEMAT WELCOMEMATRSRC WHITE WHITEDESKTOPPATTERN WHITEDESKTOPPATTERNRSRC
                   WHITEGRID WHITEGRIDRSRC WINDOWSMENU WINDOWSMENUITEM WIPEDOWN WIPELEFT WIPERIGHT WIPEUP
                   WOODFLOOR WOODFLOORRSRC WOODSHINGLERSRC WOODSHINGLES YELLOW ZOOMBOXICON ZOOMBOXRENDERER
                   ZOOMIN)

                  ("Function Library"
                   DATE DATETIME DateTimeIndirect TODAY NOW)

                  ("macframes"
                   OBJECT SK8 SYMBOL CHARACTER NUMBER COMPLEX REAL FLOAT INTEGER ARRAY VECTOR STRING LIST
                   QUICKTIMERENDERER DYNAMICRENDERERACTORMIXIN QUICKTIMEMOVIETOWHATEVERTRANSLATOR QUICKTIMEMOVIETOMOOVTRANSLATOR
                   QUICKTIMEMOVIETOAIFFTRANSLATOR QUICKTIMERENDERERTOWHATEVERTRANSLATOR QUICKTIMERENDERERTOMOOVTRANSLATOR
                   QUICKTIMERENDERERTOAIFFTRANSLATOR QUICKTIMEPICTRENDERER QUICKTIMEPICTRENDERERMEDIA SK8APPLICATIONFILE
                   ABSTRACTCLOCK APPLESCRIPT APPLESCRIPTRESULT EMPTYAPPLESCRIPTRESULT AEDESCPICTURE AEDESCALIAS
                   QUICKTIMEMOVIETORESOURCETRANSLATOR QUICKTIMEMOVIETOMOOVRESOURCETRANSLATOR QUICKTIMEMOVIETOFILETRANSLATOR
                   QUICKTIMEMOVIETOMOOVFILETRANSLATOR QUICKTIMEMOVIETOAIFFFILETRANSLATOR QUICKTIMERENDERERTORESOURCETRANSLATOR
                   QUICKTIMERENDERERTOMOOVRESOURCETRANSLATOR QUICKTIMERENDERERTOFILETRANSLATOR QUICKTIMERENDERERTOAIFFFILETRANSLATOR
                   QUICKTIMERENDERERTOMOOVFILETRANSLATOR QUICKTIMERENDERER QUICKTIMESIMPLEPLAYER QUICKTIMETRACKCOLLECTION
                   QUICKTIMETRACK QUICKTIMEMEDIA AETARGET APPLEEVENT APPLEEVENTAPPLICATION APPLEEVENTRECEIVER
                   BIGFLOAT BIGINTEGER BLACKPATTERNRSRC BWPATTERN BYTESTREAM CLOCK COLLECTION COLORPATTERN
                   COLORTABLE CONSTRAINT CURSORRSRC DARKGRAYPATTERNRSRC DEVICE EVENTMODE EVENTTRACK FILE
                   DIRECTORYNICKNAME FILEMEDIA FONT FOREIGNDEFTRAP FRAMESEQUENCE GRAPHICCONSTRAINT
                   GRAYPATTERNRSRC HANDLER ICONRSRC INPUTOUTPUTPORT INPUTPORT KEYBOARD LAYOUTCONSTRAINT LIGHTGRAYPATTERNRSRC
                   LISTPAIR MECHANICALCONSTRAINT MEDIA MINUTESCLOCK MODALSOUND MODALSOUNDRSRC MODELESSSOUND
                   MODELESSSOUNDRSRC MODEM MONITOR MOUSE MOVIEFRAMERENDERER MOVIEFRAMERENDERERMEDIA MOVIERECTANGLE
                   MOVIERSRCTOMOVIERECTANGLETRANSLATOR MOVIERSRCTOQUICKTIMEMOVIETRANSLATOR OUTPUTPORT PICTFILEMEDIA
                   POINTER PORT PRINTER PROXY QDPICTURE QDPICTURESEQUENCE QUICKTIMEMOVIE
                   QuickTimeCallBack
                   QuickTimeCallBackAtTime
                   QuickTimeCallBackAtRate
                   QuickTimeCallBackAtTimeJump
                   QuickTimeCallBackAtExtremes
                   QuickTimeCallBackForRenderer
                   QuickTimeTimeBase
                   QuickTimeComponentInstance
                   QuickTimeClockComponentInstance
                   REALTIMECLOCK REPEATINGCLOCK RESOURCE ROOTDIRECTORY ROOTDIRECTORYNICKNAME SECONDSCLOCK
                   SK8DIRECTORY SK8DIRECTORYNICKNAME SLAVECLOCK SMALLFLOAT SMALLINTEGER SOUND SOUNDCHANNEL SOUNDRSRC
                   SPECIALSTORAGEMIXIN STORAGEDEVICE SYSTEM SYSTEMCLOCK TAGMIXIN TEXT TEXTSTREAM THISAPPLICATIONAETARGET
                   WHITEPATTERNRSRC ZOOMDOWNSOUND ZOOMDOWNSOUNDRSRC ZOOMUPSOUND ZOOMUPSOUNDRSRC)

                  ("SK8Script"
                   DISPOSEDOBJECTERROR EVENTMODEERROR PROJECTIMPROPERLYCLOSEDERROR UNKNOWNERROR COMPILATIONERROR
                   UNBOUNDVARIABLEERROR UNDEFINEDHANDLERERROR INCORRECTARGUMENTSERROR INCORRECTSUBSCRIPTSERROR
                   INDEXOUTOFBOUNDSERROR COERCIONERROR NOTAHANDLERERROR CANTCHANGECONSTANTERROR DIVISIONBYZEROERROR
                   ARITHMETICOVERFLOWERROR OSHEAPFULLERROR FILEMEMORYFULLERROR SK8HEAPFULLERROR STACKOVERFLOWERROR
                   NUMBERMEMORYFULLERROR FILENOTFOUNDERROR ENDOFFILEERROR ILLEGALFILENAMEERROR IODRIVERERROR DISKERROR
                   CLOCKERROR SERIALPORTERROR APPLETALKERROR SCRAPMANAGERERROR MEMORYMANAGERERROR RESOURCEERROR
                   SOUNDMANAGERERROR PPCTOOLBOXERROR APPLEEVENTERROR
                   INDIRECTCHARACTERVECTOR INDIRECTLINEVECTOR INDIRECTPARAGRAPHVECTOR INDIRECTWORDVECTOR
                   ACTORCOLLECTION ALIASEDCOLLECTION INDIRECTCOLLECTION ARGUMENTTYPEMISMATCHERROR 
                   ARITHMETICERROR BRINGUPHANDLER BYTE
                   CHOOSERESPONSE COMPONENTMANAGERERROR CONDITIONRESPONSE
                   CONTAINERCOLLECTION DEEPCOLLECTION DEEPTYPEFILTEREDCOLLECTION DISPLAYERRORMESSAGE EDITORSPLITTER
                   EDITTEXTCOLLECTION ENUMERATEDTYPE EXITMODEWITHERROR EXPRESSIONWATCHEREXPRTITLE EXPRESSIONWATCHERFIELD
                   EXPRESSIONWATCHERHSPLITTER EXPRESSIONWATCHERHSPLITTERNUB EXPRESSIONWATCHERPICKER EXPRESSIONWATCHERRESIZER
                   EXPRESSIONWATCHERSCROLLER EXPRESSIONWATCHERVALTITLE EXPRESSIONWATCHERVSPLITTER FILEERROR
                   FILESYSTEMERROR FILTEREDCOLLECTION FOREIGNMEMORY GENERALERROR GENERALPROGRAMMATICERROR
                   IMAGECOMPRESSIONERROR INDIRECTTEXT INDIRECTTEXTVECTOR LINE LINEARPICKERSCROLLER LINEARPICKERTEXT
                   LINEARTEXTPICKER LOGERRORMESSAGE MAYBEOPENPROJECT MEMHANDLE MEMORYFULLERROR MEMPOINTER
                   MOVIECONTROLLERERROR MOVIEDATAHANDLERERROR MOVIEERROR MOVIESEQUENCEGRABBERERROR NONNEGATIVEINTEGER
                   NORESPONSE OBJECTTABLE PARAGRAPH POSITIVEINTEGER PROCESSEDCOLLECTION PROGRAMMATICERROR
                   PROPERTIESFORMODSCOLLECTION PROPERTYCOLLECTION PROPERTYTYPEMISMATCHERROR RANGECOLLECTION
                   RUNTIMEEXPRESSIONWATCHER SCRIPTABORTBUTTON SCRIPTALLPURPOSETOGGLER SCRIPTCONTEXTMENU SCRIPTCONTEXTMENUITEM
                   SCRIPTEDITCLEAR SCRIPTEDITCLOSE SCRIPTEDITCOPY SCRIPTEDITCUT SCRIPTEDITMENU SCRIPTEDITORBUTTON
                   SCRIPTEDITORRESIZER SCRIPTEDITORWINDOW SCRIPTEDITPASTE SCRIPTEDITPRINT SCRIPTEDITSELECTALL
                   SCRIPTEDITSTACKWINDOWS SCRIPTEDITUNDO SCRIPTEXPRESSION SCRIPTFIELD SCRIPTGLOBALS SCRIPTGOBUTTON
                   SCRIPTHSCROLLER SCRIPTLOCALS SCRIPTMENU SCRIPTMENUVERSIONITEM SCRIPTRUNABORT SCRIPTRUNGO
                   SCRIPTRUNGOEND SCRIPTRUNGOHERE SCRIPTRUNINTO SCRIPTRUNMENU SCRIPTRUNRESTART SCRIPTRUNSKIP
                   SCRIPTRUNSTEP SCRIPTRUNSTOP SCRIPTRUNTRACE SCRIPTRUNTRACEINTO SCRIPTSTEPBUTTON
                   SCRIPTTOOLSADDPROPERTY SCRIPTTOOLSDELETE SCRIPTTOOLSEDITOTHER SCRIPTVERSIONACTIVATE SCRIPTVERSIONDELETE
                   SCRIPTVERSIONDELETEOTHERS SCRIPTVERSIONMENU SCRIPTVSCROLLER SCRIPTWATCHINGLOG SCRIPTWATCHINGMENU
                   SCRIPTWATCHINGON SCRIPTWATCHINGPOPUP SCRIPTWATCHINGSTACKWATCHER SCRIPTWATCHINGTRACE SCRIPTWINDOWBUTTONS
                   SCRIPTWINDOWMENUBAR SIMPLESTATERANGECOLLECTION SUPERTEXTTYPEFILTEREDCOLLECTION SYSTEMERROR
                   TABLE TABLEPAIR TEXTCHUNK TEXTCOLLECTION TEXTTYPEFILTEREDCOLLECTION TYPEFILTEREDCOLLECTION TYPEMISMATCHERROR
                   TYPETABLE UNKNOWNERROR VARCOLLECTION VARPANESPLITTER VIRTUALTYPE WORD)

                  ("User Interface"
                   ADDFUNCTIONDIALOGBOX ADDHANDLERDIALOGBOX ADDPARDBCANCEL ADDPARDBDOIT ADDPARDBHIGHLIGHTER
                   ADDPARDBTHEPARENTNAME ADDPARDBTHEPARENTNAMEGETTER ADDPARENTDIALOGBOX ADDPORTDIALOGBOX
                   ADDPROPERTYDIALOGBOX ADDVARIABLEDIALOGBOX AFDBADDFUNCTIONBUTTON AFDBCANCELADDFUNCTION
                   AFDBHIGHLIGHTER AFDBTHEFUNCTIONNAME AFDBTHEFUNCTIONNAMEGETTER ALIGNCARD ALRADIOBUTTON
                   ALRBBOTTOM ALRBHCENTER ALRBLEFT ALRBRIGHT ALRBTOP ALRBVCENTER APDBADDITBUTTON APDBADDLABEL
                   APDBCANCELBUTTON APDBOFLABEL APDBONAMERECT APDBPNAMERECT APDBPORTTYPEMENU APDBPORTTYPEMENUITEM
                   APDBTOTHELABEL BOOLEANPROPERTYEDITOR BOOLEANPROPERTYEDITORCHECK BROWSERCOMPONENT BROWSERMENUBAR
                   BROWSERPAPER BROWSERPAPERHIGHLIGHTERHALO BUILDSTANDALONECHECK BUILDSTANDALONEDIALOGBOX
                   BUTTONGRADIENTCOLOR CANCELOBJECTNAMEDIALOG COLORPICKER CONITEMDISPOSE CONSHOWOBJS CONSTANTDATARECT
                   CONSTANTSHEET CONSTANTSHEETPICKER CREATEOBJECTNAMEDIALOG CURSOR10OCLOCK CURSOR12OCLOCK
                   CURSOR1OCLOCK CURSOR3OCLOCK CURSOR4OCLOCK CURSOR6OCLOCK CURSOR7OCLOCK CURSOR9OCLOCK DATAOBJECT
                   DIALOGBOX DIALOGBOXBUTTON DIALOGBOXCANCELBUTTON DIALOGBOXDISPLAYEDITTEXT DIALOGBOXDISPLAYRECTANGLE
                   DIALOGBOXEDITTEXT DIALOGBOXHIGHLIGHTEDBUTTON DIALOGBOXHIGHLIGHTEDBUTTONINNARD DIALOGBOXLABEL
                   DISTRIBUTECARD DISTWITHSIZE DLBOTH DLHONLY DLRADIOBUTTON DLVONLY DRAWTOOL DRAWTOOLPALETTE
                   DYNAMICPICKERMENUITEM EDITHANDLERMENUITEM FCDESKTOPBUTTON FCOPENBUTTON FDBACTIONLABEL
                   FDBCANCELBUTTON FDBFILECHOOSER FILECHOOSER FILEDIALOGBOX FILELIST FILEMENUITEM FILEPOPUP
                   FILTEREXPRQUERYFIELD FOURNUMBERPROPERTYEDITOR FUNCTIONDATARECT FUNCTIONSHEET FUNCTIONSHEETPICKER
                   FUNITEMDISPOSE GETCOLORCANCELBUTTON GETCOLORCOLORPICKER GETCOLORDIALOGBOX GETCOLORLABEL
                   GETCOLORMENU GETCOLORMENUITEM GETCOLORNAMEDISPLAYER GETCOLOROKBUTTON GETFROMUSERBUTTON
                   GETFROMUSERDIALOGBOX GETFROMUSERDIALOGCANCELBUTTON GETFROMUSERDIALOGTEXTLIST GETFROMUSERDIALOGYESBUTTON
                   GETFROMUSERMENUITEM GETFROMUSERPOPUP GETNEWSTRINGDIALOGBOX GETNEWSTRINGDIALOGCANCELBUTTON
                   GETNEWSTRINGDIALOGDISPLAYER GETNEWSTRINGDIALOGGETTER GETNEWSTRINGDIALOGHIGHLIGHTER GETNEWSTRINGDIALOGYESBUTTON
                   GETOBJECTFIELD GETOBJECTFIELDGETFROMUSERBUTTON GETOBJECTFIELDSIMPLETEXT GETOBJECTFIELDTEAROFFRECT
                   GFUBUTTONARROW GLOBALDATARECT HALO HANDLERDATARECT HANDLERLIST HANDLERPICKER HANDLERPICKERITEMDISPOSE
                   HANDLERPICKERNEWMENUITEM HANDLERPICKERSHOWPRIVATE HANDLERPICKERSPACERMENUITEM HANDLERPICKERVIEWTYPEMENUITEM
                   HANDLERPICKERVIEWTYPEMENUITEMALL HANDLERPICKERVIEWTYPEMENUITEMGRAPHIC HANDLERPICKERVIEWTYPEMENUITEMINHERITED
                   HANDLERPICKERVIEWTYPEMENUITEMLOCAL HANDLERPICKERVIEWTYPEMENUITEMPARENTS HANDLERSHEET HANDLERSHEETPICKER
                   HANDLERVIEWER HANDLERVIEWERTEXT HANDLERWATCHINGCLEARBPBUTTON HANDLERWATCHINGCOMPONENT
                   HIERARCHICALOBJECTLIST HIERARCHICALOBJECTPICKER INVERSEBUTTONGRADIENTCOLOR LAYOUTDIALOGBOX
                   LAYOUTDIALOGBOXCARD LDAPPLYBUTTON LDCANCEL LDCHECKBOX LDCHOOSEFUNCTION LDITEMLABEL LDNUMBEREDITOR
                   LDRELATIVELABEL LDRELATIVETO LDSOLABEL MBAREDMENU MBAREDMENUBAR MBAREDMENUBARDISPOSE MBAREDMENUBARMENUSELECT
                   MBAREDMENUBARNEW MBAREDMENUBARSPACE MBAREDMENUBARUPDATE MBAREDMENUDISPOSE MBAREDMENUMENUSELECT
                   MBAREDMENUNEW MBAREDMENUSPACE MBAREDMENUUPDATE MENUBAREDITORPICKER MENUEDITEMMENUSELECT
                   MENUEDITEMSPACE MENUEDITEMUPDATE MENUEDITORPICKER MENUFORCONPICKERS MENUFORFUNPICKERS
                   MENUFORHANDLERPICKERS MENUFORHIERARCHICALOBJECTPICKERS MENUFORMENUEDITORPICKERS MENUFORMENUEDITORPICKERSDISPOSEMENUITEM
                   MENUFORMENUEDITORPICKERSNEWMENUITEM MENUFOROBJECTPICKERS MENUFOROBJECTPICKERSITEMDISPOSE
                   MENUFOROBJECTPICKERSNEWMENUITEM MENUFORPROPERTYPICKERS MENUFORVALUEEDITORPICKERS MENUFORVARPICKERS
                   MESSAGEBOX MESSAGETOUSERDIALOGBOX MESSAGETOUSERDIALOGBOXBUTTON MESSAGETOUSERDIALOGBOXDISPLAYER
                   MHOPRELATION MHOPRELATIONCHILDREN MHOPRELATIONCONTENTS MHOPRELATIONNIL MHOPSPACER1 MHOPSPACER2
                   MHOPSWATCHESSHOWN MIXINFOROBJECTPICKERS MIXINFOROBJECTPILES MIXINFORPROJECTDATAPICKERS
                   MIXINFORPROPERTYHANDLERPICKERS NAMEFIELD NEWCONSTANTMI NEWFILEDIALOGBOX NEWFILEDIALOGBOX1
                   NEWFILENAMEGETTER NEWFUNCTIONMI NEWOBJECTDIALOGBOX NEWPROJECTDIALOGBOX NEWPROJECTNAMEGETTER
                   NEWVARHEADER NEWVARIABLEMI NFDBHIGHLIGHTER NHDBCANCELADDHANDLER NHDBCREATEADDHANDLER NHDBEVENTMENU
                   NHDBHIGHLIGHTER NHDBTHEHANDLERNAMEGETTER NHDBTHEOBJECTNAME NHDBTHEPROJECTNAME NODBACTIONLABEL
                   NODBADDNEWOBJECT NODBCANCELNEWOBJECT NODBHIGHLIGHTER NODBTHEOBJECTNAMEGETTER NODBTHEPARENTNAME
                   NODBTHEPROJECTNAMEGETTER NPDBADDADDPROPERTY NPDBCANCELADDPROPERTY NPDBHIGHLIGHTER NPDBINHERITABLEPROPERTY
                   NPDBLABEL2 NPDBPRIVATEPROPERTY NPDBTHEPROPERTYNAME NPDBTHEPROPERTYNAMEGETTER NUMBERPROPERTYEDITOR
                   NUMBERPROPERTYEDITORTEXT NVDBADDNEWVAR NVDBCANCELNEWVAR NVDBHIGHLIGHTER NVDBTHEVARNAMEGETTER
                   NVDBTHEVARPRIVATECHECK NVDBTHEVARPROJECTNAME NVDBTHEVARVALUEGETTER OBJECTDATARECT OBJECTGRID
                   OBJECTLIST OBJECTNAMEDIALOGBOX OBJECTPICKER OBJECTPILE OBJECTPILEPICKER ONHIGHLIGHTER
                   ONLABEL1 ONTHEOBJECTNAME ONTHEOBJECTNAMEGETTER ONTHEPROJECTNAME OPENFILEDIALOGBOX OPENPROJECTDIALOGBOX
                   OPENPROJECTNEWBUTTON PCPEDITPARENT PCPGETTERBUTTON PCPINHERITABLEBOX PCPPRIVATEBOX PCPPROPAGATE
                   PCPREINHERIT PCPSETTERBUTTON PCPVALUETEXT PDPMENU PDPMENUITEMDISPOSE PE2NUMBERTEXT1 PE2NUMBERTEXT2
                   PE4NUMBERTEXT1 PE4NUMBERTEXT2 PE4NUMBERTEXT3 PE4NUMBERTEXT4 PELABEL PICKERMENU PICKERMENUITEM
                   PICKERMENUITEMSPACER PROJECTDATAPICKER PROJECTDATASHEET PROJECTDATASHEETPICKER PROPERTYCONTROLPANEL
                   PROPERTYDATARECT PROPERTYHANDLERLIST PROPERTYHANDLERPICKER PROPERTYHANDLERSHEET PROPERTYHANDLERSHEETPICKER
                   PROPERTYLIST PROPERTYPICKER PROPERTYPICKERITEMDISPOSE PROPERTYPICKERNEWMENUITEM PROPERTYPICKERPORTMENUITEM
                   PROPERTYPICKERSHOWPRIVATE PROPERTYPICKERSPACERMENUITEM PROPERTYPICKERVIEWTYPEMENUITEM
                   PROPERTYPICKERVIEWTYPEMENUITEMALL PROPERTYPICKERVIEWTYPEMENUITEMGRAPHIC PROPERTYPICKERVIEWTYPEMENUITEMINHERITED
                   PROPERTYPICKERVIEWTYPEMENUITEMLOCAL PROPERTYPICKERVIEWTYPEMENUITEMPARENTS PROPERTYSHEET
                   PROPERTYSHEETPICKER PROPERTYVALUEDATA QUERYFIELD QUERYFIELDHISTORYMENU QUERYFIELDSCRIPTEDITTEXT
                   RELIEFBUTTON RELIEFBUTTONCOLORIN RELIEFBUTTONCOLOROUT RESFILEMENUITEM RESOURCECHOOSER
                   RESOURCESAMPLER RESOURCESAMPLERIMAGE SEARCHFIELD SEARCHFIELDSIMPLETEXT SELECTBYROWTABLEPICKERADDON
                   SELECTFROMCOLLECTIONDIALOGBOX SELECTFROMCOLLECTIONDIALOGCANCELBUTTON SELECTFROMCOLLECTIONDIALOGTEXTLIST
                   SELECTFROMCOLLECTIONDIALOGYESBUTTON SELECTIONDOTS SELECTIONTOOL SIMPLEHISTORYGRAPHRENDERER
                   SIMPLEPROPERTYEDITOR SPEEDITTEXT STACKDEPTHHISTORY STACKDEPTHHISTORYGRAPHER STACKDEPTHHISTORYSCROLLER
                   STACKWATCHER STACKWATCHERFILTERER STACKWATCHERSTACKLIST SWATCHRENDERER TABLEPICKER TABLEPICKEREDITOR
                   TABLEPICKEREDITORADDON TAGDIALOGBOX TDBASTHELABEL TDBCANCELTAGBUTTON TDBCONTAINERMENU
                   TDBHIGHLIGHTER TDBOFLABEL TDBTAGITBUTTON TDBTAGLABEL TDBTHETAGGEDOBJECTNAME TDBTHETAGGEENAME
                   TDBTHETAGNAMEGETTER TILECOLS TILEHSPACING TILEROWS TILEVSPACING TILEWITHRESIZING TILINGCARD
                   TWOBYNBROWSERPICKER TWONUMBERPROPERTYEDITOR UI UNDOABLESETLOG UNDOSLOTLOG UNNAMEOBJECTNAMEDIALOG
                   VALUEEDITOR VALUEEDITORPICKER VALUEEDITORPICKERITEMDISPOSE VALUEEDITORPICKERNEWMENUITEM
                   VALUETEXT VARIABLESHEET VARIABLESHEETPICKER VARITEMDISPOSE YESORNODIALOGBOX YESORNODIALOGCANCELBUTTON
                   YESORNODIALOGDISPLAYER YESORNODIALOGNOBUTTON YESORNODIALOGYESBUTTON)

                  )
#|
	Change History (most recent last):
	79 	12/16/94	rod     	
	80 	 1/ 4/95	sidney  	remove remaining traces of obsoleted lib functionality
	81 	 1/24/95	till    	
	82 	 1/24/95	till    	
	83 	 3/ 1/95	sidney  	
	84 	 3/ 8/95	dy      	
	85 	 3/11/95	dy      	
	86 	 3/13/95	dy      	
	87 	 4/26/95	dy      	
	88 	 4/26/95	dy      	
	3  	 8/17/95	sidney  	
	4  	12/15/95	sidney  	add predefined conditions
	2  	 5/ 7/96	sidney  	Changes for new object system
	3  	 5/ 9/96	sidney  	
	5  	10/18/96	sidney  	remove some unused symbols
	6  	12/19/96	sidney  	
	7  	 2/27/97	Hernan  	
|# ;(do not edit past this line!!)
