;;; SK8 © 1997 by Apple Computer, Inc.
;;; The code in this file is protected under the terms of the current SK8 License.
;;; For information on this license, see http://sk8.research.apple.com
;;; Apple Computer, Inc. -- Apple Research Laboratories


;; Exports updated 12-22-94   5:44 pm

(in-package :UI)



(SK8-declare-syms :UI :private

                  ("User Interface"
                   *ALWAYSHIGHLIGHTONSELECT* *BARLEFT* *MACSTYLEINTERFACE* *OVERRIDE-QUIT-QUESTIONS* *UIFONT*
                   *UIFONTSIZE* *UISIMPLEWINDOWBOTTOMLEFT* *UISIMPLEWINDOWBOTTOMRIGHT* *UISIMPLEWINDOWBOTTOMRIGHT2*
                   *UISIMPLEWINDOWTOPLEFT* *UISIMPLEWINDOWTOPRIGHT* *UISIMPLEWINDOWTOPRIGHT2* *WINDOWBOTTOM*
                   *WINDOWLEFT* *WINDOWRIGHT* *WINDOWTOP* ACTIVATEWIDGET ALIGN-REGION CALCTBSIZE CALCTBTEXT
                   CREATETEXTUREOBJECT DEACTIVATEWIDGET DOASWATCH DOMAKEMENU DOMAKEPROJECTTREE
                   DRAW-FUNCTION-TO-USE DRAWWIRES EDITOBJECTS EDITPROPERTY FIND-NEXT-SIBLING-THAT FIND-PREV-SIBLING-THAT
                   GENERATESWATCH GETEDITLAYER GETPOPUPITEMS GETPREFERENCEOBJECT GETSCRIPTEDS GETTOOLS HALOPREFSDIALOG
                   INIT-UISIMPLEWINDOW-BOTTOMLEFT INIT-UISIMPLEWINDOW-BOTTOMRIGHT INIT-UISIMPLEWINDOW-BOTTOMRIGHT2
                   INIT-UISIMPLEWINDOW-TOPLEFT INIT-UISIMPLEWINDOW-TOPRIGHT INIT-UISIMPLEWINDOW-TOPRIGHT2
                   INTEGRITYCHECKONSWATCHTABLE LINEHEIGHT LOGOUTSWATCHES MAKE-NEW-MEDIA MAKEPROJECTTREE MAKETHESWATCH
                   MAYBE-NEWRESFILE MAYBESAVEPROJECT NOTOKPLUGCOLOR NOTOKSOCKETCOLOR OKPLUGCOLOR OKPROJECTS
                   OKSOCKETCOLOR OKTOEDIT OKTOSELECT? PORTPROXYTABLE PORTRUBBERBAND REMOVESWATCHFROMTABLE
                   SAFECLOSEALLPROJECTS SCOREDFASTTABLEPICKER-DRAW SELECT SELECTFROMPOPUPPALETTE SET-QD-RECT
                   SETUPFOR STORESCRIPTEDS STORETOOLS SWATCHHASHTABLE SWATCHTODO UIARROWDRAW UIDISPLAYSTRING
                   UIFRAMEIT UILDRAW UIMULTILINEPICKER-DRAW UIPAINTIT UIPICKER-DRAW UIWATCHERVOFFSET UPDATEEDITORS
                   UPDATEHANDLEREDITORS UPDATESCRIPTEDITOR UPDATESWATCHOFACTOR USERPICKACTOR WINDOWPREFSDIALOG
                   WITH-OFFSETED-PORT-AND-CLIP)

                  )
#|
	Change History (most recent last):
	83 	12/22/94	rod     	
	84 	 1/ 4/95	sidney  	remove remaining traces of obsoleted lib functionality
	2  	 1/29/96	Brian   	
	2  	 2/27/97	Hernan  	
|# ;(do not edit past this line!!)
