;;; SK8 © 1997 by Apple Computer, Inc.
;;; The code in this file is protected under the terms of the current SK8 License.
;;; For information on this license, see http://sk8.research.apple.com
;;; Apple Computer, Inc. -- Apple Research Laboratories


;; Exports updated 12-21-94   4:56 pm

(in-package :UI)



(SK8-declare-syms :UI :public

                  ("macframes"
                   CLEARCOLLECTION COLLECTEDITEMS DEEPCHILD ITEMPOSITION MYMAPCOLLECTION REMOVEITEM UNUSEDCHILDREN)

                  ("User Interface"
                   ACTIVATETOOL ACTOROKFORCONTENTS ADDEDITLAYER ARROWTODRAW BACKCOLOR BACKGROUNDRECT BAR
                   BEBUTTON BEGETFIELD BEVELDISPLAYER BLACKLINE BLACKSHEET BUSY CACHEDBOUNDS CACHEDITEMS
                   CALLUPPOPUP CGEBUTTON CGEENDSLIDE CGEMENU CGESIMPLEGRADIENTEDITOR CGESTARTSLIDE CHOOSECONDITIONRESPONSE
                   CLEARMODES COLORTOUSE COMMAND COMPLEXRGBGETFIELD CONTEXT CONTEXTLIST CRGBBACKCOLOR CRGBFORECOLOR
                   CRGBMENU CRGBSETBUTTON CRGBSLIDE CURRENTMENU DARKCOLOR DEFAULTCONTAINER DEFAULTITEM DESELECT
                   DESELECTTOOLS DISPLAYER DISPLAYRECT DOUPDATEONPROPERTY DRAGGERBOUNDS DRAGSELECTIONDEEP
                   DRAWTOOLS DUMPBUTTON EDITEDPROJECT EDITLAYER ENDCOLOR ENDOPCOLOR ENTEREDWITHCONTROLKEY
                   ERROROBJECT FIELD FORECOLOR FRONTWINDOW GEBUTTON GEGETFIELD GEMENU GETFIELD GETPILE GFUBUTTON
                   GLOBALSLIST HALOOUTSET HALOSIZE HALOSNAPSHOT HANDLERLISTER HEADING HEBUTTON HEGETFIELD
                   HELPWINDOW HELPWINDOWCHILDRENBUTTON HELPWINDOWDISPLAYER HELPWINDOWFINDLABEL HELPWINDOWINPUTFIELD
                   HELPWINDOWPARENTBUTTON HEMENU HIGHLIGHTER HMENU HOUTSET HSHEET INPUTBACKCOLOR INPUTBACKGROUNDRENDERER
                   INPUTCOLOR INPUTDIRECTION INPUTENDCOLOR INPUTENDOPCOLOR INPUTFORECOLOR INPUTFORERENDERER
                   INPUTHATCHTYPE INPUTLIBRARY INPUTOPCOLOR INPUTPATTERN INPUTPENMODE INPUTPENSIZE INPUTRENDERER
                   INPUTRENDERERLIST INPUTSCALEFACTOR INPUTSPACING INPUTSTARTAT INPUTSTARTCOLOR INPUTSTARTOPCOLOR
                   INSETRECT INSPECTEDLOGOBJECT INSPECTLOGOBJECT INTERSECTIONFIND INVOKEBUTTON INVOKEDWITH
                   IREBUTTON IREGETFIELD IREMENU ITEMOVER LEFTOFFSET LEVEL LIGHTCOLOR LIVEMOTION LOADPREFERENCES
                   LOADTEXTURE LOCALSLIST LOCKEDPALETTE LOGOUTIMAGES MACSTYLEINTERFACE MAKETYPE MEMENUSMENU
                   MEMENUSMENUBAR MEMENUSMENUITEMS MREBUTTON MREGETFIELD MREPICKY MYHANDLER MYHOLDER MYSK8TYPE
                   NEWACTION NEWKEYTARGET NEWSELECTION NFIELD NUMBERTOCREATE OBJECTLISTER OFFCOLOR OFFSTAGELIST
                   OLDBOUNDS OLDOBJECTNAME OLDSELECTION OMENU ONCOLOR OPCOLOR OUTPUTCOLOR OUTPUTMENUBAR PENSIZEGETTER
                   PILE PMENU PMPBMENU POOBJMENU POOBJPICKER PROPERTYLISTER PROPERTYVALUES PROPORTION PROTOTYPES
                   PSHEET QUERYSTRING RECALCONSCROLL RECOMPUTESIZE REDRAWCOLOR REMOVEEDITLAYER RENDEREDGES
                   RENDERERPILE REPLACEFIELD RESETBUTTON RESIZERBOUNDS RESPONSELIST MAYBEREMOVE SALIENTPROPERTIES SAVEDTHISACTIVATION
                   SAVEPREFERENCES SBDOCLISTCOMP SBHANDLISTCOMP SBPROPLISTCOMP SBVALLISTCOMP SELECTIONOK
                   SETBUTTON SETHALOSIZE SETUPCHILDREN SETUPPARENTS SHOWINGDEPENDENCIES SHOWSDRAGGER SHOWSELECTIONHALOTITLEBAR
                   SHOWSRESIZER SHOWSSUBMENUS SHOWSTITLE SIMPLEDIRECTIONGETTER SIMPLERENDERSTYLEGETTER SPACINGGETTER
                   STAGELIST STARTCOLOR STARTOPCOLOR STOREPILE STUCKDOWN TITLEBOUNDS TOGGLE TOOLS TOOLSECTION
                   UIBLUETEXTURES UICOLORIZE UIEDIT UIGRAYTEXTURES UIGREENTEXTURES UIHOLPICKER UIPINKTEXTURES
                   UISEMENUBAR UIWATCHER UIYELLOWTEXTURES UNSTICK UPDATEEDITOR UPDATEGLOBALANDLOCALLISTS
                   VALUETORETURN VMENU VOUTSET WHITEBOX WHITESHEET WINDOWREFERENCE WIREUP ZOOMBOX)

                  )
#|
	Change History (most recent last):
	141	12/21/94	rod     	
	142	 4/26/95	sidney  	
	2  	 2/27/97	Hernan  	
|# ;(do not edit past this line!!)
