;;; SK8 © 1997 by Apple Computer, Inc.
;;; The code in this file is protected under the terms of the current SK8 License.
;;; For information on this license, see http://sk8.research.apple.com
;;; Apple Computer, Inc. -- Apple Research Laboratories


;; Exports updated 12-08-95  10:58 am

(in-package :UI)



(SK8-declare-syms :UI :special

                  ("macframes"
                   ABOUTSTRINGS BLANKPROJECTCOLOR BLANKPROJECTPICT SK8ABOUTCOLOR SK8ABOUTOK SK8ABOUTPICT
                   SK8ABOUTRECT SK8ABOUTTEXT SK8PROJECTCOLOR SK8PROJECTPICT UIINDEXEDVECTOR)

                  ("User Interface"
                   ACTIVATEDSHADOWRENDERER ADDPARENTMENUITEM BACKTOPB BEBOTTOM BELEFT BERIGHT BETOP BEVELDISPLAY
                   BEVELEDITOR BRINGUPMENUITEM CANCELMEDIAIMPORT CGEENDOPSLIDER CGEPENMODEGETTER CGESIMPLEGRADIENTEDITOR
                   CGESTARTOPSLIDER CHILDRENINFO CHILDRENMENU CHOOSERESPONSEDIALOG CHOOSERESPONSEDIALOGDISPLAYBOX
                   CHOOSERESPONSEDIALOGHEADING CHOOSERESPONSEDIALOGINVOKEBUTTON CHOOSERESPONSEDIALOGRESPONSELIST
                   COLORPALETTE COLORPALETTECOLORPICKER COLORPALETTEDIALOGDUPLICATEBUTTON COLORPALETTEDIALOGNEWBUTTON
                   COLORPALETTEMENU COLORPALETTEMENUITEM COLORPALETTENAMEDISPLAYER COLORPALETTEOKBUTTON COMPLEXGRADIENTEDITOR
                   COMPLEXRGBEDITOR CONTENTSVIEWER CPPUMENUITEM CREATIONPROJLABEL CRGBBACKCOLORGETTER CRGBFORECOLORGETTER
                   CRGBOPCOLORSLIDER CRGBPATTERNGETTER CROSSAUTHORMIXIN CURRENTMENUPROXY DARKERRED DARKWARNINGCOLOR
                   DIALOGDIVIDER DRAWPALETTE DRAWPALETTETOOL DRAWPALETTETOOLS DTHIGHLIGHTER EDITOFFRADIOBUTTON
                   EDITONRADIOBUTTON EHMENUITEM EIDINSETRECT EMPTYCOLOR ERRORINSPECTORDIALOG ERRORINSPECTORDIALOGCONTEXTLIST
                   ERRORINSPECTORDIALOGDISPLAYBOX ERRORINSPECTORDIALOGDUMPBUTTON ERRORINSPECTORDIALOGGLOBALSLIST
                   ERRORINSPECTORDIALOGLOCALSLIST ERRORLOGOBJECT FINDOBJECTFINDBUTTON FRAMESCORE GEENDCOLOR
                   GESIMPLECOMPLEXRGBEDITOR GESIMPLEGRADIENTEDITOR GESTARTCOLOR GETMEDIANAME GRADIENTEDITOR
                   HALOLAYOUT HALOPREFERENCESDIALOG HALOPREFSCANCEL HALOPREFSOKBUTTON HALOPREFSPICT HALOPREFSPICTRSRC
                   HALOPREFSSELHI HALOPREFSSHOW HALOPREFSTITLE HANDLERCALLLOGOBJECT HANDLERTRACER 
                   HANDLERTRACERCLEARBPBUTTON HANDLERTRACERSHOWCALLERSCB HATCHEDITOR
                   HEBACKGROUNDRENDERER HEFORERENDERER HESIMPLEHATCHEDITOR HPDRAGFRAME HPHALOINFO HPHALOPICT
                   HPOBJECTTITLE HPREFSRADIOBUTTON HPRESIZEHANDLES HTHANDLERPILE HTWATCHER IMAGERENDEREREDITOR
                   IMPORTMEDIA INFOWINDOW INHERITANCEVIEWER INPUTPORTPROXY INSPECTABLELOGOBJECT INTERSECTIONFINDBUTTON
                   IREBACKGROUNDRENDERER IREOFFSETGETTER IVCHILDREN IVKNOWNUNKNOWN IVMENUBAR IVMENUSPACER
                   IVNAMEFIELD IVPARENTS LIBEDLABEL LIBEDMENU LIBEDNOTSAVEDREFS LIBEDOBJECTLIST LIBEDOBJECTPILE
                   LIBRARYEDITOR LIBRARYPALETTE LIBRARYPALETTELABEL LIBRARYPALETTEMENU LIBRARYPALETTERECT
                   LINESIMPLELINE LISTENERHILITE MAYBENAME MAYBENAMEDIALOG MAYBENONAME MAYBEUSERESNAMES MBASTITLE
                   MBBUTTONSEP MBCOLORPALETTE MBCOPYFILEREFERENCE MBCOPYMEDIA MBIMPORTALL MBIMPORTBUTTON
                   MBIMPORTSEP MBIMPORTTITLE MBLISTENER MBMAKEMENUITEM MBMAKEPOPUP MBMENUEDITOR MBORIGINALSIZE
                   MBPREVIEWTITLE MBRESOURCECHOOSER MBRESOURCESAMPLER MBSHOWPREVIEW MBSPLITTER MBTEXT MBWINDOWBACKGROUNDMENUITEM
                   MBWINDOWCOLOR MBWINDOWMENUITEM MEADDSUBMENU MEBARNAME MEBARNAMELABEL MEDIABROWSER MEEDITEXISTINGMENU
                   MEEDITEXISTINGMENUBAR MEEDITNEWMENU MEITEMNAME MEITEMNAMELABEL MELABEL MEMENUBAR MEMENUBARPROXY
                   MEMENUBARPROXYLABEL MEMENUITEMLINE MEMENULINE MEMENUNAME MEMENUNAMELABEL MEMENUPROXY MEMENUTITLE
                   MEMENUTITLEBOX MENAME MENUEDITOR MENUPROXY MENUPROXYBOX MENUPROXYBOXARROW MENUPROXYLINE
                   MENUTITLEARROWDOWN MENUTITLEARROWRIGHT MEOBJECTLINE MEOBJECTSLABEL MEPUTMENUBARINSTAGE
                   MESCROLLER MESELECTEDMENULABEL MESSAGEBOXABORTEVENT MESSAGEBOXHIDEPB MESSAGEBOXSEARCHERMENUITEM
                   MPBLACKSHEET MPWHITESHEET MRERENDERERPILE MRESIMPLEMULTIRENDEREREDITOR MULTIRENDEREREDITOR
                   NONCROSSAUTHORCOLOR NUMOBJSLABEL OBJECTEDITOR OCSLABEL OCSSLIDER OEHANDLERMENU OEHSHEET
                   OEMENUBAR OENAMEFIELD OEPROPCP OEPROPERTYMENU OEPSHEET OESPLITTER OEVALUETEXT OPCOLORSLIDER
                   OUTPUTPORTPROXY OVALCENTERTOCORNER OVALCORNERTOCORNER PARENTINFO PARENTSMENU PATTERNGETTER
                   PBMENUBROWSER PBMENUBUILD PBMENUCLEAR PBMENUCLOSE PBMENUCLOSEWINDOW PBMENUCOMPACTPROJECT
                   PBMENUCOPY PBMENUCUT PBMENUDRAWPALETTE PBMENUEDIT PBMENUEDITMODE PBMENUHANDLERTRACER PBMENUHANDLERTRACER
                   PBMENUIMPORT PBMENUIMPORTLIBRARY PBMENUINHERITANCEVIEWER PBMENUITEMINFOWINDOW PBMENULOAD
                   PBMENULOADSCRIPT PBMENUMENUBARMOVER PBMENUMESSAGEBOX PBMENUNEW PBMENUPASTE PBMENUPORTWIRINGMODE
                   PBMENUPROJECT PBMENUPROJECTEDITOR PBMENUPROJECTS PBMENUQUIT PBMENUSAVE PBMENUSAVEAS PBMENUSAVEASTEXT
                   PBMENUSELECTALL PBMENUSTACKWATCHER PBMENUSTAGEVIEWER PBMENUTOOLS PBMENUUNDO PBMENUWINDOWS
                   PBMENUWORKSPACE PBMHOLDER PENMODEGETTER PENMODEPOPUPBOX PICKACTORMODE PICKACTORMODERECT
                   PMDEVMODE POBCONSTANTS POBFUNCTIONS POBINCOLOR POBLIBRARIES POBMEDIA POBOBJECTS POBOUTCOLOR
                   POBPILE POBPROTOTYPES POBRENDERER POBVARIABLES POCONSTANTSHEET POFUNCTIONSHEET POLYGONFREEHAND
                   POLYGONPOLYGON POLYGONREGULAR POLYGONSYMEGON POMENUBAR PONEWBUTTON POOBJECTLIST POOBJECTPILE
                   POOBJS POOTHERS POPUPBOX POPUPBOXLABEL POPUPBOXMENU POPUPEVENTMODE POPUPPALETTE POPUPPALETTEITEM
                   POPUPPALETTERECT PORTEDITLAYER PORTEDITLAYERBUTTON PORTEDITLAYERMODE PORTPROXYCONNECTOR
                   PORTPROXYPROTO PORTPROXYPROTOCOLORRECT POSWATCHESSHOWN POVALUETEXT POVARIABLESHEET PROJECTBUILDERMENUBAR
                   PROJECTBUTTONIN PROJECTOVERVIEWER PROJECTOVERVIEWERBUTTON PROPEDITORLABEL PROPERTYEDITOR
                   RDBREPLACEBUTTON RDBREPLACEBUTTONHIGHLIGHT RDBREPLACEFIELD RDBREPLACELABEL RDBREPLACESEARCHBUTTON
                   RDBSEARCHBUTTON RDBSEARCHFIELD RDBSEARCHLABEL RDBWINDOW RECTCENTERTOCORNER RECTCORNERTOCORNER
                   REMOVEPARENTMENUITEM RENDEREREDITORWINDOW RENDERSTYLEGETTER REWGETFIELD REWRESETBUTTON
                   REWSETBUTTON RRECTCENTERTOCORNER RRECTCORNERTOCORNER SAVEASAUDITBUTTON SAVEASBUTTON SAVEASDEPEDENCIES
                   SAVEASEDITOR SAVEASPILE SBHANDLERLIST SBHANDLERVIEWER SBMENUBAR SBMOVEITBUTTON SBOBJECTLIST
                   SBPROPERTYLIST SBQUERYFIELD SBVALUEEDITOR SBVALUETEXT SCHALWAYS SCHIBOX SCHONKEY SCRIPTEDITORINPUTFIELD
                   SCRIPTWATCHINGHANDLERTRACER SEARCHER SEARCHERFINDLABEL SEARCHEROBJECTLIST SEARCHERSEARCHFIELD
                   SEARCHSPACE SEARCHSTYLE SEINSETRECT SELECTIONHALO SELECTIONHALOACTORDRAGGER SELECTIONHALOPOPUP
                   SELECTIONHALOPOPUPADDPROPERTY SELECTIONHALOPOPUPARRANGE SELECTIONHALOPOPUPARRANGEBC SELECTIONHALOPOPUPARRANGEBTF
                   SELECTIONHALOPOPUPARRANGESF SELECTIONHALOPOPUPARRANGESTB SELECTIONHALOPOPUPDESELECT SELECTIONHALOPOPUPDETACH
                   SELECTIONHALOPOPUPDISPOSE SELECTIONHALOPOPUPEDITPROPERTIES SELECTIONHALOPOPUPLOCALHANDLERS
                   SELECTIONHALOPOPUPNAME SELECTIONHALOPOPUPNEWHANDLER SELECTIONHALOPOPUPRECT SELECTIONHALOPOPUPSPACE1
                   SELECTIONHALOPOPUPSPACE2 SELECTIONHALORESIZER SELECTIONHALOTAGPART SELECTIONHALOTITLEBAR
                   SELECTIONLASSOGROW SELECTIONLASSOSHRINK SELECTIONRECTGROW SELECTIONRECTSHRINK SELECTTOOL
                   SELECTTOOLDISPLAYRECT SESEARCHREPLACEWINDOW SHADOWEDRENDERER SHADOWEDRENDERERWITHEDGES
                   SHADOWWHITE SIFHANDLE SIFINSETRECT SIMPLECOMPLEXGRADIENTEDITOR SIMPLECOMPLEXRGBEDITOR
                   SIMPLEDOCUMENTCOLOR SIMPLEFRAME SIMPLEGRADIENTDIRECTIONGETTER SIMPLEGRADIENTEDITOR SIMPLEHATCHDIRECTIONGETTER
                   SIMPLEHATCHEDITOR SIMPLEIMAGERENDEREREDITOR SIMPLEMULTIRENDEREREDITOR SIMPLEPENSIZEGETTER
                   SIMPLERENDEREREDITOR SIMPLERENDEREREDITORVIEW SIMPLERENDERERGETTER SIMPLERGBCOLORGETTER
                   SIMPLESPACINGGETTER SOOFFSTAGELIST SOSPLITTER SOSTAGELIST SPLICEPARENTMENUITEM SRCGLABEL
                   SRCGSWATCH STAGEOVERVIEWER STANDARDINPUTFIELD STANDARDQUERYFIELD SUBMENUPROXY SWATCHCOLORPICKER
                   SWATCHPICKER SWFILTERLABEL SWGRAPHLABEL SWONCHECK SWSPEEDCONTROL SWSPEEDCONTROLLABEL SYSTEMBROWSER
                   TEMPORARYSWATCH TOOLDEFAULTCOLOR UIBIGLABEL UIBIGSPLITTERCOLOR UIBIGSPLITTERCOLOR1 UIBIGSPLITTERCOLOR2
                   UIBIGSPLITTERCOLOR3 UIBKGNDCOLOR UIBKGNDPATTERN UIBOTTOMLEFT UIBOTTOMMIDDLE UIBOTTOMRIGHT
                   UIBOTTOMRIGHT2 UIBUTTON UIBUTTONDISABLEDCOLOR UIBUTTONINCOLOR UIBUTTONOUTCOLOR UICHECKBOX
                   UICHECKBOXCHECK UICHECKBOXDISABLED UICHECKBOXIN UICHECKBOXOFF UICHECKBOXON UICICONALIASTOOL
                   UICICONARROWENDLINE UICICONARROWSLINE UICICONAUTOGROOVE UICICONBOX UICICONCONNECTORLINE
                   UICICONDATAFIELD UICICONEDITTEXTCENTERTOCORNER UICICONEDITTEXTCORNERTOCORNER UICICONFREEHAND
                   UICICONGLUE UICICONGRID UICICONHAND UICICONLABEL UICICONLINEGROOVE UICICONNAMETOOL UICICONOVAL3POINTS
                   UICICONOVALCENTERRADIUS UICICONOVALCENTERTOCORNER UICICONOVALCORNERTOCORNER UICICONPIN
                   UICICONPLUGTOOL UICICONPOLYGON UICICONPOLYGROOVE UICICONPORTPLUGGED UICICONPORTUNPLUGGED
                   UICICONRECTCENTERTOCORNER UICICONRECTCORNERTOCORNER UICICONRECTSIDETOSIDE UICICONREGULARPOLYGON
                   UICICONREPLICATOR UICICONRRECTCENTERTOCORNER UICICONRRECTCORNERTOCORNER UICICONRRECTSIDESIDERADIUS
                   UICICONSELECTLASSOGROW UICICONSELECTLASSOSHRINK UICICONSELECTRECTGROW UICICONSELECTRECTSHRINK
                   UICICONSIMPLELINE UICICONSOCKET UICICONSPRING UICICONSYMEGON UICICONTAGTOOL UICICONTEXTFIELD
                   UICICONTEXTTOOL UICICONTRACE UICICONVIEWER UICLOSEBOXCICN UICLOSEBOXRENDERER UICOLORALIASTOOL
                   UICOLORAQUATILE UICOLORARROWENDLINE UICOLORARROWSLINE UICOLORAUTOGROOVE UICOLORBOX UICOLORCONNECTORLINE
                   UICOLORDATAFIELD UICOLOREDITTEXTCENTERTOCORNER UICOLOREDITTEXTCORNERTOCORNER UICOLORFREEHAND
                   UICOLORGLUE UICOLORGRID UICOLORHAND UICOLORLABEL UICOLORLINEGROOVE UICOLORNAMETOOL UICOLOROVAL3POINTS
                   UICOLOROVALCENTERRADIUS UICOLOROVALCENTERTOCORNER UICOLOROVALCORNERTOCORNER UICOLORPIN
                   UICOLORPLUGTOOL UICOLORPOLYGON UICOLORPOLYGROOVE UICOLORPORTPLUGGED UICOLORPORTUNPLUGGED
                   UICOLORRECTCENTERTOCORNER UICOLORRECTCORNERTOCORNER UICOLORRECTSIDETOSIDE UICOLORREGULARPOLYGON
                   UICOLORREPLICATOR UICOLORRRECTCENTERTOCORNER UICOLORRRECTCORNERTOCORNER UICOLORRRECTSIDESIDERADIUS
                   UICOLORSELECTLASSOGROW UICOLORSELECTLASSOSHRINK UICOLORSELECTRECTGROW UICOLORSELECTRECTSHRINK
                   UICOLORSIMPLELINE UICOLORSK8 UICOLORSOCKET UICOLORSPRING UICOLORSYMEGON UICOLORTAGTOOL
                   UICOLORTEXTFIELD UICOLORTEXTTOOL UICOLORTRACE UICOLORVIEWER UICOLORWEAVE UICURSORCOLOR
                   UICURSORGRABLEFTCLOSED UICURSORGRABLEFTOPEN UICURSORGRABRIGHTCLOSED UICURSORGRABRIGHTOPEN
                   UICURSORHOME UICURSORPLUCKLEFTCLOSED UICURSORPLUCKLEFTOPEN UICURSORPLUCKRIGHTCLOSED UICURSORPLUCKRIGHTOPEN
                   UICURSORPLUCKUPCLOSED UICURSORPLUCKUPOPEN UICURSORWIREFROM UICURSORWIRETO UICURSORZOOMIN
                   UICURSORZOOMOUT UIDARKCOLOR UIDARKTEXTURE UIDARKTEXTURERSRC UIDEFAULTMENURGB UIDOWNARROW1
                   UIDOWNARROW2 UIDOWNARROWCICN UIDOWNARROWRENDERER UIEDITMODE UIGROWBOXCICN UIGROWBOXRENDERER
                   UIHILITEBOXCICN UIHILITEBOXRENDERER UIHOL UIHORIZONTALSCROLLER UILEFTARROW1 UILEFTARROW2
                   UILEFTARROWCICN UILEFTARROWRENDERER UILIGHTCOLOR UILIGHTESTGRAY UILIGHTTEXTURE UILIGHTTEXTURERSRC
                   UILITTLESPLITTER UILITTLESPLITTERCOLOR UILITTLESPLITTERCOLOR1 UILITTLESPLITTERCOLOR2 UILITTLESPLITTERCOLOR3
                   UIMENUACTOR UIMENUBARACTOR UIMENUCOLOR UIMENUDISABLED UIMENUIN UIMENUOUT UIMENURENDERER
                   UIMIDDLE UIMIDDLELEFT UIMIDDLERIGHT UINOBBYTEXTURE UINOBBYTEXTURERSRC UIOBJECTDRAGMIXIN
                   UIPATTERNAQUATILE UIPATTERNSK8 UIPATTERNWEAVE UIPELBUTTON UIPOPUP UIPREFERENCES UIPRESSEDDOWNARROWCICN
                   UIPRESSEDDOWNARROWRENDERER UIPRESSEDLEFTARROWCICN UIPRESSEDLEFTARROWRENDERER UIPRESSEDRIGHTARROWCICN
                   UIPRESSEDRIGHTARROWRENDERER UIPRESSEDUPARROWCICN UIPRESSEDUPARROWRENDERER UIRADIOBUTTON
                   UIRADIOBUTTONDISABLED UIRADIOBUTTONIN UIRADIOBUTTONOFF UIRADIOBUTTONON UIRENDERER UIRIGHTARROW1
                   UIRIGHTARROW2 UIRIGHTARROWCICN UIRIGHTARROWRENDERER UISCRIPTEDITOR UISCROLLERBODY UISCROLLERBODYHORIZONTAL
                   UISCROLLERTHUMB UISCROLLERTHUMBCICN UISCROLLERTHUMBHORIZONTAL UISCROLLERTHUMBRENDERER
                   UISEHSCROLLER UISELECTIONTOOL UISEVSCROLLER UISIMPLEWINDOW UISMALLLABEL UISPLITTER UITEXTLIST
                   UITEXTLISTFORCORNERS UITEXTLISTPICKER UITEXTLISTSCROLLER UITEXTUREDATA UITOPLEFT UITOPLEFT2
                   UITOPMIDDLE UITOPMIDDLE2 UITOPRIGHT UITOPRIGHT2 UIUPARROW1 UIUPARROW2 UIUPARROWCICN UIUPARROWRENDERER
                   UIVALUETEXT UIVALUETEXTBOX UIVALUETEXTCANCEL UIVALUETEXTGFUB UIVALUETEXTLINE UIVALUETEXTOK
                   UIVERTICALSCROLLER UIWATCHERSCROLLER UIWINDOWCOLOR UIWINSETRECT UIZOOMBOXCICN UIZOOMBOXRENDERER
                   USERPALETTE USERPALETTELABEL USERPALETTERECT UTLINSETRECT WARNINGCOLOR WINDOWPREFERENCESDIALOG
                   WINDOWPREFSCANCEL WINDOWPREFSOKBUTTON WINDOWPREFSPICT WINDOWPREFSPICTRSRC WINDOWPREFSTITLE
                   WPWINDOWBUTTON WPWINDOWPICT)

                  )
#|
	Change History (most recent last):
	2  	12/ 8/95	Brian   	
	2  	 5/ 9/96	Hernan  	
	3  	 5/10/96	Hernan  	Adding handlerTracer stuff.
	4  	 5/13/96	sidney  	
	5  	 2/27/97	Hernan  	
|# ;(do not edit past this line!!)
