;;; SK8 © 1997 by Apple Computer, Inc.
;;; The code in this file is protected under the terms of the current SK8 License.
;;; For information on this license, see http://sk8.research.apple.com
;;; Apple Computer, Inc. -- Apple Research Laboratories

(in-package :graphics-system)

;;; _______________________________ 
;;; Exports
;;; _______________________________ 

;;; from "Kernel"

(export '($hilite
          *bkg-window*
          *bkgnd-color-type*
          *currenttla*
          *edittext-the-object*
          *event-location*
          *eventtime*
        *event-window*
        *event-x*
        *event-y*
        *EditText-the-object*
        *fast-draw*
        *force-click*
        *help-message-record*
        *last-click-object*
        *last-click-time*
        *last-mouseDown-location*
        *last-mouseDown-object*
        *last-mouseDown-time*
        *live*
        *monitor-depths*
        *movies-initialized*
        *no-ui-windows*
        *sk8-menu-item*
        *sk8-menu*
        *sk8-windoid*
        *sk8-window*
        *stage*
        *unsettable-secret-property-message*
        0.5pi 
        1.5pi 
        2pi
        acceptsdrops!
        acceptsdrops?
        actflags
        actor-line-height
        actor-text-size
        add-to-translucent-contents
        alignmentOfBoundsToBounds
        alignSizeToBounds
        autohilite!
        autohilite?
        autotab!
        autotab?
        belongstoboundedbycontents!
        belongstoboundedbycontents?
        belongstocachedpixmap!
        belongstocachedpixmap?
        boundedbycontents!
        boundedbycontents?
        boundsdirty!
        boundsdirty?
        boundstodirtyregion!
        boundstodirtyregion?
        boxHeight
        boxSize
        boxWidth
        cache-pixmap
        cachespixmap!
        cachespixmap?
        call-with-temp-string
        closest-qd-point-to
        compute-text-width
        compute-maybe-truncated-text
        computeMaybeTruncatedText
        computed-active-windoid
        computed-active-window
        constrainSizeToAspectRatio
        constrainBoundsToAspectRatio
        contentsdirty!
        contentsdirty?
        coords-distance
        coords-in-rect-p
        copy-bits
        copy-pt
        copy-rect
        copy-sk8rect
        currentmode
        deeply-visible?
        deinstall-background
        depth
        dirty-one-node
        dirty-nodes
        dirty-nodes*
        dirty-region
        dirty-subnodes*
        dirty-window-p
        disable-whiting
        dispatch-mouseenter&leave
        dispatch-mousewithins
        dispose-node-records
        distance
        dither
        dlist-empty?
        docontents
        docontents-btof
        do-pstr-chunks
        draggable!
        draggable?
        drawenabled
        enable-whiting
        ensureType
        every-subactor
        f*
        f+
        f-
        f.float
        f.round
        f/
        faverage
        f.ceiling
        fdouble
        fhalf
        fdecf
        fdouble
        fillcolorisdynamic!
        fillcolorisdynamic?
        filldirty!
        filldirty?
        filltodirtyregion!
        filltodirtyregion?
        fincf
        find-physical-offset
        find-region-offset
        findbackground
        first-click
        floats!
        floats?
        fmod
        framecolorisdynamic!
        framecolorisdynamic?
        framedirty!
        framedirty?
        frametodirtyregion!
        frametodirtyregion?
        f.trunc
        get-style-number
        get-wmgr-port
        geteventkey
        getRectShapeFromUser
        gworld-pixmap
        gworld-rectangle
        gworld-to-gworld
        gWorld-to-window
        gWorld
        hasconnectors!
        hasconnectors?
        hasnocontents?
        haswindow!
        haswindow?
        hideMenuBar
        hilited!
        hilited?
        hrref
        initialize-cached-pixmap-from-parent
        inset-rect
        install-background
        install-sk8-wdef
        int-to-fixed
        intersect-rects
        inverted!
        inverted?
        just-do-mouseenters
        last-zoom-place
        leave-object-under-mouse-if-in
        let+
        limitTo01
        list-to-vector
        lock-gworld
        locked
        lockwindow
        logical-to-physical
        logical-to-stage-list
        logical-to-user-rect-coords
        logicalboundsrectdirty!
        logicalboundsrectdirty?
        mainMonitor
        mainMonitorCenter
        make-bitmap
        make-dlist
        make-new-node-dirty
        make-node-dirty
        make-pt
        make-rect
        making-self-dirty
        map-nodes*
        map-nodes
        map-subnodes*
        map-subnodes
        mode-arg
        mouseNormal?
        mouseNormal!
        mouseOpaque?
        mouseOpaque!
        mouseTransparent?
        mouseTransparent!
        mouseInvisible?
        mouseInvisible!
        mouseCustom?
        mouseCustom!
        moveToPosition
        move-to-position-help
        movies
        my-actor-object
        nameAlreadyInUse
        node-boundsregion
        node-container
        node-contents
        node-contentsdrawfunction
        node-doubleclickstyle
        node-drawfunction
        node-fillcolor
        node-fillregion
        node-flags
        node-framecolor
        node-frameregion
        node-framesize
        node-lines
        node-logicalboundsrect
        node-logicalxscale
        node-logicalyscale
        node-mousestatus
        node-offsetby
        node-physicalboundsrect
        node-pixmap
        node-properties
        node-translucentcontents
        node-window
        node-xorigin
        node-xscale
        node-yorigin
        node-yscale
        nodeseendirtybywindow!
        nodeseendirtybywindow?
        object-under-mouse
        objectdirty!
        objectdirty?
        offset-point-list
        offset-rect
        offsetsregions!
        offsetsregions?
        onlylocationchanged!
        onlylocationchanged?
        opaque!
        opaque?
        ownedregion!
        ownedregion?
        owners
        physical-to-logical
        physicalboundsrectdirty!
        physicalboundsrectdirty?
        pixmapdirty!
        pixmapdirty?
        point-in-rect-p
        point-to-sk8coords
        popcurrentmode
        port-origin
        preserve-clos-window
        pt-h
        pt-v
        range
        real-logical-to-physical
        real-physical-to-logical
        recompute-bounds-region
        recompute-fill-region
        recompute-frame-region
        recompute-logicalboundsrect
        recompute-physicalboundsrect
        rect-bottom
        rect-center-coords
        rect-center-cords
        rect-left
        rect-right
        rect-size
        rect-top
        rects-intersect
        rects-overlap-p
        redraw-background
        region-into-rect
        regions-intersect
        relativize-pathname
        remove-dirty-from-window
        remove-from-translucent-contents
        resizable!
        resizable?
        resizescontents!
        resizescontents?
        restore-clos-window
        restore-text-state
        rotate-coords-2d
        roundBoxDimensions
        selecting-clos-window
        set-dirty-contents-flag
        set-object-under-mouse
        set-point
        set-preserved-info
        set-rect
        set-rect-center
        set-rect-size
        set-text-state
        setcurrentmode
        showMenuBar
        simple-set-physical-rect-size
        simple-set-rect-size
        sk8-autokey-event
        sk8-bring-up-new-window
        sk8-close-window
        sk8-draw-contents
        sk8-draw-contents-with-translucency
        sk8-draw-data
        sk8-full-draw
        sk8-keydown-event
        sk8-keyup-event
        sk8-mousedown-event
        sk8-mouseup-event
        sk8-non-floater-p
        sk8-null-event
        sk8-point-in-which-node
        sk8-point-in-which-object
        sk8-point-in-which-window
        sk8-select-old-window
        sk8-simple-draw
        sk8-spurious-event
        sk8-subactors-draw
        sk8-text-draw
        sk8-update-event
        sk8-update-window-gworld
        sk8-windoid-p
        sk8-window-p
        sk8coords-to-point
        somerenderersaredynamic!
        somerenderersaredynamic?
        splice
        spliceAtPosition
        stage-to-logical-list
        stage-to-window-coords
        stage-to-window-list
        stage-to-window-rect-coords
        string-region
        style
        subtract-points
        textcolorisdynamic!
        textcolorisdynamic?
        track-mousedown
        translucentContents?
        uncache-pixmap
        union-rects
        unlock-gworld
        unlockwindow
        update-bounds-region
        update-event-vars
        update-fill-region
        update-frame-region
        user-to-logical-rect-coords
        vector-insert-before
        vector-move-item-backward
        vector-move-item-before
        vector-move-item-forward
        vector-to-list
        visible!
        visible?
        wait-time-period
        want-idle
        wantsidle!
        wantsidle?
        wantsmousewithin!
        wantsmousewithin?
        while-scrolling
        window-pixmap
        window-rectangle
        window-to-gWorld
        window-to-stage-coords
        window-to-stage-rect
        window-to-stage-rect-coords
        window-topleft-offset
        window-unlocked-p
        with-clipped-region
        with-composed-clip
        with-drawing-lock
        with-fast-node-slots
        with-gWorld-rectangle
        with-hilitecolor
        with-offscreen-gworld
        with-queued-drawing
        with-temporary-port
        with-zero-origin
        withdrawdisabled
        withlockedactor
        withlockedmenubar
        withlockedwindow
        without-events
        |WITH HIGHLIGHTCOLOR|
        )
        :gs)
         

#|
	Change History (most recent last):
	1  	 4/19/96	sidney  	new file, extracted from import/export to be compiled separately
	2  	 5/ 7/96	sidney  	Changes for new object system
	3  	 7/18/96	sidney  	remove *events-on* which isn't in this package
	4  	 7/25/96	sidney  	remove *current-event* which isn't in this package
	5  	10/ 7/96	sidney  	disposing-clos-window is now obsolete
	6  	 2/27/97	Hernan  	
|# ;(do not edit past this line!!)
